"""Compatibility re-exports for ``quant_fund.research.catalog.constants``.

The definitions live in :mod:`quant_fund.research.catalog.registry`.
"""

from __future__ import annotations

from quant_fund.research.catalog.registry import (
    BENCHMARK_CATALOG_VERSION,
    BENCHMARK_FAMILY_ORDER,
    DEFAULT_BENCHMARK_FAMILIES,
    FORBIDDEN_RESEARCH_METRIC_KEYS,
    LIVE_OPTIONAL_BENCHMARK_FAMILIES,
    OPTIONAL_BENCHMARK_FAMILIES,
    PREFERRED_CHRISTOFFERSEN_IND_KEYS,
    REQUIRED_BENCHMARK_FAMILIES,
    REQUIRED_CHRISTOFFERSEN_CC_KEYS,
    RESEARCH_RECEIPT_SCHEMA_VERSION,
    RESEARCH_RECEIPT_SCHEMA_VERSIONS_ACCEPTED,
    RETIRED_BENCHMARK_FAMILIES,
)

__all__ = [
    "BENCHMARK_CATALOG_VERSION",
    "BENCHMARK_FAMILY_ORDER",
    "DEFAULT_BENCHMARK_FAMILIES",
    "FORBIDDEN_RESEARCH_METRIC_KEYS",
    "LIVE_OPTIONAL_BENCHMARK_FAMILIES",
    "OPTIONAL_BENCHMARK_FAMILIES",
    "REQUIRED_BENCHMARK_FAMILIES",
    "PREFERRED_CHRISTOFFERSEN_IND_KEYS",
    "REQUIRED_CHRISTOFFERSEN_CC_KEYS",
    "RESEARCH_RECEIPT_SCHEMA_VERSION",
    "RESEARCH_RECEIPT_SCHEMA_VERSIONS_ACCEPTED",
    "RETIRED_BENCHMARK_FAMILIES",
]
