/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/harness/backends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Backends Status
         * @description Per-backend liveness: configured flag plus circuit state —
         *     whether the breaker is fast-failing this backend, how much
         *     cooldown remains, and the consecutive-fault streak.
         */
        get: operations["backends_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harness/backends/{name}/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Backend Probe
         * @description Deep health: run one minimal gated completion through the real
         *     resolver. Unlike ``GET /harness/backends`` (config + circuit state),
         *     this answers "can this backend serve right now" — including a BYOK
         *     endpoint supplied inline. Deliberately bypasses the breaker admit
         *     and never reports to it, so a monitoring scrape can't trip or heal
         *     the circuit; the verdict series lands under ``probe:<name>``.
         */
        post: operations["backend_probe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harness/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Capabilities
         * @description Discovery: the wire features this build serves and the
         *     operational limits actually in effect. A client learns batch
         *     caps, store bounds, rate limits, and feature flags (idempotency,
         *     SSE, webhooks, drain) from one call — nothing is hardcoded.
         */
        get: operations["get_capabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harness/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Commands */
        get: operations["list_commands"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harness/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete */
        post: operations["complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harness/complete/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Batch */
        post: operations["complete_batch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harness/complete/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Stream
         * @description Server-sent-event stream of one gated completion.
         *
         *     The backend's token deltas are buffered, the joined text passes the
         *     honesty gate, and only then are chunks emitted as ``token`` events
         *     plus a ``final`` envelope — no ungated model bytes ever reach a
         *     ``data:`` frame. A backend without ``stream`` fails 501 rather than
         *     faking chunking.
         *
         *     With ``sse_keepalive_s`` > 0 (default 15) the buffer+gate phase runs
         *     on a worker thread under a one-interval grace period: outcomes that
         *     resolve within the interval keep today's wire contract exactly —
         *     completions stream as usual, failures stay ordinary JSON error
         *     responses. Only a generation still running past the interval
         *     commits to SSE: ``: keepalive`` comment frames (no payload —
         *     parsers ignore them) hold the connection open against proxy/LB
         *     idle timeouts, and a failure after that point arrives as a terminal
         *     ``{"type": "error", "status", "detail"}`` data frame followed by
         *     ``[DONE]`` (the HTTP status is committed once a byte is on the
         *     wire). ``sse_keepalive_s`` = 0 disables the worker entirely — the
         *     fully synchronous path.
         */
        post: operations["complete_stream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harness/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Completions List
         * @description Newest-first window on the completion log — per-call evidence
         *     (hashes, usage, verdict) for every gated model call the process
         *     has served, bounded by the ring.
         */
        get: operations["completions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harness/completions/{completion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Completion Get */
        get: operations["completion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harness/drain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Drain
         * @description Latch drain mode (one-way): gated routes refuse new work with
         *     503 while in-flight requests finish; ``/health``, ``/metrics``
         *     and ``/ready`` keep answering so orchestrators can watch
         *     ``inflight`` bleed to zero before stopping the process.
         *     Idempotent — re-POSTing just re-reads the latch. ``wait_s>0``
         *     blocks (server-side) until in-flight work empties or the window
         *     lapses; ``drained`` reports which happened.
         */
        post: operations["drain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harness/gate/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gate Check
         * @description Pre-flight the honesty gate without spending model tokens —
         *     writers (fx-1 or BYOK callers) can validate text before or after
         *     generation. Advisory: not slot-gated, stays up during drain, and
         *     never touches a backend or the metrics series.
         */
        post: operations["gate_check"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harness/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description Job inventory, newest first: ``status`` filter + offset/limit
         *     paging; ``total`` is the filtered count before the page is cut.
         */
        get: operations["list_jobs"];
        put?: never;
        /**
         * Submit Job
         * @description Async run submission: work starts in the background, the caller
         *     polls ``GET /harness/jobs/{job_id}`` for the terminal record (also
         *     echoed as the ``Location`` header). Same drain/cap/idempotency
         *     contract as the sync route.
         */
        post: operations["submit_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harness/jobs/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Jobs Batch
         * @description Fan-out submit: each item takes the same path as the single
         *     route — command validation, drain latch, inflight cap, and
         *     per-item ``idempotency_key`` dedup (headers carry no per-item
         *     keys, so the body field is the channel here). An item that fails
         *     lands in its own ``jobs[i]`` slot as ``{error, code}`` — the
         *     batch reports honest ``submitted``/``failed`` counts rather than
         *     turning one bad item into a whole-batch failure.
         */
        post: operations["submit_jobs_batch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harness/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Status */
        get: operations["get_job"];
        put?: never;
        post?: never;
        /**
         * Cancel Job
         * @description Cooperative cancel: a queued job flips to 'cancelled' and its
         *     executor slot frees on dequeue. Running and terminal jobs 409 —
         *     the subprocess runner has no mid-run kill handle.
         */
        delete: operations["cancel_job"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harness/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Events
         * @description SSE job-status stream: the job record arrives as an
         *     ``event: job`` frame on every change until a terminal status,
         *     then the stream closes. ``: keepalive`` comment frames fire every
         *     ``sse_keepalive_s`` while the job is quiet; ``timeout_s`` bounds
         *     the stream — reconnect (and resume from the last frame) to keep
         *     watching. Same read path as ``GET /harness/jobs/{job_id}`` — a
         *     snapshot before the stream opens, so an unknown id 404s rather
         *     than hanging.
         */
        get: operations["stream_job_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harness/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Command */
        post: operations["run_command"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harness/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version Info
         * @description Version negotiation: the wire contract + package release.
         */
        get: operations["get_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics Route
         * @description Ops snapshot — JSON by default; Prometheus text exposition via
         *     ``?format=prom`` or an ``Accept: text/plain``/OpenMetrics header.
         */
        get: operations["get_metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Kubernetes-style readiness: 200 while accepting work, 503 once
         *     drain is latched — the load balancer's signal to deregister the
         *     pod before gated routes start refusing.
         */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Receipts Index
         * @description List the store's sealed receipts: sha256 → filename, sorted.
         */
        get: operations["receipts_index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Receipt */
        post: operations["verify_receipt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/verify/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Receipts Batch */
        post: operations["verify_receipts_batch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/{sha256}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Receipt Fetch
         * @description Serve the sealed receipt addressed by its content hash.
         *
         *     The body is the receipt's committed bytes verbatim, and receipts are
         *     content-addressed by their seal — so ``ETag`` is the hash itself and
         *     the response is ``Cache-Control: immutable``. Validity under the live
         *     verifier is reported on ``X-Fx1-Receipt-Valid`` so a caller learns
         *     the receipt it fetched still verifies without a second round trip.
         */
        get: operations["receipt_fetch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BackendCompletionStats
         * @description Per-backend completion accounting: outcome counts, a cumulative
         *     latency histogram (edges are ``_LAT_BUCKETS_MS`` plus ``+Inf``), and
         *     backend-reported token sums. ``usage_calls`` counts calls that carried
         *     a usage dict — a silent provider shows zero tokens AND zero calls.
         */
        BackendCompletionStats: {
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
            /**
             * Error
             * @default 0
             */
            error: number;
            /**
             * Latency Buckets
             * @default {}
             */
            latency_buckets: {
                [key: string]: number;
            };
            /**
             * Latency Count
             * @default 0
             */
            latency_count: number;
            /**
             * Latency Sum Ms
             * @default 0
             */
            latency_sum_ms: number;
            /**
             * Ok
             * @default 0
             */
            ok: number;
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
            /**
             * Usage Calls
             * @default 0
             */
            usage_calls: number;
        };
        /**
         * BackendProbeRequest
         * @description Optional controls for a backend liveness probe — same credential
         *     plumbing as a completion, so a BYOK probe tests the caller's real
         *     endpoint. ``prompt`` defaults to a one-token ping.
         */
        BackendProbeRequest: {
            byok?: components["schemas"]["ByokOverride"] | null;
            /** Checkpoint Dir */
            checkpoint_dir?: string | null;
            /**
             * Prompt
             * @default ping
             */
            prompt: string;
            /** Timeout S */
            timeout_s?: number | null;
        };
        /**
         * BackendProbeResponse
         * @description Deep-health verdict for one backend — whether a real minimal
         *     completion succeeded, how long it took, and why not when it didn't.
         */
        BackendProbeResponse: {
            /** Backend */
            backend: string;
            /** Error */
            error?: string | null;
            /** Error Class */
            error_class?: string | null;
            /** Latency Ms */
            latency_ms: number;
            /** Model */
            model?: string | null;
            /** Ok */
            ok: boolean;
        };
        /**
         * BackendProbeVerdict
         * @description The most recent ``/harness/backends/{name}/probe`` outcome — kept
         *     process-local so a monitoring scrape can read the last deep-health
         *     verdict without spending another live call.
         */
        BackendProbeVerdict: {
            /** Checked At */
            checked_at: number;
            /** Error Class */
            error_class?: string | null;
            /** Latency Ms */
            latency_ms: number;
            /** Ok */
            ok: boolean;
        };
        /**
         * BackendStatusEntry
         * @description One backend's liveness surface: whether it is configured and, when
         *     the circuit breaker is enabled, whether it is currently fast-failing.
         */
        BackendStatusEntry: {
            /** Circuit Open */
            circuit_open: boolean;
            /** Configured */
            configured: boolean;
            /** Consecutive Failures */
            consecutive_failures: number;
            /** Cooldown Remaining S */
            cooldown_remaining_s: number;
            last_probe?: components["schemas"]["BackendProbeVerdict"] | null;
        };
        /**
         * ByokOverride
         * @description Per-request BYOK credentials — the caller's own OpenAI-compatible
         *     endpoint. ``api_key`` is used for the upstream call only; it is never
         *     logged and never echoed into error text. The idempotency fingerprint
         *     is hashed, so the stored dedupe record carries no secret bytes.
         */
        ByokOverride: {
            /** Api Key */
            api_key: string;
            /** Base Url */
            base_url: string;
            /** Model */
            model: string;
        };
        /**
         * CapabilitiesResponse
         * @description Self-describing discovery payload: which wire features this build
         *     serves and the operational limits in effect — clients self-configure
         *     (batch sizes, retry budgets, stream use) from one call instead of
         *     hardcoding server internals.
         */
        CapabilitiesResponse: {
            /** Api Version */
            api_version: string;
            /** Backends */
            backends: {
                [key: string]: boolean;
            };
            /** Features */
            features: {
                [key: string]: boolean;
            };
            /** Fx1 Version */
            fx1_version: string;
            /** Limits */
            limits: {
                [key: string]: number;
            };
            /** Roles */
            roles: string[];
        };
        /** ChatMessage */
        ChatMessage: {
            /** Content */
            content: string;
            /** Role */
            role: string;
        };
        /** CompleteBatchItem */
        CompleteBatchItem: {
            /** Completion Id */
            completion_id?: string | null;
            /** Content */
            content?: string | null;
            /** Error */
            error?: string | null;
            /** Error Class */
            error_class?: string | null;
            /** Latency Ms */
            latency_ms: number;
            /** Ok */
            ok: boolean;
        };
        /** CompleteBatchRequest */
        CompleteBatchRequest: {
            /**
             * Backend
             * @enum {string}
             */
            backend: "hosted_k3" | "local_fx1" | "byok";
            /** Batch */
            batch: components["schemas"]["ChatMessage"][][];
            byok?: components["schemas"]["ByokOverride"] | null;
            /** Checkpoint Dir */
            checkpoint_dir?: string | null;
            /**
             * Max Workers
             * @default 4
             */
            max_workers: number;
            /** Receipt Hashes */
            receipt_hashes?: string[] | null;
            /** Timeout S */
            timeout_s?: number | null;
        };
        /** CompleteBatchResponse */
        CompleteBatchResponse: {
            /** Backend */
            backend: string;
            /** Model */
            model: string | null;
            /** Receipt Hashes */
            receipt_hashes: string[];
            /**
             * Replayed
             * @default false
             */
            replayed: boolean;
            /** Results */
            results: components["schemas"]["CompleteBatchItem"][];
            /** Usage Total */
            usage_total?: {
                [key: string]: number;
            } | null;
        };
        /** CompleteRequest */
        CompleteRequest: {
            /**
             * Backend
             * @enum {string}
             */
            backend: "hosted_k3" | "local_fx1" | "byok";
            byok?: components["schemas"]["ByokOverride"] | null;
            /** Checkpoint Dir */
            checkpoint_dir?: string | null;
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
            /** Receipt Hashes */
            receipt_hashes?: string[] | null;
            /** Timeout S */
            timeout_s?: number | null;
        };
        /** CompleteResponse */
        CompleteResponse: {
            /** Backend */
            backend: string;
            /** Completion Id */
            completion_id?: string | null;
            /** Content */
            content: string;
            /** Latency Ms */
            latency_ms: number;
            /** Model */
            model: string | null;
            /** Receipt Hashes */
            receipt_hashes: string[];
            /**
             * Replayed
             * @default false
             */
            replayed: boolean;
            /** Usage */
            usage?: {
                [key: string]: number;
            } | null;
        };
        /** CompletionListResponse */
        CompletionListResponse: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["CompletionRecord"][];
        };
        /**
         * CompletionRecord
         * @description One recorded model call: hashes of what went in and came out,
         *     latency, reported usage, and the verdict — the harness's own calls
         *     are auditable evidence. Content itself is never stored (hashes only),
         *     and the log is a bounded in-process ring.
         */
        CompletionRecord: {
            /** At */
            at: number;
            /** Backend */
            backend: string;
            /** Completion Id */
            completion_id: string;
            /** Error */
            error?: string | null;
            /** Error Class */
            error_class?: string | null;
            /** Latency Ms */
            latency_ms: number;
            /** Model */
            model?: string | null;
            /** Ok */
            ok: boolean;
            /** Output Sha256 */
            output_sha256?: string | null;
            /** Prompt Sha256 */
            prompt_sha256: string;
            /** Usage */
            usage?: {
                [key: string]: number;
            } | null;
        };
        /**
         * DrainResponse
         * @description Result of latching drain mode: state + live in-flight count.
         */
        DrainResponse: {
            /**
             * Drained
             * @default false
             */
            drained: boolean;
            /** Draining */
            draining: boolean;
            /** Inflight */
            inflight: number;
        };
        /**
         * GateCheckRequest
         * @description Text to run through the honesty gate — pre-flight for writers
         *     before they spend model tokens (or for validators on the way out).
         */
        GateCheckRequest: {
            /** Text */
            text: string;
        };
        /**
         * GateCheckResponse
         * @description Gate verdict — ``ok`` mirrors whether the text would pass the gate;
         *     ``error`` carries the refusal reason when it wouldn't.
         */
        GateCheckResponse: {
            /** Error */
            error?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HarnessCommandItem */
        HarnessCommandItem: {
            /** Argv */
            argv: string[];
            /** Description */
            description: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Timeout S */
            timeout_s: number;
        };
        /** HarnessCommandListResponse */
        HarnessCommandListResponse: {
            /** Items */
            items: components["schemas"]["HarnessCommandItem"][];
            /** Total */
            total: number;
        };
        /**
         * HarnessRole
         * @enum {string}
         */
        HarnessRole: "data_engine" | "evaluation" | "verification" | "model_training";
        /** HarnessRunRequest */
        HarnessRunRequest: {
            /** Callback Secret */
            callback_secret?: string | null;
            /** Callback Url */
            callback_url?: string | null;
            /** Command */
            command: string;
            /** Config */
            config?: string | null;
            /** Extra Args */
            extra_args?: string[];
            /** Idempotency Key */
            idempotency_key?: string | null;
        };
        /** HarnessRunResponse */
        HarnessRunResponse: {
            /** Command */
            command: string;
            /** Exit Code */
            exit_code: number;
            /** Ok */
            ok: boolean;
            /**
             * Replayed
             * @default false
             */
            replayed: boolean;
            /** Stderr */
            stderr: string;
            /**
             * Stderr Truncated
             * @default false
             */
            stderr_truncated: boolean;
            /** Stdout */
            stdout: string;
            /**
             * Stdout Truncated
             * @default false
             */
            stdout_truncated: boolean;
            /** Timeout S */
            timeout_s: number;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Backends */
            backends: {
                [key: string]: boolean;
            };
            /**
             * Draining
             * @default false
             */
            draining: boolean;
            /** Registered Commands */
            registered_commands: number;
            /**
             * Service
             * @default fx1-harness-api
             */
            service: string;
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Version
             * @default 0.4.0
             */
            version: string;
        };
        /**
         * JobBatchItemResponse
         * @description Per-item outcome — either the submit tuple or the ApiError the
         *     item failed with (``code`` carries the machine-stable class).
         */
        JobBatchItemResponse: {
            /** Code */
            code?: string | null;
            /** Error */
            error?: string | null;
            /** Index */
            index: number;
            /** Job Id */
            job_id?: string | null;
            /** Replayed */
            replayed?: boolean | null;
            /** Status */
            status?: ("queued" | "running" | "succeeded" | "failed" | "cancelled") | null;
        };
        /**
         * JobBatchRequest
         * @description Batch submit envelope — ``min_length``/``max_length`` fail closed:
         *     an empty batch and an over-cap batch are both 422s.
         */
        JobBatchRequest: {
            /** Jobs */
            jobs: components["schemas"]["HarnessRunRequest"][];
        };
        /** JobBatchResponse */
        JobBatchResponse: {
            /** Failed */
            failed: number;
            /** Jobs */
            jobs: components["schemas"]["JobBatchItemResponse"][];
            /** Submitted */
            submitted: number;
        };
        /**
         * JobListResponse
         * @description Job inventory page: ``total`` is the filtered count before paging.
         */
        JobListResponse: {
            /** Jobs */
            jobs: components["schemas"]["JobStatusResponse"][];
            /** Total */
            total: number;
        };
        /**
         * JobStatusResponse
         * @description Live job record; ``result`` appears only once status is terminal.
         */
        JobStatusResponse: {
            /**
             * Callback Attempts
             * @default 0
             */
            callback_attempts: number;
            /** Callback Error */
            callback_error?: string | null;
            /** Callback Status */
            callback_status?: ("delivered" | "failed") | null;
            /** Callback Url */
            callback_url?: string | null;
            /** Created At */
            created_at: number;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: number | null;
            /** Job Id */
            job_id: string;
            result: components["schemas"]["HarnessRunResponse"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        };
        /** JobSubmitResponse */
        JobSubmitResponse: {
            /** Job Id */
            job_id: string;
            /**
             * Replayed
             * @default false
             */
            replayed: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        };
        /**
         * MetricsResponse
         * @description Point-in-time ops snapshot: totals since process start.
         */
        MetricsResponse: {
            /** By Status */
            by_status: {
                [key: string]: number;
            };
            /**
             * Complete
             * @default {}
             */
            complete: {
                [key: string]: components["schemas"]["BackendCompletionStats"];
            };
            /** Draining */
            draining: boolean;
            /** Errors Total */
            errors_total: number;
            /** Inflight */
            inflight: number;
            /** Inflight Watermark */
            inflight_watermark: number;
            /** Max Inflight */
            max_inflight: number;
            /**
             * Rate Limited Total
             * @default 0
             */
            rate_limited_total: number;
            /** Requests Total */
            requests_total: number;
            /** Uptime S */
            uptime_s: number;
        };
        /**
         * ReadyResponse
         * @description Readiness probe payload — only emitted while accepting work.
         */
        ReadyResponse: {
            /** Inflight */
            inflight: number;
            /**
             * Ready
             * @default true
             * @constant
             */
            ready: true;
        };
        /** ReceiptIndexItem */
        ReceiptIndexItem: {
            /** Name */
            name: string;
            /** Sha256 */
            sha256: string;
        };
        /** ReceiptIndexResponse */
        ReceiptIndexResponse: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["ReceiptIndexItem"][];
        };
        /**
         * ReceiptVerifyBatchItem
         * @description One per-item verdict: the same payload the single-verify route
         *     returns, plus the index so callers can map results back.
         */
        ReceiptVerifyBatchItem: {
            /** Digest Convention */
            digest_convention: string | null;
            /** Errors */
            errors: string[];
            /** Index */
            index: number;
            /** Kind */
            kind: string | null;
            /** Path */
            path: string;
            /** Schema Tag */
            schema_tag: string;
            /** Valid */
            valid: boolean;
            /** Verdict */
            verdict: string | null;
            /** Warnings */
            warnings: string[];
        };
        /** ReceiptVerifyBatchRequest */
        ReceiptVerifyBatchRequest: {
            /** Receipts */
            receipts: {
                [key: string]: unknown;
            }[];
        };
        /** ReceiptVerifyBatchResponse */
        ReceiptVerifyBatchResponse: {
            /** Failed */
            failed: number;
            /** Results */
            results: components["schemas"]["ReceiptVerifyBatchItem"][];
            /** Verified */
            verified: number;
        };
        /** ReceiptVerifyRequest */
        ReceiptVerifyRequest: {
            /** Receipt */
            receipt: {
                [key: string]: unknown;
            };
        };
        /** ReceiptVerifyResponse */
        ReceiptVerifyResponse: {
            /** Digest Convention */
            digest_convention: string | null;
            /** Errors */
            errors: string[];
            /** Kind */
            kind: string | null;
            /** Path */
            path: string;
            /** Schema Tag */
            schema_tag: string;
            /** Valid */
            valid: boolean;
            /** Verdict */
            verdict: string | null;
            /** Warnings */
            warnings: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VersionResponse
         * @description Wire-contract + package versions — the client's negotiation payload.
         */
        VersionResponse: {
            /** Api Version */
            api_version: string;
            /** Fx1 Version */
            fx1_version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    backends_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["BackendStatusEntry"];
                    };
                };
            };
        };
    };
    backend_probe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: "hosted_k3" | "local_fx1" | "byok";
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BackendProbeRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackendProbeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_capabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    list_commands: {
        parameters: {
            query?: {
                role?: components["schemas"]["HarnessRole"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HarnessCommandListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_batch: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteBatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteBatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_stream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    completions_list: {
        parameters: {
            query?: {
                limit?: number;
                backend?: ("hosted_k3" | "local_fx1" | "byok") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    completion_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                completion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drain: {
        parameters: {
            query?: {
                wait_s?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gate_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GateCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs: {
        parameters: {
            query?: {
                status?: ("queued" | "running" | "succeeded" | "failed" | "cancelled") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_job: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HarnessRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description URL of the created job's status endpoint. */
                    Location?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSubmitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_jobs_batch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobBatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobBatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_job_events: {
        parameters: {
            query?: {
                timeout_s?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_command: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HarnessRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HarnessRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_metrics: {
        parameters: {
            query?: {
                format?: ("json" | "prom" | "prometheus") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    receipts_index: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptIndexResponse"];
                };
            };
        };
    };
    verify_receipt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceiptVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptVerifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_receipts_batch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceiptVerifyBatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptVerifyBatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    receipt_fetch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sha256: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    /** @description Always `no-store`. */
                    "Cache-Control"?: string;
                    /** @description Always `no-referrer`. */
                    "Referrer-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Wire-contract version; clients gate on it via /harness/version. */
                    "X-Fx1-Api-Version"?: string;
                    /** @description Request id — echoed from the inbound X-Request-ID or minted. */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
