"""Cross-receipt consistency lattice — determinism and staleness audit.

Individual receipts bind inputs to claims; ``verify-receipt`` proves a single
artifact was not tampered with after writing. Neither answers the corpus-level
question: *do two sealed receipts that commit the same inputs agree on the
same claims?* Deterministic pipelines must produce bit-identical claims for
identical input digests — disagreement is evidence of nondeterminism or
post-seal editing, and identical inputs measured under a stale ``code`` map
flag evidence generated by code that no longer exists.

Procedure:

- Harvest every claim-bearing scalar leaf of each receipt (numeric, bool, or
  string values under result/metric/verdict regions), tagged by its JSON path
  and source file. Identity/provenance keys (digests, seals, timestamps,
  schema tags, honesty stamps) are never claims.
- Group claims by ``(inputs_sha256, claim_path)``. A group observed in two or
  more receipts is a consistency edge: all-equal values are ``consistent``,
  near-equal floats are ``numeric_drift`` (platform/version jitter is
  evidence, not identity), and anything else is ``inconsistent`` — the same
  measured quantity differs under identical inputs.
- Receipts with no declared ``inputs_sha256`` cannot enter an edge; they are
  counted as a coverage gap (``n_inputs_unspecified``).
- When the caller supplies ``head_sha``, receipts whose ``code_sha256`` /
  ``git_revision`` fingerprint differs are reported as ``stale_code`` —
  evidence produced by code that is not current.

The output is itself a sealed receipt (``receipt_lattice.v1``) so the lattice
is verifiable by the same contract machinery it polices.
"""

from __future__ import annotations

import json
import math
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from quant_fund.research.fleet_eval import _atomic_write_text
from quant_fund.utils.hashing import canonical_json_bytes, hash_bytes
from quant_fund.utils.receipt import verified_corpus_files
from quant_fund.utils.reproducibility import git_revision

LATTICE_SCHEMA = "receipt_lattice.v1"

# Kinds that attest corpus/process state rather than measured claims — their
# payloads describe the corpus itself (chain position, admission verdicts,
# prior audit verdicts), so grouping them would false-flag legitimate
# advancing stamps, a mix of admit/quarantine decisions, or successive
# lattice runs disagreeing as the corpus evolves.
_META_AUDIT_KINDS = frozenset(
    {
        "corpus_epoch.v1",
        "corpus_proof.v1",
        "epoch_consistency.v1",
        "repo_integrity.v1",
        "receipt_admission.v1",
        "receipt_lattice.v1",
        "receipt_graph.v1",
    }
)

# Subtree roots that carry measured claims. Provenance lives elsewhere.
_CLAIM_REGIONS = (
    "results",
    "claims",
    "findings",
    "metrics",
    "scores",
    "verdicts",
    "verdict",
    "summary",
    "outcome",
    "rows",
    "per_head",
    "per_symbol",
    "cells",
    "lanes",
)

# Path segments that name identity/provenance rather than a measured claim.
_NON_CLAIM_TOKENS = (
    "sha256",
    "digest",
    "seal",
    "hash",
    "signature",
    "commit",
    "generated_at",
    "created_at",
    "timestamp",
    "uuid",
    "run_id",
    "session",
    "schema",
    "kind",
    "data_label",
    "research_only",
    "live_pnl_claim",
    "environment",
    "code_files",
    "receipt",
    "disclaimer",
    "evidence",  # evidence strings describe method, not a measured value
    "version",
)

_FLOAT_DRIFT_RTOL = 1e-9
_FLOAT_DRIFT_ATOL = 1e-12


def _is_claim_path(path: str) -> bool:
    segments = [seg.split("[", 1)[0] for seg in path.split(".")]
    if not segments or not segments[0]:
        return False
    if segments[0] not in _CLAIM_REGIONS:
        return False
    for seg in segments:
        low = seg.lower()
        if not low:
            return False
        if any(tok in low for tok in _NON_CLAIM_TOKENS):
            return False
    return True


def _walk_claims(node: Any, path: str) -> list[tuple[str, Any]]:
    """Harvest scalar leaves under claim regions, keyed by dotted path."""
    out: list[tuple[str, Any]] = []
    if isinstance(node, Mapping):
        for key, val in node.items():
            child = f"{path}.{key}" if path else str(key)
            out.extend(_walk_claims(val, child))
    elif isinstance(node, list):
        for i, val in enumerate(node):
            out.extend(_walk_claims(val, f"{path}[{i}]"))
    else:
        if _is_claim_path(path) and isinstance(node, (int, float, str, bool)):
            out.append((path, node))
    return out


def _inputs_fingerprint(doc: Mapping[str, Any]) -> str | None:
    """Declared input digest; v2 envelopes unwrap to the payload body."""
    body = doc.get("payload")
    inner = body if isinstance(body, Mapping) else doc
    value = inner.get("inputs_sha256")
    if isinstance(value, str) and value:
        return value
    return None


def _dataset_fingerprint(doc: Mapping[str, Any]) -> str | None:
    """Declared dataset-content digest — the cross-lane edge tier.

    ``inputs_sha256`` mixes data with run params, so two lanes measuring the
    same tape almost never share it. ``dataset_sha256`` digests only the
    evaluated content (per-shard stream digests), letting receipts written by
    *different* lanes on the same corpus agree — or provably disagree. Reads
    the convention field at top level or under params/drill/run/data.
    """
    body = doc.get("payload")
    inner = body if isinstance(body, Mapping) else doc
    for holder in (inner, *(inner.get(k) for k in ("params", "drill", "run", "data"))):
        if not isinstance(holder, Mapping):
            continue
        value = holder.get("dataset_sha256")
        if (
            isinstance(value, str)
            and len(value) == 64
            and all(c in "0123456789abcdef" for c in value)
        ):
            return value
    return None


def _code_fingerprint(doc: Mapping[str, Any]) -> str | None:
    """Digest over whatever code identity the receipt claims."""
    body = doc.get("payload")
    inner = body if isinstance(body, Mapping) else doc
    code_map = inner.get("code_sha256") or inner.get("code_files")
    if isinstance(code_map, Mapping) and code_map:
        return hash_bytes(canonical_json_bytes(dict(code_map)))
    rev = inner.get("git_revision") or inner.get("generated_at_commit")
    if isinstance(rev, str) and rev:
        return rev
    return None


def _claim_values_equal(a: Any, b: Any, *, rel_tol: float, abs_tol: float) -> str:
    """'equal' | 'drift' | 'different' for two claim values."""
    if a == b:
        return "equal"
    a_num = isinstance(a, (int, float)) and not isinstance(a, bool)
    b_num = isinstance(b, (int, float)) and not isinstance(b, bool)
    if a_num and b_num:
        fa, fb = float(a), float(b)
        if (
            math.isfinite(fa)
            and math.isfinite(fb)
            and math.isclose(fa, fb, rel_tol=rel_tol, abs_tol=abs_tol)
        ):
            return "drift"
    return "different"


def receipt_lattice(
    receipts_dir: Path | str,
    *,
    head_sha: str | None = None,
    glob: str = "*.json",
    float_rel_tol: float = _FLOAT_DRIFT_RTOL,
    float_abs_tol: float = _FLOAT_DRIFT_ATOL,
    known_inconsistent: Mapping[str, str] | None = None,
) -> dict[str, Any]:
    """Audit an evidence corpus for cross-receipt consistency.

    Returns a ``receipt_lattice.v1`` receipt dict. Fails closed on a missing
    directory; unreadable receipts are recorded and downgrade the verdict to
    at most ``"partially_unreadable"``.

    Receipts are scanned recursively (matching the epoch chain's member
    semantics) minus quarantined subdirs; file identity in groups is the
    POSIX path relative to the corpus root, identical to the basename for
    flat corpora. ``known_inconsistent`` keys use the same relative names.

    ``known_inconsistent`` maps receipt filename -> sha256 of the file's
    bytes. A claim group whose members are *all* pinned with byte-exact
    digests is reported with ``verdict: "inconsistent"`` plus
    ``known: true`` and does not drive the top-level verdict — the
    mechanism for committing deliberate demonstration artifacts. A pin
    whose digest does not match the file on disk applies to nothing, so
    a tampered pinned receipt re-enters the gate.
    """
    root = Path(receipts_dir)
    if not root.is_dir():
        raise ValueError(f"receipts dir {root} does not exist")
    if float_rel_tol <= 0 or float_abs_tol <= 0:
        raise ValueError("drift tolerances must be positive")

    receipt_files = verified_corpus_files(root, pattern=glob)
    digests: dict[str, str] = {}
    errors: list[dict[str, str]] = []
    unspecified: list[str] = []
    dataset_unspecified: list[str] = []
    stale: list[dict[str, str]] = []
    # Retractions: sealed receipt_tombstone.v1 members exclude their
    # target's claims — append-only corpus can't delete, it retracts.
    from quant_fund.research.receipt_tombstone import load_tombstones

    tombs = load_tombstones(root)
    retracted = tombs["active"]
    tombstone_filenames = {t["tombstone"] for t in retracted.values()}
    for bad in tombs["invalid"]:
        errors.append({"file": bad.split(":", 1)[0], "error": bad.split(":", 1)[1]})
    # (tier, fingerprint, claim_path) -> list of (file, value)
    edges: dict[tuple[str, str, str], list[tuple[str, Any]]] = {}

    for path in receipt_files:
        rel = path.relative_to(root).as_posix()
        try:
            raw = path.read_bytes()
            digests[rel] = hash_bytes(raw)
            doc = json.loads(raw)
            if not isinstance(doc, Mapping):
                raise ValueError("receipt root is not an object")
        except (OSError, UnicodeDecodeError, json.JSONDecodeError, ValueError) as exc:
            # Narrowed from `except Exception` (quality ratchet): receipt read/parse
            # faults are IO/JSON plus the explicit shape ValueError above; exotic
            # errors propagate. Recorded, never skipped.
            errors.append({"file": rel, "error": f"{type(exc).__name__}: {exc}"})
            continue

        inputs = _inputs_fingerprint(doc)
        if inputs is None:
            unspecified.append(rel)
        code = _code_fingerprint(doc)
        if head_sha is not None and code is not None and code != head_sha:
            stale.append({"file": rel, "claimed_code": code, "head": head_sha})

        dataset = _dataset_fingerprint(doc)
        if dataset is None:
            dataset_unspecified.append(rel)
        body = doc.get("payload")
        inner = body if isinstance(body, Mapping) else doc
        if inner.get("kind") in _META_AUDIT_KINDS:
            continue
        # Tombstone records carry no measured claims (valid or not — an
        # invalid tombstone is already an error entry); retracted targets
        # contribute none either — partial scopes are honored per claim path.
        if inner.get("kind") == "receipt_tombstone.v1" or rel in tombstone_filenames:
            continue
        tomb_scope = (retracted.get(rel) or {}).get("scope")
        for claim_path, value in _walk_claims(inner, ""):
            if tomb_scope == "all" or (isinstance(tomb_scope, list) and claim_path in tomb_scope):
                continue
            key = (
                "inputs",
                inputs if inputs is not None else f"unspecified:{rel}",
                claim_path,
            )
            edges.setdefault(key, []).append((rel, value))
            if dataset is not None:
                edges.setdefault(("dataset", dataset, claim_path), []).append((rel, value))

    groups: list[dict[str, Any]] = []
    n_consistent = n_drift = n_inconsistent = 0
    n_known_inconsistent = 0
    for (tier, fingerprint, claim_path), seen in sorted(edges.items()):
        if len(seen) < 2:
            continue
        files = sorted({f for f, _ in seen})
        if len(files) < 2:
            continue  # same file repeats the path — not a cross-receipt edge
        pairwise_drift = False
        inconsistent = False
        base_file, base_val = seen[0]
        detail: list[dict[str, Any]] = []
        for f, v in seen[1:]:
            cmp = _claim_values_equal(base_val, v, rel_tol=float_rel_tol, abs_tol=float_abs_tol)
            if cmp == "drift":
                pairwise_drift = True
            elif cmp == "different":
                inconsistent = True
                detail.append(
                    {
                        "claim_path": claim_path,
                        "files": sorted({base_file, f}),
                        "values": [base_val, v],
                    }
                )
        if inconsistent:
            verdict = "inconsistent"
            if known_inconsistent and all(
                known_inconsistent.get(f) == digests.get(f) for f in files
            ):
                n_known_inconsistent += 1
            else:
                n_inconsistent += 1
        elif pairwise_drift:
            verdict = "numeric_drift"
            n_drift += 1
        else:
            verdict = "consistent"
            n_consistent += 1
        group: dict[str, Any] = {
            "tier": tier,
            "fingerprint": fingerprint,
            "claim_path": claim_path,
            "n_receipts": len(files),
            "files": files,
            "verdict": verdict,
        }
        if detail:
            group["disagreements"] = detail[:8]
        if (
            verdict == "inconsistent"
            and known_inconsistent
            and all(known_inconsistent.get(f) == digests.get(f) for f in files)
        ):
            group["known"] = True
        groups.append(group)

    n_singleton_claims = sum(1 for seen in edges.values() if len(seen) == 1)
    if errors:
        verdict = "partially_unreadable"
    elif n_inconsistent:
        verdict = "inconsistent"
    elif n_drift or stale:
        verdict = "drift_or_stale"
    else:
        verdict = "consistent"

    params = {
        "glob": glob,
        "float_rel_tol": float_rel_tol,
        "float_abs_tol": float_abs_tol,
        "head_sha": head_sha,
        "n_known_inconsistent_pins": len(known_inconsistent or {}),
    }
    inputs_sha256 = hash_bytes(canonical_json_bytes({"digests": digests, "params": params}))
    return {
        "kind": LATTICE_SCHEMA,
        "schema": LATTICE_SCHEMA,
        "data_label": "CORPUS",
        "research_only": True,
        "live_pnl_claim": False,
        "generated_at_commit": git_revision(),
        "inputs_sha256": inputs_sha256,
        "params": params,
        "verdict": verdict,
        "n_receipts": len(receipt_files),
        "n_parse_errors": len(errors),
        "parse_errors": errors,
        "file_digests": digests,
        "n_inputs_unspecified": len(unspecified),
        "inputs_unspecified": unspecified,
        "n_dataset_unspecified": len(dataset_unspecified),
        "dataset_unspecified": dataset_unspecified,
        "n_stale_code": len(stale),
        "stale_code": stale,
        "n_claim_groups": len(groups),
        "n_consistent_groups": n_consistent,
        "n_drift_groups": n_drift,
        "n_inconsistent_groups": n_inconsistent,
        "n_known_inconsistent_groups": n_known_inconsistent,
        "n_singleton_claims": n_singleton_claims,
        "n_retracted": len(retracted),
        "retracted": {
            name: {"tombstone": t["tombstone"], "scope": t["scope"]}
            for name, t in sorted(retracted.items())
        },
        "groups": groups,
        "evidence": [
            "cross_receipt_claim_equality",
            "inputs_fingerprint_edges",
            "code_staleness_audit",
        ],
    }


def lattice_contract_errors(payload: Mapping[str, Any]) -> list[str]:
    """Re-derive the accounting invariants of a ``receipt_lattice.v1`` body."""
    errors: list[str] = []
    if payload.get("schema") != LATTICE_SCHEMA and payload.get("kind") != LATTICE_SCHEMA:
        return ["schema"]
    groups = payload.get("groups")
    if not isinstance(groups, list):
        return ["groups_missing"]
    digests = payload.get("file_digests")
    if not isinstance(digests, Mapping):
        errors.append("file_digests")
    elif payload.get("n_receipts") != len(digests):
        errors.append("n_receipts")

    # Every advertised count must equal the length of the list it claims to
    # summarize — an understated count drives `expected_verdict` below.
    for field, list_key in (
        ("n_parse_errors", "parse_errors"),
        ("n_inputs_unspecified", "inputs_unspecified"),
        ("n_dataset_unspecified", "dataset_unspecified"),
        ("n_stale_code", "stale_code"),
    ):
        listing = payload.get(list_key)
        if not isinstance(listing, list):
            errors.append(f"{list_key}_not_list")
        elif payload.get(field) != len(listing):
            errors.append(field)
    retracted = payload.get("retracted")
    if not isinstance(retracted, Mapping):
        errors.append("retracted_not_mapping")
    elif payload.get("n_retracted") != len(retracted):
        errors.append("n_retracted")

    if payload.get("n_claim_groups") != len(groups):
        errors.append("n_claim_groups")
    counts = {"consistent": 0, "numeric_drift": 0, "inconsistent": 0}
    for index, group in enumerate(groups):
        if not isinstance(group, Mapping):
            errors.append(f"groups[{index}]_not_object")
            continue
        tier = group.get("tier")
        if tier not in ("inputs", "dataset"):
            errors.append(f"groups[{index}].tier")
        if not isinstance(group.get("fingerprint"), str) or not group["fingerprint"]:
            errors.append(f"groups[{index}].fingerprint")
        verdict = group.get("verdict")
        if verdict not in counts:
            errors.append(f"groups[{index}].verdict")
            continue
        counts[verdict] += 1
        files = group.get("files")
        if not isinstance(files, list) or len(files) < 2:
            errors.append(f"groups[{index}].files")
        if verdict == "inconsistent":
            disagreements = group.get("disagreements")
            if not isinstance(disagreements, list) or not disagreements:
                errors.append(f"groups[{index}].disagreements")
            else:
                for d in disagreements:
                    dv = d.get("values") if isinstance(d, Mapping) else None
                    if not isinstance(dv, list) or len(dv) < 2 or dv[0] == dv[1]:
                        errors.append(f"groups[{index}].disagreements_not_real")
                        break
    n_known = 0
    for index, group in enumerate(groups):
        if not isinstance(group, Mapping) or group.get("known") is not True:
            continue
        if group.get("verdict") != "inconsistent":
            errors.append(f"groups[{index}].known_not_inconsistent")
        else:
            n_known += 1
    if payload.get("n_known_inconsistent_groups", 0) != n_known:
        errors.append("n_known_inconsistent_groups")
    if payload.get("n_consistent_groups") != counts["consistent"]:
        errors.append("n_consistent_groups")
    if payload.get("n_drift_groups") != counts["numeric_drift"]:
        errors.append("n_drift_groups")
    if payload.get("n_inconsistent_groups") != counts["inconsistent"] - n_known:
        errors.append("n_inconsistent_groups")

    expected_verdict = (
        "partially_unreadable"
        if payload.get("n_parse_errors", 0) > 0
        else "inconsistent"
        if counts["inconsistent"] - n_known > 0
        else "drift_or_stale"
        if counts["numeric_drift"] > 0 or payload.get("n_stale_code", 0) > 0
        else "consistent"
    )
    if payload.get("verdict") != expected_verdict:
        errors.append("verdict")

    params = payload.get("params")
    if isinstance(params, Mapping) and isinstance(digests, Mapping):
        try:
            derived = hash_bytes(
                canonical_json_bytes({"digests": dict(digests), "params": dict(params)})
            )
        except (TypeError, ValueError):
            derived = None
        if derived is not None and payload.get("inputs_sha256") != derived:
            errors.append("inputs_sha256")
    return errors


def write_lattice_receipt(
    receipt: Mapping[str, Any],
    receipts_dir: Path | str = Path("receipts"),
    *,
    receipt_version: int = 1,
) -> Path:
    """Seal a receipt_lattice receipt and write ``receipt_lattice_<hash>.json``.

    Filename digest = canonical ``receipt_sha256``. Atomic, fail-closed on
    a malformed receipt. ``receipt_version=2`` wraps the same body in the
    unified ``receipt.v2`` envelope instead.
    """
    from quant_fund.research.receipt_v2 import seal_receipt, wrap_receipt_v2

    if (
        receipt.get("kind") != LATTICE_SCHEMA
        or receipt.get("schema") != LATTICE_SCHEMA
        or receipt.get("research_only") is not True
        or receipt.get("live_pnl_claim") is not False
        or not isinstance(receipt.get("inputs_sha256"), str)
        or not isinstance(receipt.get("params"), Mapping)
    ):
        raise ValueError("receipt_lattice receipt violates its contract")
    errors = lattice_contract_errors(receipt)
    if errors:
        raise ValueError(f"receipt_lattice receipt violates its contract: {errors}")
    if receipt_version == 1:
        canonical = json.loads(canonical_json_bytes(dict(receipt)))
        digest = hash_bytes(canonical_json_bytes(canonical))
        payload = {**canonical, "receipt_sha256": digest}
    elif receipt_version == 2:
        payload = seal_receipt(
            wrap_receipt_v2(
                receipt,
                code_files=(Path(__file__),),
                verdict="pass" if receipt.get("verdict") == "consistent" else "fail",
            )
        )
        digest = str(payload["receipt_sha256"])
    else:
        raise ValueError(f"receipt_version must be 1 or 2, got {receipt_version!r}")
    path = Path(receipts_dir) / f"receipt_lattice_{digest[:16]}.json"
    _atomic_write_text(path, json.dumps(payload, indent=2, sort_keys=True) + "\n")
    return path
