"""Tests for models/breeden_litzenberger.py — BL RND extraction + moments.

SYNTHETIC: every smile is generated by the in-module lognormal-mixture DGP
(:func:`synthetic_mixture_smile`); no market data. Assertions are correctness
checks — density L1/KL error, moment recovery, mass normalization, arb-screen
fail-closed behavior — never market evidence.

References exercised: Breeden & Litzenberger (1978) J. Business 51(4);
Shimko (1993) RISK 6(4); Aït-Sahalia & Lo (1998) J. Finance 53(2);
Figlewski (2010); Malz (2014) NY Fed Staff Report 677.
"""

from __future__ import annotations

import numpy as np
import pytest

from quant_fund.models.breeden_litzenberger import (
    RNDResult,
    arbitrage_report,
    bench_breeden_litzenberger,
    extract_rnd,
    implied_moments,
    synthetic_mixture_smile,
)

CLEAN = synthetic_mixture_smile(seed=3, noise_std=0.0)
NOISY = synthetic_mixture_smile(seed=11, noise_std=0.004)
NARROW = synthetic_mixture_smile(seed=4, noise_std=0.0, strike_lo_log=-0.5, strike_hi_log=0.45)


def _extract(fx) -> RNDResult:
    return extract_rnd(
        fx.strikes,
        fx.call_prices,
        forward=fx.forward,
        r=fx.r,
        maturity=fx.maturity,
    )


# ---------------------------------------------------------------------------
# density recovery on a known smile
# ---------------------------------------------------------------------------


def test_extract_returns_result_shape() -> None:
    res = _extract(CLEAN)
    assert isinstance(res, RNDResult)
    assert res.strikes.shape == res.density.shape == res.density_raw.shape
    assert res.observed_mask.dtype == bool
    assert np.all(np.diff(res.strikes) > 0.0)


def test_density_recovers_true_clean() -> None:
    res = _extract(CLEAN)
    rep = arbitrage_report(
        res,
        model_density=CLEAN.density_on(res.strikes),
        reference_moments=CLEAN.true_moments,
    )
    assert rep["l1_distance"] < 0.15
    assert rep["kl_divergence"] < 0.5


def test_repaired_density_is_a_density() -> None:
    res = _extract(CLEAN)
    assert (res.density >= 0.0).all()
    assert np.isfinite(res.density).all()
    assert abs(np.trapezoid(res.density, res.strikes) - 1.0) < 1e-9


def test_mass_defect_closed_by_repair() -> None:
    res = _extract(CLEAN)
    assert res.diagnostics["mass_defect_after_repair"] < 1e-9
    # raw extraction over a finite grid carries a nonzero defect
    assert abs(res.diagnostics["mass_defect_raw"]) < 0.05


def test_density_peak_region_matches_true_mode() -> None:
    res = _extract(CLEAN)
    q = CLEAN.density_on(res.strikes)
    mode_hat = res.strikes[np.argmax(res.density[res.observed_mask])]
    mode_true = res.strikes[res.observed_mask][np.argmax(q[res.observed_mask])]
    assert abs(mode_hat - mode_true) / res.forward < 0.15


# ---------------------------------------------------------------------------
# implied moments
# ---------------------------------------------------------------------------


def test_forward_martingale_gap() -> None:
    res = _extract(CLEAN)
    mom = implied_moments(res.strikes, res.density)
    assert abs(mom["mean"] - res.forward) / res.forward < 0.03


def test_variance_recovery() -> None:
    res = _extract(CLEAN)
    mom = implied_moments(res.strikes, res.density)
    rel = abs(mom["variance"] - CLEAN.true_moments["variance"])
    assert rel / CLEAN.true_moments["variance"] < 0.15


def test_skewness_sign_and_size() -> None:
    res = _extract(CLEAN)
    mom = implied_moments(res.strikes, res.density)
    assert mom["skewness"] < 0.0  # crash component gives negative skew
    assert abs(mom["skewness"] - CLEAN.true_moments["skewness"]) < 0.4


def test_excess_kurtosis_recovery() -> None:
    res = _extract(CLEAN)
    mom = implied_moments(res.strikes, res.density)
    assert abs(mom["excess_kurtosis"] - CLEAN.true_moments["excess_kurtosis"]) < 0.8


def test_implied_moments_uniform_analytic() -> None:
    """Uniform density on [a, b] has closed-form moments — exact pin."""
    a, b = 80.0, 120.0
    k = np.linspace(a, b, 801)
    f = np.full_like(k, 1.0 / (b - a))
    mom = implied_moments(k, f)
    assert abs(mom["mean"] - (a + b) / 2.0) < 1e-10
    assert abs(mom["variance"] - (b - a) ** 2 / 12.0) < 1e-2
    assert abs(mom["skewness"]) < 1e-6
    assert abs(mom["excess_kurtosis"] - (-1.2)) < 1e-2


def test_implied_moments_gaussian() -> None:
    """Gaussian on a wide grid: skew ~0, excess kurtosis ~0."""
    mu, sd = 100.0, 12.0
    k = np.linspace(mu - 8 * sd, mu + 8 * sd, 4001)
    f = np.exp(-0.5 * ((k - mu) / sd) ** 2) / (sd * np.sqrt(2 * np.pi))
    mom = implied_moments(k, f)
    assert abs(mom["mean"] - mu) < 1e-8
    assert abs(mom["skewness"]) < 1e-8
    assert abs(mom["excess_kurtosis"]) < 1e-6


@pytest.mark.parametrize(
    "k,f",
    [
        ([50.0, 100.0, 150.0], [0.01, -0.5, 0.01]),  # negative density
        ([50.0, 100.0, 150.0], [0.0, 0.0, 0.0]),  # zero mass
        ([150.0, 100.0, 50.0], [0.01, 0.02, 0.01]),  # unsorted strikes
        ([50.0, 100.0, np.nan], [0.01, 0.02, 0.01]),  # non-finite strikes
    ],
)
def test_implied_moments_fail_closed(k: list[float], f: list[float]) -> None:
    with pytest.raises(ValueError):
        implied_moments(k, f)


# ---------------------------------------------------------------------------
# noise robustness + repair
# ---------------------------------------------------------------------------


def test_noisy_extraction_still_valid_density() -> None:
    res = _extract(NOISY)
    assert (res.density >= 0.0).all()
    assert abs(np.trapezoid(res.density, res.strikes) - 1.0) < 1e-9


def test_noisy_density_error_bounded() -> None:
    res = _extract(NOISY)
    rep = arbitrage_report(res, model_density=NOISY.density_on(res.strikes))
    assert rep["l1_distance"] < 0.8
    assert rep["negative_mass_raw"] < 0.5


def test_smoothing_limits_negative_mass_vs_raw_differences() -> None:
    """Raw second differences on noisy mids should be worse than the pipeline."""
    k = NOISY.strikes
    c = NOISY.call_prices
    d2 = np.empty(k.size - 2)
    for i in range(1, k.size - 1):
        h1, h2 = k[i] - k[i - 1], k[i + 1] - k[i]
        d2[i - 1] = 2.0 * ((c[i + 1] - c[i]) / h2 - (c[i] - c[i - 1]) / h1) / (h1 + h2)
    f_naive = np.exp(NOISY.r * NOISY.maturity) * d2
    res = _extract(NOISY)
    # the unsmoothed estimate violates non-negativity; the pipeline repairs it
    assert (f_naive < 0.0).any()
    assert (res.density >= 0.0).all()


def test_tail_grafting_fills_missing_mass_on_narrow_grid() -> None:
    res = _extract(NARROW)
    # the narrow quote range truncates real mass; tails must carry the deficit
    assert res.diagnostics["mass_defect_raw"] > 0.05
    assert res.diagnostics["tail_mass_grafted"] > 0.0
    assert abs(np.trapezoid(res.density, res.strikes) - 1.0) < 1e-9
    assert (~res.observed_mask).any()
    assert np.isnan(res.density_raw[~res.observed_mask]).all()


def test_observed_mask_covers_input_range() -> None:
    res = _extract(CLEAN)
    obs = res.strikes[res.observed_mask]
    assert obs[0] >= CLEAN.strikes[0] and obs[-1] <= CLEAN.strikes[-1]
    assert np.isfinite(res.density_raw[res.observed_mask]).all()


# ---------------------------------------------------------------------------
# arbitrage report
# ---------------------------------------------------------------------------


def test_arbitrage_report_keys_and_ranges() -> None:
    res = _extract(CLEAN)
    rep = arbitrage_report(res)
    for key in (
        "mass_defect_raw",
        "mass_defect_after_repair",
        "negative_mass_raw",
        "negativity_violation_frac",
        "forward_gap",
        "mean",
        "variance",
        "skewness",
        "excess_kurtosis",
    ):
        assert key in rep
        assert np.isfinite(rep[key])
    assert 0.0 <= rep["negativity_violation_frac"] <= 1.0


def test_report_zero_distance_for_self_density() -> None:
    res = _extract(CLEAN)
    rep = arbitrage_report(res, model_density=res.density.copy())
    assert rep["l1_distance"] < 1e-12
    assert rep["kl_divergence"] < 1e-9


def test_report_moment_consistency_vs_reference() -> None:
    res = _extract(CLEAN)
    rep = arbitrage_report(res, reference_moments=CLEAN.true_moments)
    assert rep["mean_rel_err"] < 0.05
    assert rep["variance_rel_err"] < 0.15
    assert rep["skewness_abs_err"] < 0.5
    assert rep["excess_kurtosis_abs_err"] < 1.0


def test_report_rejects_bad_model_density() -> None:
    res = _extract(CLEAN)
    with pytest.raises(ValueError):
        arbitrage_report(res, model_density=np.ones(7))
    with pytest.raises(ValueError):
        arbitrage_report(res, model_density=np.full(res.strikes.size, -0.1))
    with pytest.raises(ValueError):
        arbitrage_report(res, reference_moments={"mean": 100.0})


# ---------------------------------------------------------------------------
# input validation / fail-closed
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "strikes,calls",
    [
        ([80.0, 90.0, 90.0, 100.0, 110.0], [10.0] * 5),  # duplicate strikes
        ([-5.0, 50.0, 100.0, 150.0, 200.0], [10.0] * 5),  # non-positive strike
        ([80.0, 90.0, 100.0, 110.0], [10.0] * 4),  # too short
        ([80.0, 90.0, 100.0, 110.0, np.inf], [10.0] * 5),  # non-finite strike
        ([80.0, 90.0, 100.0, 110.0, 120.0], [10.0, 10.0, np.nan, 9.0, 8.0]),
    ],
)
def test_extract_rejects_bad_grids(strikes: list[float], calls: list[float]) -> None:
    with pytest.raises(ValueError):
        extract_rnd(strikes, calls, forward=100.0, maturity=0.5)


def test_extract_rejects_arb_violating_prices() -> None:
    k = np.linspace(60.0, 160.0, 15)
    with pytest.raises(ValueError):  # price above e^{-rT} F
        extract_rnd(k, np.full(15, 200.0), forward=100.0, maturity=0.5)
    with pytest.raises(ValueError):  # grossly increasing in strike
        extract_rnd(k, np.linspace(1.0, 30.0, 15), forward=100.0, maturity=0.5)


@pytest.mark.parametrize(
    "kwargs",
    [
        {"forward": 0.0, "maturity": 0.5},
        {"forward": -10.0, "maturity": 0.5},
        {"forward": 100.0, "maturity": 0.0},
        {"forward": 100.0, "maturity": -0.5},
        {"forward": 100.0, "maturity": 0.5, "smoothing": -1.0},
        {"forward": 100.0, "maturity": 0.5, "grid_points": 4},
        {"forward": 100.0, "maturity": 0.5, "tail_points": -1},
        {"forward": 100.0, "maturity": 0.5, "price_tol": 0.0},
    ],
)
def test_extract_rejects_bad_params(kwargs: dict[str, float]) -> None:
    with pytest.raises(ValueError):
        extract_rnd(CLEAN.strikes, CLEAN.call_prices, **kwargs)


def test_extract_sorts_unordered_input() -> None:
    shuffled = np.random.default_rng(0).permutation(CLEAN.strikes.size)
    res_a = _extract(CLEAN)
    res_b = extract_rnd(
        CLEAN.strikes[shuffled],
        CLEAN.call_prices[shuffled],
        forward=CLEAN.forward,
        r=CLEAN.r,
        maturity=CLEAN.maturity,
    )
    np.testing.assert_allclose(res_a.density, res_b.density, atol=1e-12)


# ---------------------------------------------------------------------------
# synthetic fixture internals
# ---------------------------------------------------------------------------


def test_fixture_call_price_matches_payoff_integral() -> None:
    """Closed-form mixture calls must match ∫ (S-K)+ q(S) dS on the fine grid."""
    fx = CLEAN
    payoff = np.trapezoid(
        np.maximum(fx.fine_grid[:, None] - fx.strikes[None, :], 0.0) * fx.true_density[:, None],
        fx.fine_grid,
        axis=0,
    )
    disc = np.exp(-fx.r * fx.maturity)
    model = fx.call_price_on(fx.strikes) / disc
    rel = np.abs(model - payoff) / payoff
    mid = payoff > 1.0  # only compare where the payoff is meaningfully covered
    assert mid.sum() >= 10
    assert (rel[mid] < 0.05).all()


def test_fixture_true_moments_match_density() -> None:
    """Analytic raw-moment identities agree with numerical integration."""
    fx = CLEAN
    mom = implied_moments(fx.fine_grid, fx.true_density)
    assert abs(mom["mean"] - fx.true_moments["mean"]) < 0.5
    assert abs(mom["variance"] - fx.true_moments["variance"]) / fx.true_moments["variance"] < 0.02
    assert abs(mom["skewness"] - fx.true_moments["skewness"]) < 0.05
    assert abs(mom["excess_kurtosis"] - fx.true_moments["excess_kurtosis"]) < 0.2


def test_fixture_martingale_calibration() -> None:
    assert abs(CLEAN.true_moments["mean"] - CLEAN.forward) < 1e-8
    assert CLEAN.true_moments["skewness"] < 0.0


def test_fixture_zero_noise_and_seed_effects() -> None:
    fx = synthetic_mixture_smile(seed=0, noise_std=0.0)
    np.testing.assert_array_equal(fx.call_prices, fx.call_prices_clean)
    fx_a = synthetic_mixture_smile(seed=0, noise_std=0.003)
    fx_b = synthetic_mixture_smile(seed=1, noise_std=0.003)
    assert not np.array_equal(fx_a.call_prices, fx_b.call_prices)


@pytest.mark.parametrize(
    "kwargs",
    [
        {"seed": -1},
        {"n_strikes": 3},
        {"noise_std": -0.1},
        {"forward": 0.0},
        {"maturity": -0.1},
        {"weight": 0.0},
        {"weight": 1.0},
        {"vol1": 0.0},
        {"crash_log_median": 0.2},
        {"strike_lo_log": 0.5, "strike_hi_log": -0.5},
        {"fine_points": 10},
    ],
)
def test_fixture_fail_closed(kwargs: dict[str, float]) -> None:
    with pytest.raises(ValueError):
        synthetic_mixture_smile(**kwargs)  # type: ignore[arg-type]


def test_near_lognormal_limit_positive_skew() -> None:
    """Shrinking the crash component (weight -> 0) approaches a pure
    lognormal, which has *positive* skew — opposite sign of the default."""
    fx = synthetic_mixture_smile(seed=5, noise_std=0.0, weight=0.02)
    assert fx.true_moments["skewness"] > 0.0
    res = _extract(fx)
    mom = implied_moments(res.strikes, res.density)
    assert mom["skewness"] > 0.0


# ---------------------------------------------------------------------------
# determinism + bench
# ---------------------------------------------------------------------------


def test_extraction_deterministic() -> None:
    a = _extract(NOISY)
    b = _extract(NOISY)
    np.testing.assert_array_equal(a.strikes, b.strikes)
    np.testing.assert_array_equal(a.density, b.density)
    np.testing.assert_array_equal(a.density_raw, b.density_raw)
    assert a.diagnostics == b.diagnostics


def test_bench_flat_synthetic_float_dict() -> None:
    out = bench_breeden_litzenberger()
    assert len(out) >= 10
    for key, val in out.items():
        assert key.startswith("synthetic_")
        assert isinstance(val, float)
        assert np.isfinite(val)


def test_bench_deterministic() -> None:
    assert bench_breeden_litzenberger() == bench_breeden_litzenberger()


def test_bench_quality_bounds() -> None:
    out = bench_breeden_litzenberger()
    assert out["synthetic_l1_density_clean"] < 0.2
    assert out["synthetic_mass_defect_after_repair"] < 1e-9
    assert out["synthetic_forward_gap"] < 0.05
    assert out["synthetic_l1_density_noisy"] < 0.8


def test_bench_rejects_bad_seed() -> None:
    with pytest.raises(ValueError):
        bench_breeden_litzenberger(seed=-1)
    with pytest.raises(ValueError):
        bench_breeden_litzenberger(seed=True)
