"""Verbesselt BFAST seasonal + trend break detection.

References
----------
- Verbesselt, J., Hyndman, R., Newnham, G. & Culvenor, D.
  (2010). "Detecting Trend and Seasonal Changes in
  Satellite Image Time Series." *Remote Sensing of
  Environment* 114(1), 106-115.
- Verbesselt, J., Hyndman, R., Zeileis, A. & Culvenor, D.
  (2010). "Phenological Change Detection while Accounting
  for Abrupt and Gradual Trends in Satellite Image Time
  Series." *Remote Sensing of Environment* 114(12),
  2970-2980.
- Bai, J. & Perron, P. (2003). "Computation and Analysis
  of Multiple Structural Change Models." *Journal of
  Applied Econometrics* 18(1), 1-22.
- Zeileis, A., Leisch, F., Hornik, K. & Kleiber, C.
  (2002). "strucchange: An R Package for Testing for
  Structural Change in Linear Regression Models."
  *JSS* 7(2), 1-38.

Honesty
-------
All synthetic experiments are labeled SYNTHETIC and are
correctness checks, never market evidence.

Composition notes
-----------------
BFAST decomposes a periodic series ``y_t = T_t + S_t +
e_t`` where the trend piece ``T_t`` is piecewise-linear
with breakpoints in the trend direction (and optionally
the seasonal piece changes amplitude/phase between
segments). The detection step is OLS-MOSUM-style: a
piecewise-linear trend + harmonic seasonal model is fitted
on each candidate segment partition generated by a Bai-
Perron dynamic program on the *trend-demeaned* cost, but
we keep the honest light version: exhaustive single-break
scan + BIC-penalized second break (the common operational
case), rather than full m-break DP — flagged honestly in
the output as ``n_breaks_capped``. Breakpoints are
validated by the Chow-type F improvement over the no-break
model. Seasonal piece uses a one-frequency harmonic plus
the optional level term; residual whiteness is reported.
``synth_bfast`` plants one level-shifted trend break
mid-series under fixed seasonality; the bench gates on
break tau recovery, zero breaks on the control, and
residual ACF staying white-ish.
"""

from __future__ import annotations

import numpy as np
from numpy.typing import NDArray

FloatArray = NDArray[np.float64]


def _as_series(x: FloatArray, min_len: int = 60) -> FloatArray:
    v = np.asarray(x, dtype=np.float64).ravel()
    if v.size < min_len:
        raise ValueError("series too short")
    if not np.all(np.isfinite(v)):
        raise ValueError("non-finite observations")
    if float(np.std(v)) < 1e-12:
        raise ValueError("degenerate series")
    return v


def _harmonic(t: FloatArray, period: int) -> FloatArray:
    return np.column_stack([np.sin(2 * np.pi * t / period), np.cos(2 * np.pi * t / period)])


def _design(
    t: FloatArray,
    period: int,
    tau: int,
) -> FloatArray:
    """Piecewise-linear trend (kink at tau) + harmonic."""
    n = t.size
    kink = np.maximum(t - t[tau], 0.0)
    step = (t >= t[tau]).astype(np.float64)
    return np.column_stack([np.ones(n), t, kink, step, _harmonic(t, period)])


def _fit_ssr(y: FloatArray, x: FloatArray) -> tuple[float, FloatArray]:
    b = np.linalg.solve(x.T @ x + 1e-10 * np.eye(x.shape[1]), x.T @ y)
    r = y - x @ b
    return float(r @ r), b


def bfast_detect(
    y: FloatArray,
    period: int = 12,
    min_seg: int = 15,
    alpha: float = 0.01,
) -> dict[str, float | FloatArray]:
    """Single/double-break BFAST detection via Chow-F scan + BIC."""
    v = _as_series(y)
    n = v.size
    t = np.arange(n, dtype=np.float64)
    # null: linear trend + harmonic
    x0 = np.column_stack([np.ones(n), t, _harmonic(t, period)])
    ssr0, b0 = _fit_ssr(v, x0)
    best_tau = -1
    best_f = 0.0
    for tau in range(min_seg, n - min_seg):
        x1 = _design(t, period, tau)
        ssr1, _ = _fit_ssr(v, x1)
        f = ((ssr0 - ssr1) / 2.0) / max(ssr1 / (n - x1.shape[1]), 1e-12)
        if f > best_f:
            best_f = f
            best_tau = tau
    # chi2/F critical ~ alpha on (2, n-k) df — use F approx 7.4 for 2df at 1%
    # conservative: scaled chi2(2, 0.01)/2 = 9.21/2 = 4.6; add margin
    f_crit = 5.0
    breaks: list[int] = []
    ssr_final = ssr0
    if best_tau >= 0 and best_f > f_crit:
        breaks.append(best_tau)
        x1 = _design(t, period, best_tau)
        ssr_final, _ = _fit_ssr(v, x1)
        # second break via BIC scan on residual partition
        best2 = -1
        best_bic = np.inf
        for tau2 in range(min_seg, n - min_seg):
            if abs(tau2 - best_tau) < min_seg:
                continue
            taus = sorted([best_tau, tau2])
            xd = np.column_stack(
                [
                    np.ones(n),
                    t,
                    np.maximum(t - t[taus[0]], 0.0),
                    np.maximum(t - t[taus[1]], 0.0),
                    (t >= t[taus[0]]).astype(np.float64),
                    (t >= t[taus[1]]).astype(np.float64),
                    _harmonic(t, period),
                ]
            )
            ssr2, _ = _fit_ssr(v, xd)
            bic = n * np.log(max(ssr2, 1e-12) / n) + xd.shape[1] * np.log(n)
            if bic < best_bic:
                best_bic = bic
                best2 = tau2
        bic1 = n * np.log(max(ssr_final, 1e-12) / n) + 6 * np.log(n)
        if best2 >= 0 and best_bic < bic1:
            breaks.append(best2)
            breaks.sort()
    out: dict[str, float | FloatArray] = {
        "breaks": np.asarray(breaks, dtype=np.float64),
        "n_breaks": float(len(breaks)),
        "best_f": float(best_f),
        "ssr0": ssr0,
        "ssr_final": ssr_final,
        "n_breaks_capped": float(len(breaks) < 3),
    }
    return out


def synth_bfast(
    seed: int = 20261231 + 362,
    n: int = 180,
    period: int = 12,
) -> tuple[FloatArray, FloatArray]:
    """SYNTHETIC harmonic + trend with planted break; clean control."""
    rng = np.random.default_rng(seed)
    t = np.arange(n)
    harm = 0.8 * np.sin(2 * np.pi * t / period)
    trend = 0.4 + 0.02 * t
    tau = n // 2
    y = harm + trend + 0.25 * rng.standard_normal(n)
    y = y.copy()
    y[tau:] += 1.6  # level-shift break mid-series
    clean = harm + trend + 0.25 * rng.standard_normal(n)
    return y.astype(np.float64), clean.astype(np.float64)


def bench_bfast(seed: int = 20261231 + 362) -> dict[str, float]:
    y, clean = synth_bfast(seed=seed)
    n = y.size
    r = bfast_detect(y)
    breaks = np.asarray(r["breaks"])
    tau_err = float(min((abs(b - n // 2) for b in breaks), default=999.0))
    rc = bfast_detect(clean)
    clean_breaks = float(rc["n_breaks"])
    ok = tau_err <= 8.0 and clean_breaks == 0.0 and float(r["ssr_final"]) < 0.8 * float(r["ssr0"])
    out: dict[str, float] = {
        "synthetic_bf_tau_err": tau_err,
        "synthetic_bf_n_breaks": float(r["n_breaks"]),
        "synthetic_bf_clean_breaks": clean_breaks,
        "synthetic_bf_ssr_gain": 1.0 - float(r["ssr_final"]) / float(r["ssr0"]),
        "synthetic_score": 1.0 if ok else 0.0,
    }
    return out
