"""Finite colimits in FinSet: coproducts, coequalizers, pushouts (SYNTHETIC)."""

from __future__ import annotations


def coproduct(a: int, b: int) -> tuple[int, tuple[int, ...], tuple[int, ...]]:
    """A+B disjoint union: i1(x)=x, i2(y)=a+y."""
    return a + b, tuple(range(a)), tuple(range(a, a + b))


def copair(f: tuple[int, ...], g: tuple[int, ...], a: int) -> tuple[int, ...]:
    """[f,g]: A+B -> C induced by f:A->C, g:B->C."""
    return tuple(f) + tuple(g)


def coequalizer(f: tuple[int, ...], g: tuple[int, ...], b: int) -> tuple[int, tuple[int, ...]]:
    """Quotient of B by ~ generated by f(x)~g(x); returns (n_classes, quotient map)."""
    parent = list(range(b))

    def find(x: int) -> int:
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    for x in range(len(f)):
        rx, ry = find(f[x]), find(g[x])
        if rx != ry:
            parent[rx] = ry
    roots: dict[int, int] = {}
    q = []
    for y in range(b):
        r = find(y)
        if r not in roots:
            roots[r] = len(roots)
        q.append(roots[r])
    return len(roots), tuple(q)


def pushout(f: tuple[int, ...], g: tuple[int, ...], b: int, c: int) -> int:
    """Pushout of f:A->B, g:A->C = (B+C)/~ with f(x)~g(x): coequalizer of copair."""
    f_map = tuple(f)
    g_map = tuple(b + x for x in g)
    # elements of A index two maps into B+C: u(x)=f(x), v(x)=b+g(x)
    parent = list(range(b + c))

    def find(x: int) -> int:
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    for x in range(len(f_map)):
        rx, ry = find(f_map[x]), find(g_map[x])
        if rx != ry:
            parent[rx] = ry
    return len({find(i) for i in range(b + c)})


def _bench_cat_colimit(seed: int = 0) -> float:
    checks = []
    n, i1, i2 = coproduct(2, 3)
    checks.append(n == 5 and i1 == (0, 1) and i2 == (2, 3, 4))
    # copair universal property: [f,g]∘i1 = f, [f,g]∘i2 = g
    f = (0, 1)
    g = (1, 0, 1)
    cp = copair(f, g, 2)
    checks.append(tuple(cp[i1[x]] for x in range(2)) == f)
    checks.append(tuple(cp[i2[y]] for y in range(3)) == g)
    # coequalizer of f=(0,0) g=(0,1) on B=2 -> 1 class
    nc, q = coequalizer((0, 0), (0, 1), 2)
    checks.append(nc == 1)
    nc2, _ = coequalizer((0, 1), (0, 2), 3)
    checks.append(nc2 == 2)  # 0~1, 0~2 => all merge? f(0)=0~g(0)=2, f(1)=1~g(1)=... check
    # pushout of f:{pt}->B f(0)=0, g:{pt}->C g(0)=1 -> B+C with 0~b+1
    n3 = pushout((0,), (1,), 2, 2)
    checks.append(n3 == 3)
    return sum(checks) / len(checks)


def bench_cat_colimit(seed: int = 0) -> dict[str, float]:
    return {"synthetic_cat_colimit": _bench_cat_colimit(seed)}
