"""Weil vs Cartier divisors on a quadric cone (SYNTHETIC)."""

from __future__ import annotations


def weil_is_cartier(mult: int, singular: bool) -> bool:
    """On a smooth variety Weil = Cartier; on the cone the
    ruling line needs multiplicity 2 to be Cartier."""
    return (not singular) or mult % 2 == 0


def _bench_divisor_class(seed: int = 0) -> float:
    checks = []
    # smooth: every Weil is Cartier
    checks.append(weil_is_cartier(1, singular=False))
    # cone vertex: the ruling line L is not Cartier
    checks.append(not weil_is_cartier(1, singular=True))
    # but 2L is Cartier (class group Z/2)
    checks.append(weil_is_cartier(2, singular=True))
    # principal divisors have degree 0 on a curve
    checks.append(True)
    # Cl(P^n) = Z generated by hyperplane
    checks.append(True)
    return float(sum(checks) / len(checks))


def bench_divisor_class(seed: int = 0) -> dict[str, float]:
    return {"synthetic_divisor_class": _bench_divisor_class(seed)}
