"""Group presentations: word normal form + order from presentation (SYNTHETIC)."""

from __future__ import annotations


def eval_word(word: list[int], gens: list, mul, ident):
    cur = ident
    for g in word:
        cur = mul(cur, gens[g])
    return cur


def group_from_present(gens: list, mul, ident, max_elts: int = 100) -> frozenset:
    """Enumerate group generated by gens under mul (BFS closure)."""
    elems = {ident}
    frontier = [ident]
    while frontier and len(elems) < max_elts:
        nxt = []
        for x in frontier:
            for g in gens:
                y = mul(x, g)
                if y not in elems:
                    elems.add(y)
                    nxt.append(y)
        frontier = nxt
    return frozenset(elems)


def cyclic_present(n: int) -> tuple[list, object, object]:
    """Z_n via generator a=1 mod n."""

    def mul(a, b):
        return (a + b) % n

    return [1], mul, 0


def _bench_group_presentation(seed: int = 0) -> float:
    checks = []
    gens, mul, ident = cyclic_present(4)
    g = group_from_present(gens, mul, ident)
    checks.append(g == frozenset({0, 1, 2, 3}))
    checks.append(eval_word([0, 0, 0], gens, mul, ident) == 3)
    # Klein four: gens a=(1,0), b=(0,1) under mod-2 add
    gens2 = [(1, 0), (0, 1)]

    def mul2(x, y):
        return ((x[0] + y[0]) % 2, (x[1] + y[1]) % 2)

    g2 = group_from_present(gens2, mul2, (0, 0))
    checks.append(len(g2) == 4)
    checks.append(eval_word([0, 1, 0], gens2, mul2, (0, 0)) == (0, 1))
    # S3 via r=(1,2,0) f=(1,0,2): closure = 6
    r = (1, 2, 0)
    f = (1, 0, 2)

    def mul3(p, q):
        return tuple(p[q[i]] for i in range(3))

    g3 = group_from_present([r, f], mul3, (0, 1, 2))
    checks.append(len(g3) == 6)
    return float(sum(checks) / len(checks))


def bench_group_presentation(seed: int = 0) -> dict[str, float]:
    return {"synthetic_group_presentation": _bench_group_presentation(seed)}
