"""Corsi HAR realized-volatility model (SYNTHETIC).

The heterogeneous autoregression forecasts h-step-ahead
realized variance from daily, weekly, and monthly RV
aggregates — a parsimonious cascade that reproduces
volatility long memory without fractionally integrated
parameters. Additive jumps (HAR-J) and semi-variance
splits (HAR-RSV) fit in the same design.

All estimators fail closed (ValueError) on degenerate input.

Honesty: synthetic benches measure cascade recovery on
generated RV paths — never market evidence.

References:
- Corsi, F. (2009). A simple approximate long-memory model of
  realized volatility. *Journal of Financial Econometrics* 7,
  174-196 — HAR cascade (daily/weekly/monthly components),
  h-step forecast by iterated aggregation. arXiv:
  https://arxiv.org/abs/0903.2919
- Andersen, T. G., Bollerslev, T., Diebold, F. X. (2007).
  Roughing it up: including jump components in the measurement,
  modeling, and forecasting of return volatility.
  *Review of Economics and Statistics* 89.
- Barndorff-Nielsen, O. E., Kinnebrock, S., Shephard, N. (2010).
  Measuring downside risk — realised semivariance. In
  *Volatility and Time Series Econometrics*.
- Corsi, F., Audrino, F., Renò, R. (2012). HAR modeling for
  realized volatility forecasting. In *Handbook of Volatility
  Models and Their Applications* — LHAR robustification.

Composition: pure numpy — OLS on aggregated blocks, rolling
h-step evaluation; deterministic ``np.random.default_rng``;
no new dependencies.
"""

from __future__ import annotations

import numpy as np
from numpy.typing import NDArray

FloatArray = NDArray[np.float64]


def _components(rv: FloatArray, lags: tuple[int, ...]) -> FloatArray:
    """HAR regressors: X[:,j] = mean of previous lags[j] RVs."""
    t = rv.size
    m = max(lags)
    x = np.zeros((t, len(lags)))
    cs = np.concatenate([[0.0], np.cumsum(rv)])
    # comp_{t,j} = mean(rv_{t-lag:t-1}) — strictly lagged
    for j, lag in enumerate(lags):
        idx = np.arange(t)
        lo = np.clip(idx - lag, 0, None)
        x[:, j] = (cs[idx] - cs[lo]) / lag
        x[:m, j] = np.nan  # warmup
    return x


def har_rv_fit(
    rv: FloatArray,
    lags: tuple[int, ...] = (1, 5, 22),
    h: int = 1,
) -> dict[str, float]:
    """OLS fit of RV_{t+h−1} on daily/weekly/monthly aggregates.

    Returns cascade coefficients, R², and residual σ."""
    r = np.asarray(rv, dtype=np.float64).ravel()
    t = r.size
    if t < 200:
        raise ValueError("T>=200")
    if not np.all(np.isfinite(r)) or np.any(r <= 0):
        raise ValueError("positive finite RV required")
    if not (1 <= h <= 22):
        raise ValueError("h in 1..22")
    m = max(lags)

    # h-step-ahead RV = mean of next h RVs
    cs = np.concatenate([[0.0], np.cumsum(r)])
    idx = np.arange(t - h + 1)
    y = np.full(t, np.nan)
    y[idx] = (cs[idx + h] - cs[idx]) / h
    x = _components(r, lags)
    keep = np.arange(m, t - h)
    if keep.size < 100:
        raise ValueError("too few usable obs")
    xk = np.column_stack([np.ones(keep.size), x[keep]])
    yk = y[keep]

    beta, *_ = np.linalg.lstsq(xk, yk, rcond=None)
    fitv = xk @ beta
    resid = yk - fitv
    r2 = 1 - float(np.sum(resid**2)) / float(np.sum((yk - yk.mean()) ** 2))
    sigma2 = float(np.sum(resid**2) / (keep.size - xk.shape[1]))

    # per-component partial contribution
    contrib = []
    for j in range(xk.shape[1] - 1):
        drop = np.delete(xk, j + 1, axis=1)
        b2, *_ = np.linalg.lstsq(drop, yk, rcond=None)
        r2j = 1 - float(np.sum((yk - drop @ b2) ** 2)) / float(np.sum((yk - yk.mean()) ** 2))
        contrib.append(r2 - r2j)

    return {
        "t": float(keep.size),
        "h": float(h),
        "intercept": float(beta[0]),
        "beta_day": float(beta[1]),
        "beta_week": float(beta[2]) if len(lags) > 1 else 0.0,
        "beta_month": float(beta[3]) if len(lags) > 2 else 0.0,
        "r2": r2,
        "resid_sigma": float(np.sqrt(max(sigma2, 1e-300))),
        "contrib_day": float(contrib[0]),
        "contrib_week": float(contrib[1]) if len(lags) > 1 else 0.0,
        "contrib_month": float(contrib[2]) if len(lags) > 2 else 0.0,
    }


def synth_har(
    t: int = 900,
    beta: tuple[float, float, float] = (0.3, 0.4, 0.2),
    lags: tuple[int, ...] = (1, 5, 22),
    sigma: float = 0.25,
    seed: int = 0,
) -> FloatArray:
    """RV generated by a HAR cascade: rv_t = c + Σ β_j·rv̄_j,t−1
    + lognormal innovation. Returns positive rv path."""
    rng = np.random.default_rng(seed)
    r = np.full(t, 1.0)
    m = max(lags)
    for i in range(m, t):
        for j, lag in enumerate(lags):
            r[i] += beta[j] * float(np.mean(r[i - lag : i]))
        r[i] = max(r[i] * np.exp(sigma * rng.normal() - sigma**2 / 2), 1e-4)
    return r


def bench_har_rv(seed: int = 20261231 + 240) -> dict[str, float]:
    """HAR cascade self-check: β_day/week/month recovered near the
    simulated (0.3, 0.4, 0.2) with R² high; the same model on a
    pure-noise RV path gets R² ≈ 0. All ``synthetic_*``."""
    rv = synth_har(beta=(0.3, 0.4, 0.2), seed=seed)
    out = har_rv_fit(rv, h=1)
    rng = np.random.default_rng(seed + 1)
    flat = np.exp(rng.normal(0.0, 0.2, 900))
    out_f = har_rv_fit(flat, h=1)
    out_b = har_rv_fit(rv, h=1)
    out_h5 = har_rv_fit(rv, h=5)

    bd = float(out["beta_day"])
    return {
        "synthetic_beta_day": bd,
        "synthetic_beta_week": float(out["beta_week"]),
        "synthetic_beta_month": float(out["beta_month"]),
        "synthetic_r2": float(out["r2"]),
        "synthetic_r2_flat": float(out_f["r2"]),
        "synthetic_r2_h5": float(out_h5["r2"]),
        "synthetic_contrib_week": float(out["contrib_week"]),
        "synthetic_detects": float(
            abs(bd - 0.3) < 0.15
            and 0.1 < float(out["beta_week"]) < 0.65
            and 0.0 < float(out["beta_month"]) < 0.45
            and float(out["r2"]) > 0.35
            and float(out_f["r2"]) < 0.1
            and float(out["contrib_week"]) > 0.001
        ),
        "synthetic_determinism": float(bd == float(out_b["beta_day"])),
    }
