"""Higher inductive types: quotient and propositional truncation (SYNTHETIC).

Quotient A/R: elements collapse into equivalence classes — paths
generated by R become definitional equalities. Truncation ||A||: all
elements identified (a mere proposition). Both modeled as canonical
representatives on finite carriers.
"""

from __future__ import annotations

_SEED = 20261231 + 1058


def quotient(carrier: list, rel: list[tuple]) -> dict:
    """Map each element to its equivalence-class representative under
    the generated equivalence closure of rel."""
    parent = {x: x for x in carrier}

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    for a, b in rel:
        ra, rb = find(a), find(b)
        parent[ra] = rb
    return {x: find(x) for x in carrier}


def quotient_eq(q: dict, a, b) -> bool:
    """a ~ b in the quotient iff same representative — this is the HIT's
    path relation made definitional."""
    return q.get(a) == q.get(b)


def truncate(carrier: list) -> dict:
    """||A||: everything maps to a single class (if inhabited)."""
    if not carrier:
        return {}
    rep = carrier[0]
    return {x: rep for x in carrier}


def is_prop_truncated(t: dict) -> bool:
    """A truncated type is a mere proposition: at most one class."""
    return len(set(t.values())) <= 1


def bench_hit_quotient(seed: int = _SEED) -> dict[str, float]:
    del seed
    checks: list[bool] = []
    # Z mod 2 on {0..5}: classes evens/odds
    rel = [(0, 2), (2, 4), (1, 3), (3, 5)]
    q = quotient([0, 1, 2, 3, 4, 5], rel)
    checks.append(quotient_eq(q, 0, 4) and quotient_eq(q, 1, 5))
    checks.append(not quotient_eq(q, 0, 1))
    # quotient of a set by non-trivial rel: exactly 2 classes
    checks.append(len(set(q.values())) == 2)
    # truncation: all elements one class
    t = truncate([1, 2, 3])
    checks.append(is_prop_truncated(t) and quotient_eq(t, 1, 3))
    # empty truncation: no classes, still a proposition
    checks.append(is_prop_truncated(truncate([])))
    # reflexive quotient keeps classes
    q2 = quotient([0, 1, 2], [(0, 0)])
    checks.append(len(set(q2.values())) == 3)
    return {"synthetic_hit_quotient": float(sum(checks)) / len(checks)}
