"""Hyena implicit long convolution (Poli et al. 2023).

Filter generated by a learned positional MLP, applied via FFT, then
gated elementwise by the input — an O(T log T) long-range operator.
Content gating gives partial lookup ability vs the stateless S4 on
associative recall.
"""

from __future__ import annotations

import numpy as np
from numpy.typing import NDArray

from quant_fund.models._attn_synth import synth_retrieval

FloatArray = NDArray[np.float64]
_SEED = 20261231


def _torch():
    try:
        import torch

        return torch
    except ImportError as exc:
        raise ImportError("hyena_conv needs the torch `nn` extra") from exc


def bench_hyena_conv(
    seed: int = 7,
    n_train: int = 800,
    n_test: int = 240,
    m_pairs: int = 48,
    n_classes: int = 4,
    iters: int = 700,
    d_model: int = 48,
) -> dict[str, float]:
    torch = _torch()
    rng = np.random.default_rng(seed + _SEED)
    xtr, ytr = synth_retrieval(n_train, m_pairs, n_classes, rng)
    xte, yte = synth_retrieval(n_test, m_pairs, n_classes, rng)
    t, d_in = xtr.shape[1], xtr.shape[2]

    proj = torch.nn.Linear(d_in, d_model)
    filt = torch.nn.Sequential(
        torch.nn.Linear(1, 32), torch.nn.ReLU(), torch.nn.Linear(32, d_model)
    )
    gate = torch.nn.Linear(d_model, d_model)
    out = torch.nn.Linear(d_model, n_classes)
    params = (
        list(proj.parameters())
        + list(filt.parameters())
        + list(gate.parameters())
        + list(out.parameters())
    )

    proj_o = torch.nn.Linear(d_in, d_model)
    out_o = torch.nn.Linear(d_model, n_classes)
    opt = torch.optim.Adam(params, lr=3e-3)
    opt_o = torch.optim.Adam(list(proj_o.parameters()) + list(out_o.parameters()), lr=3e-3)
    pos = torch.linspace(0, 1, t)[:, None]

    def hyena(xb):
        h = proj(xb)
        k = filt(pos).T
        hx = torch.fft.rfft(h.transpose(1, 2), n=2 * t)
        hk = torch.fft.rfft(k, n=2 * t)
        conv = torch.fft.irfft(hx * hk, n=2 * t)[:, :, :t].transpose(1, 2)
        return h * torch.sigmoid(gate(h)) * conv

    def full_attn(xb):
        h = proj_o(xb)
        return torch.softmax(h @ h.transpose(1, 2) / np.sqrt(d_model), -1) @ h

    xt, yt = torch.tensor(xtr).float(), torch.tensor(ytr)
    for _i in range(iters):
        loss = torch.nn.functional.cross_entropy(
            out(hyena(xt)[:, -1]), yt
        ) + torch.nn.functional.cross_entropy(out_o(full_attn(xt)[:, -1]), yt)
        opt.zero_grad()
        opt_o.zero_grad()
        loss.backward()
        opt.step()
        opt_o.step()
    xe = torch.tensor(xte).float()
    with torch.no_grad():
        acc = float((out(hyena(xe)[:, -1]).argmax(-1) == torch.tensor(yte)).float().mean())
        acc_full = float(
            (out_o(full_attn(xe)[:, -1]).argmax(-1) == torch.tensor(yte)).float().mean()
        )
    import math

    return {
        "synthetic_hyena_acc": acc,
        "synthetic_hyena_full_acc": acc_full,
        "synthetic_hyena_acc_gap": acc_full - acc,
        "synthetic_hyena_cost_ratio": float(t * math.log2(t) * d_model) / float(t * t * d_model),
        "torch_available": 1.0,
    }
