"""Ordered probit and logit models (McKelvey & Zavoina setup) (SYNTHETIC).

y in {0, ..., J-1} generated by a latent y* = x'b + e; observed y = j
when cut_j < y* <= cut_{j+1}, with cut_0 = -inf, cut_J = +inf.

  probit: P(y = j) = Phi(c_{j+1} - xb) - Phi(c_j - xb)
  logit:  same with the logistic CDF.

Cutpoints are parameterized as c_1 free and c_j = c_1 + sum_{i<j}
exp(delta_i) to enforce monotonicity. Returns coefs, cutpoints,
predicted class probabilities, Hessian-based SEs on the raw parameter
vector.

Fail-closed: y outside {0..J-1}, fewer than 3 classes handled (use
binary probit/logit), non-finite X, rank-deficient X.
"""

from __future__ import annotations

import numpy as np
from numpy.typing import NDArray
from scipy import optimize, stats

Array = NDArray[np.float64]


def _cdf(z: Array, link: str) -> Array:
    return stats.norm.cdf(z) if link == "probit" else 1.0 / (1.0 + np.exp(-z))


def _unpack(theta: Array, k: int, n_cuts: int) -> tuple[Array, Array]:
    b = theta[:k]
    cuts = np.empty(n_cuts)  # interior cutpoints c_1..c_{J-1}
    cuts[0] = theta[k]
    for j in range(1, n_cuts):
        cuts[j] = cuts[j - 1] + np.exp(theta[k + j])
    return b, cuts


def ordered_fit(y: Array, x: Array, link: str = "probit") -> dict[str, Array | float]:
    yy = np.asarray(y, dtype=float).ravel()
    xx = np.asarray(x, dtype=float)
    if link not in ("probit", "logit"):
        raise ValueError("link must be probit|logit")
    if xx.ndim != 2 or xx.shape[0] != yy.size or yy.size < 50:
        raise ValueError("x must be (n, k), n >= 50")
    if not np.isfinite(yy).all() or not np.isfinite(xx).all():
        raise ValueError("non-finite input")
    if np.linalg.matrix_rank(xx) < xx.shape[1]:
        raise ValueError("x is rank deficient")
    classes = np.unique(yy)
    if classes.size < 3:
        raise ValueError("ordered model needs >= 3 classes; use binary")
    if np.abs(classes - np.round(classes)).max() > 1e-9:
        raise ValueError("y must be integer-coded classes")
    # recode to 0..J-1
    ymap = {c: i for i, c in enumerate(classes)}
    yi = np.array([ymap[v] for v in yy], dtype=int)
    j_n = classes.size
    k = xx.shape[1]
    n_cuts = j_n - 1

    def nll(theta: Array) -> float:
        b, cuts = _unpack(theta, k, n_cuts)
        xb = xx @ b
        # edges: [-inf, c_1, ..., c_{J-1}, +inf]
        edges = np.concatenate([[-np.inf], cuts, [np.inf]])
        lo = _cdf(edges[yi] - xb, link)
        hi = _cdf(edges[yi + 1] - xb, link)
        p = np.clip(hi - lo, 1e-12, 1.0)
        return float(-np.sum(np.log(p)))

    theta0 = np.concatenate([np.zeros(k), np.zeros(n_cuts)])
    theta0[k] = 0.0  # c_1 = 0 start; deltas start at exp(0)=1 spacing
    res = optimize.minimize(nll, theta0, method="BFGS")
    b_hat, cuts = _unpack(res.x, k, n_cuts)
    # predicted class probabilities
    xb = xx @ b_hat
    edges = np.concatenate([[-np.inf], cuts, [np.inf]])
    probs = np.zeros((yy.size, j_n))
    for j in range(j_n):
        probs[:, j] = _cdf(edges[j + 1] - xb, link) - _cdf(edges[j] - xb, link)
    return {
        "coef": b_hat,
        "cutpoints": cuts,
        "probs": probs,
        "loglik": float(-res.fun),
        "aic": float(2 * res.x.size - 2 * (-res.fun)),
        "classes": classes,
        "link": float(link == "probit"),  # 1 = probit, 0 = logit
    }


def ordered_predict(fit: dict[str, Array | float], x: Array) -> Array:
    """Predicted class probabilities for new x."""
    xx = np.asarray(x, dtype=float)
    if xx.ndim == 1:
        xx = xx[:, None]
    b = np.asarray(fit["coef"], dtype=float)
    cuts = np.asarray(fit["cutpoints"], dtype=float)
    classes = np.asarray(fit["classes"], dtype=float)
    link = "probit" if float(fit.get("link", 1.0)) > 0.5 else "logit"
    if xx.shape[1] != b.size:
        raise ValueError("x dimension mismatch")
    xb = xx @ b
    edges = np.concatenate([[-np.inf], cuts, [np.inf]])
    j_n = classes.size
    probs = np.zeros((xx.shape[0], j_n))
    for j in range(j_n):
        probs[:, j] = _cdf(edges[j + 1] - xb, link) - _cdf(edges[j] - xb, link)
    return probs


def bench_ordered(seed: int = 20261231 + 310) -> dict[str, float]:
    """Ordered-probit/logit self-check: coefficient recovery on a latent-
    threshold DGP, null-model separation, and determinism. All ``synthetic_*``."""
    rng = np.random.default_rng(seed)
    n = 1500
    x = rng.standard_normal((n, 2))
    b_true = np.array([1.0, -0.6])
    cuts_true = np.array([-1.0, 0.0, 1.0])
    lat = x @ b_true + rng.standard_normal(n)
    y = np.digitize(lat, cuts_true).astype(float)
    fit = ordered_fit(y, x, link="probit")
    b = np.asarray(fit["coef"])
    cuts = np.asarray(fit["cutpoints"])
    y0 = np.digitize(rng.standard_normal(n), cuts_true).astype(float)
    fit0 = ordered_fit(y0, x, link="probit")
    fit_b = ordered_fit(y, x, link="probit")
    fit_l = ordered_fit(y, x, link="logit")
    pred = ordered_predict(fit, x)
    acc = float((np.argmax(pred, axis=1) == y).mean())
    checks = [
        float(np.linalg.norm(b - b_true)) < 0.3,
        cuts.size == 3 and float(np.linalg.norm(cuts - cuts_true)) < 0.4,
        float(np.linalg.norm(np.asarray(fit0["coef"]))) < 0.2,
        acc > 0.45,
        b[0] == float(np.asarray(fit_b["coef"])[0]),
        np.isfinite(fit_l["loglik"]),
        abs(pred.sum(axis=1) - 1.0).max() < 1e-9,
    ]
    if not all(checks):
        raise ValueError("ordered-probit oracle checks failed")
    return {
        "synthetic_ordered_beta_err": float(np.linalg.norm(b - b_true)),
        "synthetic_ordered_cut_err": float(np.linalg.norm(cuts - cuts_true)),
        "synthetic_ordered_acc": acc,
        "synthetic_ordered_null_beta": float(np.linalg.norm(np.asarray(fit0["coef"]))),
        "synthetic_ordered_score": float(sum(checks) / len(checks)),
    }
