"""Ideals in Z and finite rings: membership, generation, quotient-size (SYNTHETIC)."""

from __future__ import annotations


def ideal_in_zn(n: int, gen: frozenset[int]) -> frozenset[int]:
    """Ideal generated by elements of Z/nZ."""
    import math

    if not gen:
        return frozenset({0})
    d = 0
    for g in gen:
        d = math.gcd(d, g)
    d = math.gcd(d, n)
    return frozenset((d * k) % n for k in range(n))


def is_ideal_zn(n: int, s: frozenset[int]) -> bool:
    """Subgroup closed under multiplication by whole ring."""
    for a in s:
        for b in s:
            if (a + b) % n not in s:
                return False
    for a in s:
        for r in range(n):
            if (r * a) % n not in s:
                return False
    return bool(s)


def _bench_ring_ideals(seed: int = 0) -> float:
    checks = []
    checks.append(ideal_in_zn(6, frozenset({2})) == frozenset({0, 2, 4}))
    checks.append(ideal_in_zn(6, frozenset({2, 3})) == frozenset({0, 1, 2, 3, 4, 5}))
    checks.append(ideal_in_zn(12, frozenset({4, 6})) == frozenset({0, 2, 4, 6, 8, 10}))
    checks.append(is_ideal_zn(6, frozenset({0, 3})))
    checks.append(not is_ideal_zn(6, frozenset({0, 2})))
    checks.append(not is_ideal_zn(6, frozenset({0, 1})))
    return float(sum(checks) / len(checks))


def bench_ring_ideals(seed: int = 0) -> dict[str, float]:
    return {"synthetic_ring_ideals": _bench_ring_ideals(seed)}
