"""Steane [[7,1,3]] CSS code over the Hamming [7,4,3] / simplex [7,3,4] pair (SYNTHETIC).

|0_L> = (1/sqrt8) sum_{c in C^perp} |c> where C^perp is the [7,3,4] simplex
code generated by the rows of the Hamming parity-check matrix H (3x7, all
nonzero columns). C = ker H is the [7,4,3] Hamming code, C^perp subset C.

Coherent decoder on a 13-qubit register (7 data + 6 ancilla):
  1. extract bit-flip syndrome a1 = H*x into ancilla, X-correct data at the
     column position, leaving the syndrome in the ancilla (traced out);
  2. Hadamard-conjugate the data so phase errors become bit errors;
  3. extract phase syndrome a2 = H*x~ and correct; Hadamard back.
Verified by reduced-density-matrix fidelity on all 21 single-qubit Paulis.
"""

from __future__ import annotations

import numpy as np

_SEED = 20261231 + 945

H = np.array(
    [[int(b) for b in format(v + 1, "03b")] for v in range(7)], dtype=np.uint8
).T  # 3x7, column j = binary of j+1


def simplex_codewords() -> list[int]:
    """The 8 C^perp codewords as 7-bit integers (row space of H)."""
    out = []
    for s in range(8):
        combo = np.zeros(7, dtype=np.uint8)
        for i in range(3):
            if (s >> i) & 1:
                combo ^= H[i]
        v = 0
        for b in combo:
            v = v * 2 + int(b)
        out.append(v)
    return out


def encode_zero(n_anc: int = 6) -> np.ndarray:
    """|0_L> |0>^6 statevector; data qubits occupy the top-7 index bits."""
    dim = 1 << 13
    psi = np.zeros(dim, dtype=np.complex128)
    for c in simplex_codewords():
        psi[c << n_anc] = 1.0 / np.sqrt(8.0)
    return psi


def apply_pauli(psi: np.ndarray, q: int, pauli: str) -> np.ndarray:
    """Pauli on data qubit q (q=0 is data MSB -> index bit 12-n_anc...)."""
    n_anc = 6
    mask = 1 << (n_anc + 6 - q)
    out = np.zeros_like(psi)
    for i in range(len(psi)):
        if not i & mask:
            j = i | mask
            if pauli == "X":
                out[j] += psi[i]
                out[i] += psi[j]
            elif pauli == "Y":
                out[j] += 1j * psi[i]
                out[i] += -1j * psi[j]
            else:
                out[i] += psi[i]
                out[j] += -psi[j]
    return out


def _data_bits(i: int, n_anc: int = 6) -> np.ndarray:
    return np.array([(i >> (n_anc + 6 - q)) & 1 for q in range(7)], dtype=np.uint8)


def _syndrome_of(bits: np.ndarray) -> np.ndarray:
    return np.asarray((H @ bits) % 2, dtype=np.uint8)


def _extract(psi: np.ndarray, anc_base: int) -> np.ndarray:
    """CNOT-parity: ancilla bit k (at anc_base+k) ^= (H x)_k."""
    n_anc = 6
    out = np.zeros_like(psi)
    for i in range(len(psi)):
        bits = _data_bits(i, n_anc)
        syn = _syndrome_of(bits)
        j = i
        for k in range(3):
            if syn[k]:
                j ^= 1 << (n_anc - 1 - (anc_base + k))
        out[j] += psi[i]
    return out


def _correct_bits(psi: np.ndarray, anc_base: int) -> np.ndarray:
    """Flip data bit j iff the 3 ancilla bits equal syndrome column j."""
    n_anc = 6
    out = np.zeros_like(psi)
    for i in range(len(psi)):
        syn = np.array(
            [(i >> (n_anc - 1 - (anc_base + k))) & 1 for k in range(3)],
            dtype=np.uint8,
        )
        j = i
        if syn.any():
            for col in range(7):
                if np.array_equal(H[:, col], syn):
                    j ^= 1 << (n_anc + 6 - col)
                    break
        out[j] += psi[i]
    return out


def _hadamard_data(psi: np.ndarray) -> np.ndarray:
    """H^7 on the data register (Walsh transform per ancilla)."""
    n_anc = 6
    out = np.zeros_like(psi)
    scale = 1.0 / np.sqrt(128.0)
    for a in range(1 << n_anc):
        vec = np.zeros(128, dtype=np.complex128)
        for x in range(128):
            vec[x] = psi[(x << n_anc) | a]
        res = np.zeros(128, dtype=np.complex128)
        for y in range(128):
            acc = 0j
            for x in range(128):
                acc += vec[x] * (1 if (x & y).bit_count() % 2 == 0 else -1)
            res[y] = acc * scale
        for y in range(128):
            out[(y << n_anc) | a] = res[y]
    return out


def decode_state(psi: np.ndarray) -> np.ndarray:
    s1 = _correct_bits(_extract(psi, 0), 0)
    had = _hadamard_data(s1)
    s2 = _correct_bits(_extract(had, 3), 3)
    return _hadamard_data(s2)


def data_density(psi: np.ndarray, n_anc: int = 6) -> np.ndarray:
    """Reduced 128x128 density matrix of the data register."""
    dim = 1 << n_anc
    rho = np.zeros((128, 128), dtype=np.complex128)
    for a in range(dim):
        v = np.array([psi[(x << n_anc) | a] for x in range(128)])
        rho += np.outer(v, v.conj())
    return rho


def bench_steane_code(seed: int = _SEED) -> dict[str, float]:
    _ = np.random.default_rng(seed)
    psi0 = encode_zero()
    target = np.zeros(128, dtype=np.complex128)
    for c in simplex_codewords():
        target[c] = 1.0 / np.sqrt(8.0)
    ok = 0
    trials = 0
    for q in range(7):
        for pauli in ("X", "Y", "Z"):
            err = apply_pauli(psi0, q, pauli)
            rec = decode_state(err)
            rho = data_density(rec)
            fid = float(np.real(np.vdot(target, rho @ target)))
            ok += fid > 0.999
            trials += 1
    rec = decode_state(psi0)
    rho = data_density(rec)
    fid = float(np.real(np.vdot(target, rho @ target)))
    ok += fid > 0.999
    trials += 1
    return {"synthetic_steane_code": ok / trials}
