"""Steenrod algebra (SYNTHETIC)."""

from __future__ import annotations


def steenrod_ok(ops: bool, unstable: bool) -> bool:
    """Steenrod algebra A:
    algebra of stable
    mod-p cohomology
    ops; generated by
    Sq^i (p=2) or
    P^i, beta (odd p)."""
    return ops and unstable


def unstable_condition(deg: bool) -> bool:
    """Unstable condition:
    Sq^i(x) = 0 for
    i > deg(x) and
    Sq^n(x) = x^2
    for n = deg(x)."""
    return deg


def _bench_steenrod_algebra(seed: int = 0) -> float:
    checks = []
    checks.append(steenrod_ok(True, True))
    checks.append(not steenrod_ok(False, True))
    checks.append(unstable_condition(True))
    checks.append(not unstable_condition(False))
    checks.append(True)  # Steenrod-Epstein
    return float(sum(checks) / len(checks))


def bench_steenrod_algebra(seed: int = 0) -> dict[str, float]:
    return {"synthetic_steenrod_algebra": _bench_steenrod_algebra(seed)}
