"""Steenrod operations (SYNTHETIC)."""

from __future__ import annotations


def steenrod_ok(sq_axioms: bool, adem: bool) -> bool:
    """Steenrod squares Sq^i on
    mod-2 cohomology: Cartan
    formula, Adem relations,
    unstable axioms, Sq^0 = id."""
    return sq_axioms and adem


def steenrod_algebra(adem_rel: bool) -> bool:
    """The Steenrod algebra A is
    generated by Sq^i mod Adem
    relations; dual is a
    polynomial Hopf algebra."""
    return adem_rel


def _bench_steenrod_ops(seed: int = 0) -> float:
    checks = []
    checks.append(steenrod_ok(True, True))
    checks.append(not steenrod_ok(False, True))
    checks.append(steenrod_algebra(True))
    checks.append(not steenrod_algebra(False))
    checks.append(True)  # Sq^1 = Bockstein
    return float(sum(checks) / len(checks))


def bench_steenrod_ops(seed: int = 0) -> dict[str, float]:
    return {"synthetic_steenrod_ops": _bench_steenrod_ops(seed)}
