"""Stone duality for finite Boolean algebras (SYNTHETIC)."""

from __future__ import annotations

from itertools import combinations


def powerset_algebra(n: int) -> set[frozenset[int]]:
    """The Boolean algebra P({0..n-1}): all subsets."""
    elts = list(range(n))
    return {frozenset(s) for r in range(n + 1) for s in combinations(elts, r)}


def atoms(alg: set[frozenset[int]]) -> set[frozenset[int]]:
    """Atoms = minimal nonzero elements = singletons."""
    return {a for a in alg if a and not any(b < a and b for b in alg)}


def ultrafilter_of(pt: int, alg: set[frozenset[int]]) -> set[frozenset[int]]:
    """Principal ultrafilter generated by the atom {pt}."""
    return {a for a in alg if pt in a}


def _bench_stone_duality(seed: int = 0) -> float:
    checks = []
    alg = powerset_algebra(3)
    at = atoms(alg)
    checks.append(len(at) == 3)
    checks.append(len(alg) == 8)
    # Stone space has 3 points; each ultrafilter is principal
    ufs = [ultrafilter_of(i, alg) for i in range(3)]
    checks.append(all(len(u) == 4 for u in ufs))  # half the algebra
    # ultrafilters are distinct
    checks.append(len({frozenset(u) for u in ufs}) == 3)
    # every element of the algebra is in exactly half the ultrafilters:
    # clopen sets of the Stone space correspond to algebra elements
    a = frozenset({0, 1})
    count = sum(a in u for u in ufs)
    checks.append(count == 2)  # clopen {0,1} contains points 0,1
    # complement law: A or X\A in each ultrafilter, not both
    for a in alg:
        ins = sum(a in u for u in ufs) + sum(frozenset(set(range(3)) - a) in u for u in ufs)
        checks.append(ins == 3)
    return float(sum(checks) / len(checks))


def bench_stone_duality(seed: int = 0) -> dict[str, float]:
    return {"synthetic_stone_duality": _bench_stone_duality(seed)}
