"""Ultraproducts and Łoś's theorem on finite structures (SYNTHETIC bench)."""

from __future__ import annotations

from fractions import Fraction


def make_struct(n: int, edge: set[tuple[int, int]]) -> dict:
    return {"n": n, "edge": edge}


def satisfies(struct: dict, formula: tuple) -> bool:
    """formulas: ("edge",i,j), ("and",f,g), ("not",f), ("exists_edge",) means ∃x∃y E(x,y)."""
    tag = formula[0]
    if tag == "edge":
        return (formula[1], formula[2]) in struct["edge"]
    if tag == "and":
        return satisfies(struct, formula[1]) and satisfies(struct, formula[2])
    if tag == "not":
        return not satisfies(struct, formula[1])
    if tag == "exists_edge":
        return bool(struct["edge"])
    if tag == "degree_ge":
        # ∃ vertex with degree >= k
        k = formula[1]
        deg: dict[int, int] = {}
        for x, _y in struct["edge"]:
            deg[x] = deg.get(x, 0) + 1
        return any(d >= k for d in deg.values())
    raise ValueError(tag)


def ultraproduct_satisfies(structs: list[dict], formula: tuple, index_set: set[int]) -> bool:
    """Łoś: ultraproduct ⊨ φ iff {i : S_i ⊨ φ} ∈ U. Here U = cofinite/principal
    filter generated by index_set — model holds iff witnesses ⊆ U."""
    witness = {i for i, s in enumerate(structs) if satisfies(s, formula)}
    return witness >= index_set and bool(witness)


def almost_all(structs: list[dict], formula: tuple, frac: Fraction = Fraction(2, 3)) -> bool:
    hits = sum(1 for s in structs if satisfies(s, formula))
    return hits >= len(structs) * frac


def _bench_ultraproduct(seed: int = 0) -> float:
    checks = []
    s1 = make_struct(3, {(0, 1)})
    s2 = make_struct(3, set())
    checks.append(satisfies(s1, ("exists_edge",)))
    checks.append(not satisfies(s2, ("exists_edge",)))
    checks.append(satisfies(s1, ("edge", 0, 1)))
    checks.append(satisfies(s1, ("degree_ge", 1)))
    # ultraproduct over 3 structures with U = principal filter at indices {0,2}
    structs = [s1, s2, make_struct(4, {(0, 1), (1, 2), (2, 3)})]
    checks.append(ultraproduct_satisfies(structs, ("exists_edge",), {0, 2}))
    checks.append(not ultraproduct_satisfies(structs, ("exists_edge",), {1}))
    checks.append(almost_all(structs, ("exists_edge",)))
    return sum(checks) / len(checks)


def bench_ultraproduct(seed: int = 0) -> dict[str, float]:
    return {"synthetic_ultraproduct": _bench_ultraproduct(seed)}
