"""Weyl group of A2 = S3 acting on the hyperplane x+y+z=0 (SYNTHETIC)."""

from __future__ import annotations

import numpy as np


def reflect(v: np.ndarray, alpha: np.ndarray) -> np.ndarray:
    """Simple reflection s_alpha(v) = v - 2(v.a)/(a.a) a."""
    return np.asarray(v - 2.0 * (v @ alpha) / (alpha @ alpha) * alpha)


def generate_weyl() -> set[tuple[float, ...]]:
    """All reflections generated by s1,s2 on roots; collect distinct points."""
    a1 = np.array([1.0, -1.0, 0.0])
    a2 = np.array([0.0, 1.0, -1.0])
    e1 = np.array([1.0, 0.0, -1.0])
    pts = {tuple(np.round(e1, 9))}
    frontier = [e1]
    s = [a1, a2]
    while frontier:
        v = frontier.pop()
        for a in s:
            w = reflect(v, a)
            t = tuple(np.round(w, 9))
            if t not in pts:
                pts.add(t)
                frontier.append(w)
    return pts


def _bench_weyl_group_a2(seed: int = 0) -> float:
    checks = []
    a1 = np.array([1.0, -1.0, 0.0])
    a2 = np.array([0.0, 1.0, -1.0])
    # s_a^2 = id
    v = np.array([1.0, 2.0, -3.0])
    checks.append(np.allclose(reflect(reflect(v, a1), a1), v))
    # Weyl group of A2 has 6 elements acting on positive roots
    w = generate_weyl()
    checks.append(len(w) == 6)
    # reflections preserve inner product (isometry)
    u = np.array([2.0, -1.0, -1.0])
    checks.append(np.isclose(reflect(u, a1) @ reflect(v, a1), u @ v))
    # Coxeter relation (s1 s2)^3 = 1: s1s2 s1s2 s1s2 (v) = v
    x = v.copy()
    for _ in range(3):
        x = reflect(reflect(x, a2), a1)
    checks.append(np.allclose(x, v))
    return float(sum(checks) / len(checks))


def bench_weyl_group_a2(seed: int = 0) -> dict[str, float]:
    return {"synthetic_weyl_group_a2": _bench_weyl_group_a2(seed)}
