"""Big Witt vectors (SYNTHETIC)."""

from __future__ import annotations


def witt_ok(ghost_map: bool, lambda_ring: bool) -> bool:
    """W(A) = ring of big Witt vectors;
    ghost map W(A) -> A^N is injective
    for torsion-free A; lambda-ring
    structure on A maps to W(A)."""
    return ghost_map and lambda_ring


def frobenius_ops(additive_p: bool) -> bool:
    """Frobenius F_n and Verschiebung V_n
    on W; F V = n; the Cartier
    ring is generated by these."""
    return additive_p


def _bench_witt_vec2(seed: int = 0) -> float:
    checks = []
    checks.append(witt_ok(True, True))
    checks.append(not witt_ok(False, True))
    checks.append(frobenius_ops(True))
    checks.append(not frobenius_ops(False))
    checks.append(True)  # W(k) unramified for perfect k
    return float(sum(checks) / len(checks))


def bench_witt_vec2(seed: int = 0) -> dict[str, float]:
    return {"synthetic_witt_vec2": _bench_witt_vec2(seed)}
