"""Expected-shortfall and joint VaR–ES backtests.

Expected shortfall is not elicitable on its own, so backtests target
the jointly-elicitable (VaR, ES) pair or standardized exceedance
residuals.

References:
- Acerbi & Szekely (2014): Z1/Z2 unconditional ES tests via exceedances.
- McNeil & Frey (2000): exceedance-residual goodness-of-fit (bootstrap).
- Du & Escanciano (2017): joint VaR–ES backtests via cumulative violations.
- Nolde & Ziegel (2017): elicitability limits of ES.
- Berkowitz (2001): censored-normal transform used for PIT style tests.
"""

from __future__ import annotations

import numpy as np
from numpy.typing import NDArray
from scipy import stats

Array = NDArray[np.float64]


def _aligned(returns: Array, var: Array, es: Array, n: int = 50) -> tuple[Array, Array, Array]:
    r = np.asarray(returns, dtype=float).reshape(-1)
    v = np.asarray(var, dtype=float).reshape(-1)
    e = np.asarray(es, dtype=float).reshape(-1)
    if not (r.size == v.size == e.size) or r.size < n:
        raise ValueError(f"series must share length >= {n}")
    if not (np.all(np.isfinite(r)) and np.all(np.isfinite(v)) and np.all(np.isfinite(e))):
        raise ValueError("series must be finite")
    if np.any(e < v):
        raise ValueError("ES must be at least as extreme as VaR (loss convention: ES >= VaR)")
    return r, v, e


def acerbi_szekely_test(
    returns: Array, var: Array, es: Array, n_boot: int = 500, seed: int = 0
) -> dict[str, float]:
    """Acerbi–Szekely (2014) unconditional ES test.

    ``Z2 = (1/N_e) sum_{t: r_t < VaR_t} (r_t / ES_t) - 1``; under correct
    ES forecasts E[r/ES | exceedance] = 1, so E[Z2] = 0. Sign convention:
    returns/var/es are expressed as losses (positive = bad). The p-value
    is generated by an iid bootstrap over the violation indicator and
    residual ratio — a fixed-marginal resampling."""
    r, v, e = _aligned(returns, var, es)
    hits = r > v
    n_e = int(hits.sum())
    if n_e < 3:
        raise ValueError("too few exceedances for the AS test")
    ratio = r[hits] / e[hits]
    z2 = float(ratio.mean() - 1.0)
    # Bootstrap under H0: replace observed ratios with draws of a
    # correctly-specified model — exceedance residual r/ES ~ F where the
    # tail mean is 1 by construction; we resample residuals scaled to
    # have conditional mean 1, preserving the empirical shape.
    rng = np.random.default_rng(seed)
    shape = ratio / ratio.mean()
    boots = np.empty(n_boot)
    for b in range(n_boot):
        z = rng.choice(shape, size=n_e, replace=True)
        boots[b] = z.mean() - 1.0
    p = float(2.0 * min(np.mean(boots <= z2), np.mean(boots >= z2)))
    p = max(p, 1.0 / n_boot)
    return {
        "z2": z2,
        "pvalue": p,
        "n_exceedances": float(n_e),
        "mean_ratio": float(ratio.mean()),
    }


def mcneil_frey_test(
    returns: Array, var: Array, es: Array, n_boot: int = 500, seed: int = 0
) -> dict[str, float]:
    """McNeil–Frey (2000) exceedance-residual test.

    Standardized exceedance residuals ``eps_t = (r_t - VaR_t) / (ES_t - VaR_t)``
    for r_t > VaR_t should be iid with mean ~ 1 (unit-mean positive
    residuals). A bootstrap on the standardized residuals gives the
    p-value for H0: E[eps] = 1."""
    r, v, e = _aligned(returns, var, es)
    denom = e - v
    hits = r > v
    if hits.sum() < 3:
        raise ValueError("too few exceedances")
    eps = (r[hits] - v[hits]) / np.maximum(denom[hits], 1e-12)
    stat = float(eps.mean() - 1.0)
    rng = np.random.default_rng(seed)
    boots = np.empty(n_boot)
    eps_c = eps / eps.mean()  # enforce unit mean under H0
    for b in range(n_boot):
        boots[b] = rng.choice(eps_c, size=eps.size, replace=True).mean() - 1.0
    p = float(2.0 * min(np.mean(boots <= stat), np.mean(boots >= stat)))
    p = max(p, 1.0 / n_boot)
    return {
        "statistic": stat,
        "pvalue": p,
        "n_exceedances": float(hits.sum()),
        "mean_eps": float(eps.mean()),
    }


def exceedance_residuals(returns: Array, var: Array, es: Array) -> dict[str, Array | float]:
    """Standardized exceedance residuals and diagnostics.

    ``eps_t = (r_t - VaR_t)/(ES_t - VaR_t)`` over violations; returns the
    series plus skew/mean and a Lagrange-type independence flag based on
    lag-1 autocorrelation of the violation-scaled residuals."""
    r, v, e = _aligned(returns, var, es)
    hits = r > v
    if hits.sum() < 3:
        raise ValueError("too few exceedances")
    denom = np.maximum(e - v, 1e-12)
    eps = (r[hits] - v[hits]) / denom[hits]
    if eps.size >= 4:
        ac1 = float(np.corrcoef(eps[:-1], eps[1:])[0, 1])
    else:
        ac1 = np.nan
    return {
        "residuals": eps,
        "mean": float(eps.mean()),
        "skew": float(stats.skew(eps)),
        "lag1_ac": ac1,
        "n_exceedances": float(hits.sum()),
    }


def du_escanciano_test(hits: Array, alpha: float = 0.99) -> dict[str, float]:
    """Du–Escanciano (2017) cumulative-violation autocorrelation screen.

    Transforms the hit sequence to cumulative violations
    ``H_t = sum_{s<=t} I_s``; under correct conditional calibration the
    demeaned violation process is a martingale difference — a Ljung–Box
    on centered hits detects residual dependence."""
    h = np.asarray(hits, dtype=float).reshape(-1)
    if h.size < 50 or not np.all((h == 0.0) | (h == 1.0)):
        raise ValueError("hits must be binary with length >= 50")
    n = h.size
    p = 1.0 - alpha
    u = h - p  # martingale difference under H0
    if u.std() == 0:
        raise ValueError("no violations — degenerate")
    m = 5
    r = np.array([np.corrcoef(u[k:], u[:-k])[0, 1] for k in range(1, m + 1)])
    lb = float(n * (n + 2) * np.sum(r * r / (n - np.arange(1, m + 1))))
    return {
        "statistic": lb,
        "pvalue": float(1.0 - stats.chi2.cdf(lb, m)),
        "df": float(m),
        "violation_rate": float(h.mean()),
        "expected_rate": float(p),
    }
