"""Stochastic portfolio theory (SPT) analytics — rank processes, market
entropy, diversity measures, and functionally generated (FG) portfolios.

This lane ADDS a pure-analytics SPT layer. It complements the portfolio
package (``src/quant_fund/portfolio/``, weight construction + constraints)
and ``models/momentum.py`` (signal extraction) without modifying either —
nothing here feeds live trading. numpy only (no new deps); every estimator
is deterministic given its inputs; malformed inputs fail closed with
``ValueError``.

References (fetch-verified 2026-10-01)
--------------------------------------
1. Fernholz, E. R. (2002). *Stochastic Portfolio Theory*. Applications of
   Mathematics 48, Springer-Verlag, New York. DOI 10.1007/978-1-4757-3699-1.
   Master equation (Thm. 3.1.5), rank processes / local times (Ch. 4–5),
   diversity weighting (Ex. 3.4.4).
2. Fernholz, R., Karatzas, I., Kardaras, C. (2005). "Diversity and relative
   arbitrage in equity markets." *Finance and Stochastics* 9(1), 1–27.
   DOI 10.1007/s00780-004-0129-4; arXiv:0803.3093. NOTE: the wave brief
   suggested arXiv:cond-mat/0504061 — that ID is a superconductivity
   preprint (Nernst effect, Zn-doped YBCO); the paper's actual arXiv posting
   is 0803.3093. Journal citation confirmed via RePEc/DOI.
3. Karatzas, I., Ruf, J. (2017). "Trading strategies generated by Lyapunov
   functions." *Finance and Stochastics* 21, 753–787.
   DOI 10.1007/s00780-017-0332-8; arXiv:1603.08245. NOTE: the wave brief
   suggested arXiv:1605.07451 — that ID is a fracture-mechanics preprint
   (thermally activated fracture of porous media); the correct arXiv ID is
   1603.08245 (v3, June 2017; journal ref added).
4. Banner, A., Fernholz, D. (2008). "Short-term relative arbitrage in
   volatility-stabilized markets." *Annals of Finance* 4(4), 445–454.
   DOI 10.1007/s10436-007-0085-z.

Machinery implemented here
--------------------------
1. ``market_weights`` — capitalization panel → market weights μ on the
   open simplex; strictly-positive caps required (fail-closed).
2. ``ranked_weights`` / ``rank_gaps`` / ``rank_occupation_matrix`` —
   ranked weight processes μ_(1) ≥ … ≥ μ_(n), adjacent log-rank gaps
   g_k = log(μ_(k)/μ_(k+1)) ≥ 0 (reflected semimartingales under the
   first-order/Atlas picture, Fernholz 2002 §5), and the empirical
   rank-occupation matrix (fraction of time each stock holds each rank).
3. ``market_entropy`` — S(μ) = −Σ μ_i log μ_i trajectory;
   ``diversity_index`` — D_p(μ) = (Σ μ_i^p)^{1/p}, p ∈ (0, 1).
4. ``fg_weights`` — Fernholz's functionally generated portfolio
   π_i = μ_i·(D_i log G(μ) + 1 − Σ_j μ_j D_j log G(μ)) given the gradient
   of log G on the path; ``diversity_weights`` / ``entropy_weights`` are
   the closed-form instances for G = D_p and G = S (the latter yields
   π_i = −μ_i log μ_i / S(μ)).
5. ``fg_master_equation`` — the master-equation decomposition

       log(V_π/V_μ)(T) = log G(μ_T) − log G(μ_0) + ∫ Θ(t) dt,

   evaluated on a discrete grid. Θ (the FG drift rate) follows from Itô's
   lemma applied to log G(μ) combined with the relative-wealth identity
   d log(V_π/V_μ) = Σ π_i d log μ_i + γ*_π dt:

       Θ = γ*_π − (1/2)Σ_i π_i σ̂^{logμ}_{ii}
                − (1/2)Σ_{ij} μ_i μ_j (D²_{ij} log G) σ̂^{logμ}_{ij},

   where σ̂^{logμ}, σ̂^{logX} are realized quadratic-(co)variation rates of
   the log-weight and log-capitalization processes and γ*_π =
   (1/2)(Σ π_i σ̂_{ii} − Σ π_i π_j σ̂_{ij}) is the portfolio excess growth
   rate (invariant to numéraire — identical under σ̂^{logX} and σ̂^{logμ}).
   For G = D_p the drift collapses to the canonical closed form
   Θ = (1−p)·γ*_π (``diversity_drift_rate`` — Fernholz 2002, Ex. 3.4.4);
   the two formulas agree to machine precision (checked in the bench).
   DISCRETIZATION HONESTY: per-step realized covariations make the
   identity asymptotic — the cumulative residual is O(√dt), reported
   verbatim by the bench rather than hidden.
6. ``local_time_at_zero`` — occupation-density estimator of the
   semimartingale local time at zero of a nonnegative path x:
   Λ̂ = (1/(2h)) Σ_k (Δx_k)² · 1{x_k < h}. Normalizer 1/(2h) and default
   bandwidth h = 4·std(Δx) were calibrated against the exact Euler–
   Skorokhod reflected scheme (``reflected_path``), where the true
   compensator is known — see the bench's estimator error.
7. ``rank_gap_local_times`` — the per-rank local times Λ_{k,k+1} that
   drive rank turnover and the drift earned at rank boundaries.
8. ``diversity_arbitrage_horizon`` — the FKK (2005) guaranteed-
   outperformance bound: since log D_p ≥ 0 on the simplex,
   rel_t = log D_p(μ_t) − log D_p(μ_0) + ∫Θ ≥ θ_min·t − log D_p(μ_0),
   so π dominates the market with certainty once
   T* = log D_p(μ_0)/θ_min. ``first_passage_time`` gives the realized
   crossing on a path; Banner–Fernholz (2008) is why this matters at
   short horizons under volatility stabilization.
9. ``growth_optimal_weights`` — argmax_π γ*(π) over the simplex by
   projected gradient ascent with exact simplex projection
   (deterministic; the excess-growth objective is numéraire-invariant).
10. ``simulate_gbm_market`` / ``reflected_path`` / ``bench_fernholz_spt``
    — seeded SYNTHETIC correctness worlds (AGENTS.md honesty contract #2).
    Simulated markets are correctness evidence for the decompositions
    ONLY — never market evidence. ``live_pnl_claim`` False everywhere.

Scores/metrics here are diagnostic quantities of market structure
(entropy, drift, local time), not P&L claims. ``bench_fernholz_spt``
returns a flat ``dict[str, float]`` of ``synthetic_``-prefixed numbers.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from numpy.typing import NDArray

Array = NDArray[np.float64]
IntArray = NDArray[np.int64]

STUDY_SCHEMA = "fernholz_spt.v1"
BENCH_SEED = 24
_SIMPLEX_TOL = 1e-8
_WEIGHT_FLOOR_TOL = 1e-9


# ---------------------------------------------------------------------------
# Validation helpers — fail closed on malformed market data
# ---------------------------------------------------------------------------


def _check_seed(seed: int) -> int:
    if isinstance(seed, bool) or not isinstance(seed, (int, np.integer)):
        raise ValueError("seed must be an integer")
    return int(seed)


def _check_dt(dt: float) -> float:
    value = float(dt)
    if not np.isfinite(value) or value <= 0.0:
        raise ValueError("dt must be finite and positive")
    return value


def _check_p(p: float) -> float:
    value = float(p)
    if not np.isfinite(value) or value <= 0.0 or value >= 1.0:
        raise ValueError("diversity exponent p must lie in (0, 1)")
    return value


def _require_caps(caps: Array, name: str = "caps") -> Array:
    x = np.asarray(caps, dtype=float)
    if x.ndim != 2 or x.shape[0] < 2 or x.shape[1] < 2:
        raise ValueError(f"{name} must be a (T >= 2, n >= 2) panel; got {x.shape}")
    if not np.isfinite(x).all():
        raise ValueError(f"{name} must be finite")
    if np.any(x <= 0.0):
        raise ValueError(f"{name} must be strictly positive (capitalizations)")
    return x


def _require_simplex(mu: Array, name: str = "mu") -> Array:
    m = np.asarray(mu, dtype=float)
    if m.ndim == 1:
        m = m.reshape(1, -1)
    if m.ndim != 2 or m.shape[1] < 2 or m.shape[0] < 1:
        raise ValueError(f"{name} must be (T, n >= 2)")
    if not np.isfinite(m).all():
        raise ValueError(f"{name} must be finite")
    if np.any(m <= 0.0):
        raise ValueError(f"{name} must be strictly positive on the open simplex")
    if np.abs(m.sum(axis=1) - 1.0).max() > _SIMPLEX_TOL:
        raise ValueError(f"{name} rows must sum to 1 (simplex)")
    return m


def _require_portfolio(pi: Array, name: str = "pi") -> Array:
    """Portfolio weights: simplex membership, zeros allowed (unlike μ)."""
    p = np.asarray(pi, dtype=float)
    if p.ndim == 1:
        p = p.reshape(1, -1)
    if p.ndim != 2 or p.shape[1] < 2 or p.shape[0] < 1:
        raise ValueError(f"{name} must be (T, n >= 2)")
    if not np.isfinite(p).all():
        raise ValueError(f"{name} must be finite")
    if np.any(p < -1e-10):
        raise ValueError(f"{name} must be nonnegative (long-only simplex)")
    if np.abs(p.sum(axis=1) - 1.0).max() > _SIMPLEX_TOL:
        raise ValueError(f"{name} rows must sum to 1 (simplex)")
    return np.asarray(np.maximum(p, 0.0), dtype=float)


def _require_path_match(a: Array, b: Array, a_name: str, b_name: str) -> None:
    if a.shape != b.shape:
        raise ValueError(f"{a_name} and {b_name} must share shape; {a.shape} vs {b.shape}")


# ---------------------------------------------------------------------------
# 1. Market weights, rank processes, occupation
# ---------------------------------------------------------------------------


def market_weights(caps: Array) -> Array:
    """Capitalizations → market weights μ_i = X_i / Σ_j X_j.

    Accepts a single date ``(n,)`` or a path ``(T, n)``; always returns
    ``(T, n)``. Caps must be finite and strictly positive.
    """
    x = np.asarray(caps, dtype=float)
    if x.ndim == 1:
        x = x.reshape(1, -1)
    if x.ndim != 2 or x.shape[1] < 2 or x.shape[0] < 1:
        raise ValueError(f"caps must be (n >= 2,) or (T, n >= 2); got {x.shape}")
    if not np.isfinite(x).all():
        raise ValueError("caps must be finite")
    if np.any(x <= 0.0):
        raise ValueError("caps must be strictly positive (capitalizations)")
    totals = x.sum(axis=1, keepdims=True)
    return np.asarray(x / totals, dtype=np.float64)


def ranked_weights(mu: Array) -> Array:
    """Ranked market weights μ_(1) ≥ μ_(2) ≥ … ≥ μ_(n) per row."""
    m = _require_simplex(mu)
    return -np.sort(-m, axis=1)


def rank_permutations(mu: Array) -> IntArray:
    """``order[t, k]`` = index of the stock holding rank ``k`` at time ``t``."""
    m = _require_simplex(mu)
    return np.argsort(-m, axis=1).astype(np.int64)


def rank_gaps(mu: Array) -> Array:
    """Adjacent log-rank gaps g_k = log(μ_(k)/μ_(k+1)) ≥ 0, shape (T, n−1).

    Under the Atlas/first-order market picture these are nonnegative
    semimartingales whose local times at zero are the Λ_{k,k+1} of
    Fernholz (2002) §4–5 — the turnover earned at rank boundaries.
    """
    ranked = ranked_weights(mu)
    gaps = np.log(ranked[:, :-1]) - np.log(ranked[:, 1:])
    return np.asarray(np.maximum(gaps, 0.0), dtype=float)


def rank_occupation_matrix(mu: Array) -> Array:
    """``occ[i, k]`` = fraction of the path where stock ``i`` holds rank ``k``.

    Rows sum to 1 (each stock occupies exactly one rank per date).
    """
    m = _require_simplex(mu)
    order = rank_permutations(m)
    n_assets = m.shape[1]
    occ = np.zeros((n_assets, n_assets), dtype=float)
    for k in range(n_assets):
        counts = np.bincount(order[:, k], minlength=n_assets)
        occ[:, k] = counts / m.shape[0]
    return occ


# ---------------------------------------------------------------------------
# 2. Entropy and diversity measures
# ---------------------------------------------------------------------------


def market_entropy(mu: Array) -> Array:
    """Market entropy S(μ) = −Σ_i μ_i log μ_i per date (nats)."""
    m = _require_simplex(mu)
    return np.asarray(-np.sum(m * np.log(m), axis=1), dtype=float)


def diversity_index(mu: Array, p: float = 0.5) -> Array:
    """Diversity measure D_p(μ) = (Σ_i μ_i^p)^{1/p} per date, p ∈ (0, 1).

    D_p ∈ [1, n^{(1−p)/p}]: it equals 1 at a vertex (one stock = whole
    market) and n^{(1−p)/p} on the uniform weight. Its generating role:
    ``diversity_weights`` below.
    """
    pv = _check_p(p)
    m = _require_simplex(mu)
    return np.asarray(np.sum(m**pv, axis=1) ** (1.0 / pv), dtype=float)


def diverse(mu: Array, eps: float) -> bool:
    """FKK (2005) diversity check: every weight ≤ 1 − eps along the path."""
    if not np.isfinite(eps) or not 0.0 < float(eps) < 1.0:
        raise ValueError("eps must lie in (0, 1)")
    m = _require_simplex(mu)
    return bool(np.all(m <= 1.0 - float(eps)))


# ---------------------------------------------------------------------------
# 3. Functionally generated portfolios
# ---------------------------------------------------------------------------


def fg_weights(mu: Array, grad_log_g: Array) -> Array:
    """Fernholz's FG portfolio from the gradient of log G on the path.

    π_i(t) = μ_i(t)·(D_i log G(μ(t)) + 1 − Σ_j μ_j(t) D_j log G(μ(t))).

    The construction guarantees Σ_i π_i = 1 (since Σ_i dμ_i = 0).
    Weights that come out negative beyond ``1e-9`` mean G is not a valid
    portfolio generator on this region of the simplex → fail closed;
    tiny numerical negatives are clipped and the weights renormalized.
    """
    m = _require_simplex(mu)
    g = np.asarray(grad_log_g, dtype=float)
    if g.shape != m.shape or not np.isfinite(g).all():
        raise ValueError("grad_log_g must be finite with the same shape as mu")
    tilt = 1.0 - np.sum(m * g, axis=1, keepdims=True)
    pi = m * (g + tilt)
    if np.any(pi < -_WEIGHT_FLOOR_TOL):
        raise ValueError(
            "G is not a valid portfolio generator here — negative FG weight "
            f"{float(pi.min()):.3e} (Lyapunov/generator condition violated)"
        )
    pi = np.maximum(pi, 0.0)
    return np.asarray(pi / pi.sum(axis=1, keepdims=True), dtype=float)


def diversity_weights(mu: Array, p: float = 0.5) -> Array:
    """Closed-form diversity-weighted portfolio π_i = μ_i^p / Σ_j μ_j^p."""
    pv = _check_p(p)
    m = _require_simplex(mu)
    powered = m**pv
    return np.asarray(powered / powered.sum(axis=1, keepdims=True), dtype=float)


def entropy_weights(mu: Array) -> Array:
    """Closed-form entropy-generated portfolio π_i = −μ_i log μ_i / S(μ)."""
    m = _require_simplex(mu)
    s = market_entropy(m)
    if np.any(s <= 0.0):
        raise ValueError("degenerate entropy (a vertex) — S(μ) must be positive")
    return np.asarray((-m * np.log(m)) / s[:, None], dtype=float)


def diversity_log_g(mu: Array, p: float = 0.5) -> Array:
    """log D_p(μ) per date — the log generating function for ``diversity_weights``."""
    return np.log(diversity_index(mu, p))


def diversity_grad_log_g(mu: Array, p: float = 0.5) -> Array:
    """D_i log D_p(μ) = μ_i^{p−1} / Σ_j μ_j^p per date."""
    pv = _check_p(p)
    m = _require_simplex(mu)
    s_p = np.sum(m**pv, axis=1, keepdims=True)
    return np.asarray(m ** (pv - 1.0) / s_p, dtype=float)


def diversity_hess_log_g(mu: Array, p: float = 0.5) -> Array:
    """Hessian of log D_p(μ): (p−1)μ_i^{p−2}δ_ij/S_p − p·μ_i^{p−1}μ_j^{p−1}/S_p²."""
    pv = _check_p(p)
    m = _require_simplex(mu)
    s_p = np.sum(m**pv, axis=1)
    eye = np.eye(m.shape[1])
    term_diag = (pv - 1.0) * np.einsum("ti,ij->tij", m ** (pv - 2.0), eye) / s_p[:, None, None]
    term_outer = (
        pv * np.einsum("ti,tj->tij", m ** (pv - 1.0), m ** (pv - 1.0)) / (s_p**2)[:, None, None]
    )
    return np.asarray(term_diag - term_outer, dtype=float)


def entropy_log_g(mu: Array) -> Array:
    """log S(μ) per date — the log generating function for ``entropy_weights``."""
    s = market_entropy(mu)
    if np.any(s <= 0.0):
        raise ValueError("degenerate entropy (a vertex) — S(μ) must be positive")
    return np.asarray(np.log(s), dtype=float)


def entropy_grad_log_g(mu: Array) -> Array:
    """D_i log S(μ) = −(log μ_i + 1)/S(μ) per date."""
    m = _require_simplex(mu)
    s = market_entropy(m)
    if np.any(s <= 0.0):
        raise ValueError("degenerate entropy (a vertex) — S(μ) must be positive")
    return np.asarray(-(np.log(m) + 1.0) / s[:, None], dtype=float)


def entropy_hess_log_g(mu: Array) -> Array:
    """Hessian of log S(μ): −δ_ij/(μ_i S) − (log μ_i + 1)(log μ_j + 1)/S²."""
    m = _require_simplex(mu)
    s = market_entropy(m)
    if np.any(s <= 0.0):
        raise ValueError("degenerate entropy (a vertex) — S(μ) must be positive")
    eye = np.eye(m.shape[1])
    term_diag = -np.einsum("ti,ij->tij", 1.0 / (m * s[:, None]), eye)
    ds = np.log(m) + 1.0
    term_outer = np.einsum("ti,tj->tij", ds, ds) / (s**2)[:, None, None]
    return np.asarray(term_diag - term_outer, dtype=float)


# ---------------------------------------------------------------------------
# 4. Realized covariations, excess growth, exact relative returns
# ---------------------------------------------------------------------------


def log_cap_covariation(caps: Array, dt: float) -> Array:
    """Realized covariation rate of log-caps per step: ΔlogX_i·ΔlogX_j/dt."""
    x = _require_caps(caps)
    step = _check_dt(dt)
    d = np.diff(np.log(x), axis=0)
    return np.asarray(np.einsum("ti,tj->tij", d, d) / step, dtype=float)


def log_weight_covariation(mu: Array, dt: float) -> Array:
    """Realized covariation rate of log-weights: Δlogμ_i·Δlogμ_j/dt.

    Equals Fernholz's relative covariance τ_{ij} measured on the grid —
    the log weights are the caps expressed in market units, so this is
    numéraire-relative by construction.
    """
    m = _require_simplex(mu)
    if m.shape[0] < 2:
        raise ValueError("mu must have at least 2 dates")
    step = _check_dt(dt)
    d = np.diff(np.log(m), axis=0)
    return np.asarray(np.einsum("ti,tj->tij", d, d) / step, dtype=float)


def excess_growth_rate(pi: Array, sigma: Array) -> Array:
    """Portfolio excess growth γ*_π = (1/2)(Σ_i π_i σ_ii − Σ_ij π_i π_j σ_ij).

    ``pi`` is ``(T, n)`` and ``sigma`` a matching ``(T, n, n)`` covariance-rate
    path. Numéraire-invariant: identical values under the return covariance
    σ^{logX} and the relative (market-unit) covariance σ^{logμ}.
    """
    p_arr = _require_portfolio(pi, "pi")
    s = np.asarray(sigma, dtype=float)
    if s.shape != (p_arr.shape[0], p_arr.shape[1], p_arr.shape[1]) or not np.isfinite(s).all():
        raise ValueError("sigma must be a finite (T, n, n) path matching pi")
    diag_term = np.einsum("ti,tii->t", p_arr, s)
    quad_term = np.einsum("ti,tij,tj->t", p_arr, s, p_arr)
    return np.asarray(0.5 * (diag_term - quad_term), dtype=float)


def relative_log_returns(caps: Array, pi: Array) -> Array:
    """Exact per-step relative log returns of π vs the market portfolio.

    Over step k the self-financing gross returns are
    R_π = Σ_i π_i(k) X_i(k+1)/X_i(k) and R_μ = Σ_i μ_i(k) X_i(k+1)/X_i(k)
    (the market holds weights μ); the step contribution is
    log R_π − log R_μ — no approximation.
    """
    x = _require_caps(caps)
    p_arr = _require_portfolio(pi, "pi")
    if p_arr.shape[0] != x.shape[0] or p_arr.shape[1] != x.shape[1]:
        raise ValueError("pi must be a (T, n) path aligned with caps")
    gross = x[1:] / x[:-1]
    ret_pi = np.einsum("ti,ti->t", p_arr[:-1], gross)
    ret_mu = np.einsum("ti,ti->t", market_weights(x)[:-1], gross)
    if np.any(ret_pi <= 0.0) or np.any(ret_mu <= 0.0):
        raise ValueError("nonpositive gross return — check caps/weights")
    return np.asarray(np.log(ret_pi) - np.log(ret_mu), dtype=float)


# ---------------------------------------------------------------------------
# 5. Master-equation drift and decomposition
# ---------------------------------------------------------------------------


def fg_drift_rate(
    pi: Array, mu: Array, hess_log_g: Array, sigma_mu: Array, sigma_x: Array
) -> Array:
    """FG drift rate Θ(t) of the master equation (per unit time).

    Θ = γ*_π − (1/2)Σ_i π_i σ̂^{logμ}_{ii}
             − (1/2)Σ_ij μ_iμ_j (D²_ij log G) σ̂^{logμ}_{ij}.

    ``pi``, ``mu`` and ``hess_log_g`` are evaluated at step starts
    (``(T−1, n)`` / ``(T−1, n, n)``); ``sigma_mu`` = ``log_weight_covariation``
    output and ``sigma_x`` = ``log_cap_covariation`` output, both ``(T−1, n, n)``.
    """
    p_arr = _require_portfolio(pi, "pi")
    m = _require_simplex(mu)
    _require_path_match(p_arr, m, "pi", "mu")
    h = np.asarray(hess_log_g, dtype=float)
    s_mu = np.asarray(sigma_mu, dtype=float)
    s_x = np.asarray(sigma_x, dtype=float)
    t_steps, n_assets = p_arr.shape
    for name, arr in (("hess_log_g", h), ("sigma_mu", s_mu), ("sigma_x", s_x)):
        if arr.shape != (t_steps, n_assets, n_assets) or not np.isfinite(arr).all():
            raise ValueError(f"{name} must be a finite (T−1, n, n) path")
    gamma_star = excess_growth_rate(p_arr, s_x)
    corr_weights = 0.5 * np.einsum("ti,tii->t", p_arr, s_mu)
    corr_hess = 0.5 * np.einsum("ti,tj,tij,tij->t", m, m, h, s_mu)
    return np.asarray(gamma_star - corr_weights - corr_hess, dtype=float)


def diversity_drift_rate(pi: Array, sigma_mu: Array, p: float = 0.5) -> Array:
    """Closed-form drift of the D_p-generated portfolio: Θ = (1−p)·γ*_π.

    Obtained by substituting the D_p Hessian into ``fg_drift_rate`` and
    using numéraire invariance of γ* — the canonical Fernholz (2002)
    Ex. 3.4.4 result. Nonnegative whenever the market has excess growth —
    this is the FKK "free lunch" drift earned by diversity weighting.
    """
    pv = _check_p(p)
    p_arr = _require_portfolio(pi, "pi")
    s_mu = np.asarray(sigma_mu, dtype=float)
    if (
        s_mu.shape != (p_arr.shape[0], p_arr.shape[1], p_arr.shape[1])
        or not np.isfinite(s_mu).all()
    ):
        raise ValueError("sigma_mu must be a finite (T−1, n, n) path matching pi")
    return np.asarray((1.0 - pv) * excess_growth_rate(p_arr, s_mu), dtype=float)


@dataclass(frozen=True)
class MasterEquation:
    """Master-equation decomposition on a discrete path.

    ``lhs`` = exact cumulative log(V_π/V_μ); ``delta_log_g`` =
    log G(μ_T) − log G(μ_0); ``theta_integral`` = Σ_k Θ_k·dt;
    ``residual_abs``/``residual_rel`` = |lhs − (delta_log_g + ∫Θ)| — the
    O(√dt) discretization error of the continuous-time identity.
    """

    relative_path: Array  # per-step exact relative log returns, (T−1,)
    theta_rate: Array  # per-step drift rate Θ_k, (T−1,)
    lhs: float
    delta_log_g: float
    theta_integral: float
    residual_abs: float
    residual_rel: float


def fg_master_equation(
    caps: Array,
    pi: Array,
    log_g: Array,
    hess_log_g: Array,
    dt: float,
) -> MasterEquation:
    """Verify log(V_π/V_μ) = Δlog G(μ) + ∫Θ on a discrete market path.

    The left side uses the exact self-financing relative log returns; the
    right side telescopes log G exactly and integrates Θ with the realized
    covariations of the step. ``log_g`` is the (T,) path of log G(μ);
    ``hess_log_g`` the (T, n, n) Hessian path of log G — both evaluated at
    step starts inside the routine.
    """
    x = _require_caps(caps)
    step = _check_dt(dt)
    m = market_weights(x)
    p_arr = _require_portfolio(pi, "pi")
    if p_arr.shape != m.shape:
        raise ValueError("pi must be a (T, n) path aligned with caps")
    lg = np.asarray(log_g, dtype=float).reshape(-1)
    if lg.shape != (x.shape[0],) or not np.isfinite(lg).all():
        raise ValueError("log_g must be a finite (T,) path")
    h = np.asarray(hess_log_g, dtype=float)
    if h.shape != (x.shape[0], x.shape[1], x.shape[1]) or not np.isfinite(h).all():
        raise ValueError("hess_log_g must be a finite (T, n, n) path")

    rel = relative_log_returns(x, p_arr)
    theta = fg_drift_rate(
        p_arr[:-1],
        m[:-1],
        h[:-1],
        log_weight_covariation(m, step),
        log_cap_covariation(x, step),
    )
    lhs = float(np.sum(rel))
    delta_log_g = float(lg[-1] - lg[0])
    theta_integral = float(np.sum(theta) * step)
    rhs = delta_log_g + theta_integral
    residual_abs = abs(lhs - rhs)
    residual_rel = residual_abs / abs(lhs) if abs(lhs) > 0.0 else residual_abs
    return MasterEquation(
        relative_path=np.asarray(rel, dtype=float),
        theta_rate=np.asarray(theta, dtype=float),
        lhs=lhs,
        delta_log_g=delta_log_g,
        theta_integral=theta_integral,
        residual_abs=float(residual_abs),
        residual_rel=float(residual_rel),
    )


def diversity_master_equation(
    caps: Array, p: float = 0.5, dt: float = 1.0 / 252.0
) -> MasterEquation:
    """Master equation specialized to G = D_p (closed-form pieces)."""
    m = market_weights(_require_caps(caps))
    pi = diversity_weights(m, p)
    return fg_master_equation(
        caps,
        pi,
        diversity_log_g(m, p),
        diversity_hess_log_g(m, p),
        dt,
    )


def entropy_master_equation(caps: Array, dt: float = 1.0 / 252.0) -> MasterEquation:
    """Master equation specialized to G = S (entropy), closed-form pieces."""
    m = market_weights(_require_caps(caps))
    pi = entropy_weights(m)
    return fg_master_equation(caps, pi, entropy_log_g(m), entropy_hess_log_g(m), dt)


# ---------------------------------------------------------------------------
# 6. Local times: rank-occupation estimators
# ---------------------------------------------------------------------------


def local_time_at_zero(path: Array, dt: float, bandwidth: float | None = None) -> float:
    """Occupation-density local-time estimate at zero of a nonnegative path.

    Λ̂ = (1/(2h)) Σ_k (Δx_k)² · 1{x_k < h}. For a continuous nonnegative
    semimartingale this converges to the semimartingale local time at 0 as
    the grid refines (occupation-density formula). The 1/(2h) normalizer
    and the default bandwidth h = 4·std(Δx) are calibrated against the
    Euler–Skorokhod reflected scheme in ``reflected_path`` where the true
    compensator is known (≈2–5% relative error on bench grids).

    Negative entries beyond ``1e-12`` fail closed — the estimator is only
    meaningful for processes that live on one side of zero (e.g. log rank
    gaps, reflected diffusions).
    """
    x = np.asarray(path, dtype=float).reshape(-1)
    _check_dt(dt)
    if x.size < 2 or not np.isfinite(x).all():
        raise ValueError("path must be a finite 1-d array of length >= 2")
    if np.any(x < -1e-12):
        raise ValueError("path must be nonnegative (one-sided local time at zero)")
    x = np.maximum(x, 0.0)
    increments = np.diff(x)
    if bandwidth is None:
        h = 4.0 * float(np.std(increments))
        if not np.isfinite(h) or h <= 0.0:
            raise ValueError("degenerate increments — cannot pick a bandwidth")
    else:
        h = float(bandwidth)
        if not np.isfinite(h) or h <= 0.0:
            raise ValueError("bandwidth must be finite and positive")
    return float(np.sum((increments**2) * (x[:-1] < h)) / (2.0 * h))


def rank_gap_local_times(mu: Array, dt: float, bandwidth: float | None = None) -> Array:
    """Per-boundary local times Λ̂_{k,k+1} of the log rank gaps, shape (n−1,)."""
    gaps = rank_gaps(mu)
    return np.asarray(
        [local_time_at_zero(gaps[:, k], dt, bandwidth) for k in range(gaps.shape[1])],
        dtype=float,
    )


def reflected_path(x0: float, increments: Array) -> tuple[Array, Array]:
    """Euler–Skorokhod reflected path + its exact discrete compensator.

    R_{k+1} = max(R_k + ε_k, 0), L_{k+1} = L_k + max(−(R_k + ε_k), 0) —
    the standard reflected-diffusion discretization: L accumulates exactly
    the pushes needed to keep R ≥ 0, so it is the scheme's own true local
    time and the honest ground truth for ``local_time_at_zero``.
    """
    start = float(x0)
    if not np.isfinite(start) or start < 0.0:
        raise ValueError("x0 must be finite and nonnegative")
    eps = np.asarray(increments, dtype=float).reshape(-1)
    if eps.size < 1 or not np.isfinite(eps).all():
        raise ValueError("increments must be a finite 1-d array")
    n_steps = eps.size
    r = np.empty(n_steps + 1, dtype=float)
    local = np.empty(n_steps + 1, dtype=float)
    r[0] = start
    local[0] = 0.0
    for k in range(n_steps):
        y = r[k] + float(eps[k])
        r[k + 1] = max(y, 0.0)
        local[k + 1] = local[k] + max(-y, 0.0)
    return r, local


# ---------------------------------------------------------------------------
# 7. Relative-arbitrage horizons and growth-optimal diagnostics
# ---------------------------------------------------------------------------


def diversity_arbitrage_horizon(mu0: Array, p: float, theta_min: float) -> float:
    """FKK guaranteed-outperformance horizon T* = log D_p(μ_0)/θ_min.

    With Θ ≥ θ_min > 0 the relative log wealth satisfies
    rel_t ≥ θ_min·t − log D_p(μ_0) (since log D_p ≥ 0), so π beats the
    market with certainty for all t > T*. Requires θ_min > 0 (an
    estimated drift floor — the diagnostics, not a promise).
    """
    theta = float(theta_min)
    if not np.isfinite(theta) or theta <= 0.0:
        raise ValueError("theta_min must be finite and positive")
    pv = _check_p(p)
    m = _require_simplex(np.asarray(mu0, dtype=float))
    if m.shape[0] != 1:
        raise ValueError("mu0 must be a single market-weight vector")
    log_d0 = float(np.log(diversity_index(m, pv)[0]))
    if log_d0 <= 0.0:
        raise ValueError("mu0 has no diversity gap to harvest (D_p(μ0) <= 1)")
    return float(log_d0 / theta)


def first_passage_time(values: Array, dt: float, level: float = 0.0) -> float:
    """First t where the (cumulative) path ≥ level; ``nan`` if never."""
    step = _check_dt(dt)
    if not np.isfinite(level):
        raise ValueError("level must be finite")
    v = np.asarray(values, dtype=float).reshape(-1)
    if v.size < 1 or not np.isfinite(v).all():
        raise ValueError("values must be a finite 1-d array")
    hits = np.nonzero(v >= float(level))[0]
    if hits.size == 0:
        return float("nan")
    return float((int(hits[0]) + 1) * step)


def _project_simplex(v: Array) -> Array:
    """Euclidean projection onto the probability simplex (Duchi et al.)."""
    u = np.sort(v)[::-1]
    css = np.cumsum(u) - 1.0
    rho = np.nonzero(u * np.arange(1, v.size + 1) > css)[0]
    if rho.size == 0:
        raise ValueError("simplex projection failed")
    theta = float(css[rho[-1]]) / float(rho[-1] + 1)
    return np.asarray(np.maximum(v - theta, 0.0), dtype=float)


def growth_optimal_weights(
    sigma: Array, n_iter: int = 2000, step_size: float | None = None
) -> Array:
    """argmax over the simplex of the excess growth rate γ*(π).

    Objective γ*(π) = (1/2)(π·diag(σ) − πᵀσπ), numéraire-invariant.
    Deterministic projected-gradient ascent with exact simplex projection;
    step size defaults to 1/λ_max(σ) (descent-safe for the concave
    quadratic objective). σ must be symmetric PSD (fail-closed).
    """
    s = np.asarray(sigma, dtype=float)
    if s.ndim != 2 or s.shape[0] != s.shape[1] or s.shape[0] < 2:
        raise ValueError("sigma must be a square (n >= 2) matrix")
    if not np.isfinite(s).all():
        raise ValueError("sigma must be finite")
    if not np.allclose(s, s.T, atol=1e-10):
        raise ValueError("sigma must be symmetric")
    eig = np.linalg.eigvalsh(s)
    if eig[0] < -1e-8:
        raise ValueError("sigma must be positive semidefinite")
    if isinstance(n_iter, bool) or not isinstance(n_iter, (int, np.integer)) or int(n_iter) < 10:
        raise ValueError("n_iter must be an integer >= 10")
    n_assets = s.shape[0]
    a = np.diag(s).copy()
    lam = float(eig[-1])
    eta = float(step_size) if step_size is not None else (1.0 / lam if lam > 0.0 else 1.0)
    if not np.isfinite(eta) or eta <= 0.0:
        raise ValueError("step_size must be finite and positive")
    pi = np.full(n_assets, 1.0 / n_assets, dtype=float)
    for _ in range(int(n_iter)):
        grad = 0.5 * a - s @ pi
        pi = _project_simplex(pi + eta * grad)
    return np.asarray(pi / pi.sum(), dtype=float)


# ---------------------------------------------------------------------------
# 8. Synthetic worlds and the bench
# ---------------------------------------------------------------------------


def simulate_gbm_market(
    n_assets: int = 24,
    n_steps: int = 4096,
    dt: float = 1.0 / 2048.0,
    seed: int = 0,
    *,
    rho: float = 0.4,
    vol_lo: float = 0.30,
    vol_hi: float = 0.90,
    drift_scale: float = 0.05,
    cap_spread: float = 4.0,
) -> Array:
    """Seeded correlated-GBM capitalization panel ``(n_steps+1, n_assets)``.

    d log X_i = (g_i − σ_i²/2)dt + σ_i(√ρ·dW_mkt + √(1−ρ)·dW_i) with
    uniform-parameter grids and log-uniform initial caps spanning
    ``cap_spread`` decades of dispersion. SYNTHETIC correctness world —
    decomposition evidence only, never market evidence.
    """
    for name, value in (("n_assets", n_assets), ("n_steps", n_steps)):
        if isinstance(value, bool) or not isinstance(value, (int, np.integer)) or int(value) < 2:
            raise ValueError(f"{name} must be an integer >= 2")
    step = _check_dt(dt)
    if not np.isfinite(rho) or not 0.0 <= float(rho) < 1.0:
        raise ValueError("rho must lie in [0, 1)")
    if not np.isfinite(vol_lo) or not np.isfinite(vol_hi) or not 0.0 < vol_lo <= vol_hi:
        raise ValueError("vol bounds must satisfy 0 < vol_lo <= vol_hi")
    if not np.isfinite(drift_scale) or float(drift_scale) < 0.0:
        raise ValueError("drift_scale must be finite and nonnegative")
    if not np.isfinite(cap_spread) or float(cap_spread) <= 0.0:
        raise ValueError("cap_spread must be finite and positive")

    rng = np.random.default_rng(_check_seed(seed))
    n = int(n_assets)
    t = int(n_steps)
    vols = rng.uniform(float(vol_lo), float(vol_hi), n)
    drifts = rng.uniform(-float(drift_scale), float(drift_scale), n)
    x0 = np.exp(rng.uniform(-float(cap_spread) / 2.0, float(cap_spread) / 2.0, n))
    common = rng.normal(0.0, 1.0, (t, n))
    idio = rng.normal(0.0, 1.0, (t, n))
    shocks = np.sqrt(float(rho)) * common + np.sqrt(1.0 - float(rho)) * idio
    increments = (drifts[None, :] - 0.5 * vols[None, :] ** 2) * step + (
        vols[None, :] * np.sqrt(step) * shocks
    )
    log_x = np.log(x0)[None, :] + np.vstack([np.zeros((1, n)), np.cumsum(increments, axis=0)])
    caps = np.exp(log_x)
    if not np.isfinite(caps).all() or np.any(caps <= 0.0):
        raise ValueError("simulation produced a degenerate capitalization path")
    return np.asarray(caps, dtype=float)


def arbitrage_diagnostics(
    caps: Array,
    p: float = 0.5,
    dt: float = 1.0 / 252.0,
    margin: float = 0.02,
) -> dict[str, float]:
    """Diversity-vs-cap relative-arbitrage diagnostics on one path.

    Reports the exact relative value path summary (end level and worst
    drawdown), the realized first passage of log(V_π/V_μ) ≥ ``margin``
    (a "strong arbitrage" threshold — crossing 0 alone is trivially fast),
    the realized average drift, the FKK horizon bound T* computed from
    that drift, and the slack ratio T*/realized.
    """
    step = _check_dt(dt)
    pv = _check_p(p)
    x = _require_caps(caps)
    if not np.isfinite(margin) or float(margin) < 0.0:
        raise ValueError("margin must be finite and nonnegative")
    m = market_weights(x)
    pi = diversity_weights(m, pv)
    rel = np.cumsum(relative_log_returns(x, pi))
    theta = diversity_drift_rate(pi[:-1], log_weight_covariation(m, step), pv)
    theta_bar = float(np.mean(theta))
    log_d0 = float(np.log(diversity_index(m[:1], pv)[0]))
    horizon_bound = float(log_d0 / theta_bar) if theta_bar > 0.0 else float("nan")
    realized = first_passage_time(rel, step, float(margin))
    slack = (
        horizon_bound / realized
        if np.isfinite(horizon_bound) and np.isfinite(realized) and realized > 0.0
        else float("nan")
    )
    return {
        "relative_log_wealth_end": float(rel[-1]),
        "relative_log_wealth_min": float(rel.min()),
        "theta_mean": theta_bar,
        "theta_min_step": float(np.min(theta)),
        "log_diversity_start": log_d0,
        "horizon_bound": horizon_bound,
        "horizon_realized": realized,
        "horizon_slack": slack,
    }


def bench_fernholz_spt(seed: int = BENCH_SEED) -> dict[str, float]:
    """Flat dict of SYNTHETIC headline numbers (correctness evidence only).

    Every key is ``synthetic_``-prefixed; values are plain floats. Runs the
    seeded GBM market and the reflected-BM ground truth; reports the
    master-equation residuals (diversity + entropy generators), the
    closed-form vs general drift gap, the local-time estimator error,
    entropy recovery, rank local-time totals, and the arbitrage-horizon
    diagnostics.
    """
    s = _check_seed(seed)
    dt = 1.0 / 2048.0
    caps = simulate_gbm_market(n_assets=24, n_steps=4096, dt=dt, seed=s)
    mu = market_weights(caps)

    # FG decomposition residuals (theory vs exact discrete relative returns).
    p_div = 0.5
    decomp_div = diversity_master_equation(caps, p_div, dt)
    decomp_ent = entropy_master_equation(caps, dt)

    # Closed-form vs general Θ for the D_p generator (should be ~0 gap).
    pi_div = diversity_weights(mu, p_div)
    sigma_mu = log_weight_covariation(mu, dt)
    theta_closed = diversity_drift_rate(pi_div[:-1], sigma_mu, p_div)
    theta_general = fg_drift_rate(
        pi_div[:-1],
        mu[:-1],
        diversity_hess_log_g(mu, p_div)[:-1],
        sigma_mu,
        log_cap_covariation(caps, dt),
    )
    theta_gap = float(np.max(np.abs(theta_closed - theta_general)))

    # Local-time estimator vs exact reflected-path compensator. The
    # estimator is ~unbiased but a single path's local time is a small
    # denominator (few zero visits ⇒ noisy ratio), so pool 12 independent
    # reflections of horizon τ = 4 and compare sums (~4% pooled error).
    rng = np.random.default_rng(s + 1)
    lt_steps, lt_dt = 160_000, 2.5e-5
    est_sum = 0.0
    true_sum = 0.0
    for _ in range(12):
        reflected, true_lt = reflected_path(0.0, rng.normal(0.0, np.sqrt(lt_dt), lt_steps))
        est_sum += local_time_at_zero(reflected, lt_dt, bandwidth=4.0 * np.sqrt(lt_dt))
        true_sum += float(true_lt[-1])
    lt_error = abs(est_sum - true_sum) / true_sum

    # Entropy recovery on a uniform market (exact answer log n).
    n_assets = mu.shape[1]
    uniform = np.full((1, n_assets), 1.0 / n_assets)
    entropy_uniform_error = abs(float(market_entropy(uniform)[0]) - float(np.log(n_assets)))

    # Rank local times + arbitrage diagnostics on the simulated market.
    rank_lts = rank_gap_local_times(mu, dt)
    diag = arbitrage_diagnostics(caps, p_div, dt)
    slack = diag["horizon_slack"]
    return {
        "synthetic_diversity_master_eq_residual": decomp_div.residual_abs,
        "synthetic_diversity_master_eq_rel_residual": decomp_div.residual_rel,
        "synthetic_entropy_master_eq_residual": decomp_ent.residual_abs,
        "synthetic_entropy_master_eq_rel_residual": decomp_ent.residual_rel,
        "synthetic_theta_closed_form_gap": theta_gap,
        "synthetic_diversity_theta_integral": decomp_div.theta_integral,
        "synthetic_entropy_theta_integral": decomp_ent.theta_integral,
        "synthetic_local_time_rel_error": float(lt_error),
        "synthetic_entropy_uniform_error": float(entropy_uniform_error),
        "synthetic_rank_local_time_max": float(np.max(rank_lts)),
        "synthetic_rank_local_time_sum": float(np.sum(rank_lts)),
        "synthetic_relative_log_wealth_end": diag["relative_log_wealth_end"],
        "synthetic_relative_log_wealth_min": diag["relative_log_wealth_min"],
        "synthetic_theta_mean": diag["theta_mean"],
        "synthetic_horizon_bound": diag["horizon_bound"],
        "synthetic_horizon_realized": float(diag["horizon_realized"])
        if np.isfinite(diag["horizon_realized"])
        else float(caps.shape[0] - 1) * dt,
        "synthetic_horizon_slack": float(slack) if np.isfinite(slack) else float("nan"),
    }


__all__ = [
    "BENCH_SEED",
    "STUDY_SCHEMA",
    "Array",
    "MasterEquation",
    "arbitrage_diagnostics",
    "bench_fernholz_spt",
    "diverse",
    "diversity_arbitrage_horizon",
    "diversity_drift_rate",
    "diversity_grad_log_g",
    "diversity_hess_log_g",
    "diversity_index",
    "diversity_log_g",
    "diversity_master_equation",
    "diversity_weights",
    "entropy_grad_log_g",
    "entropy_hess_log_g",
    "entropy_log_g",
    "entropy_master_equation",
    "entropy_weights",
    "excess_growth_rate",
    "fg_drift_rate",
    "fg_master_equation",
    "fg_weights",
    "first_passage_time",
    "growth_optimal_weights",
    "local_time_at_zero",
    "log_cap_covariation",
    "log_weight_covariation",
    "market_entropy",
    "market_weights",
    "rank_gap_local_times",
    "rank_gaps",
    "rank_occupation_matrix",
    "rank_permutations",
    "ranked_weights",
    "reflected_path",
    "relative_log_returns",
    "simulate_gbm_market",
]
