#!/usr/bin/env python3
"""Regenerate the architecture-atlas diagrams and freshness manifest.

Reads first-party imports out of ``src/`` with the stdlib ``ast`` parser (no
third-party dependency) and emits deterministic Mermaid artifacts:

- ``docs/architecture/module_deps.mmd`` — package-level import graph,
- ``docs/architecture/data_flow.mmd`` — ingest → features → model →
  backtest/paper → receipt,
- ``docs/architecture/paper_loop_sequence.mmd`` — paper/shadow event loop,
- ``docs/architecture/manifest.json`` — sorted module list + package edges,
- generated blocks spliced into ``docs/ARCHITECTURE_ATLAS.md`` between
  ``<!-- BEGIN GENERATED: <name> -->`` / ``<!-- END GENERATED: <name> -->``
  markers.

``--check`` regenerates everything in memory and exits 1 when any committed
artifact (``.mmd``, ``manifest.json``, or an embedded atlas block) is stale.
Determinism contract: every emitted collection is sorted, so byte-for-byte
comparison is stable across runs and platforms.

Curated diagrams (data flow, paper loop) declare every displayed node as an
anchor key. Renderers print the symbol stored under that key, and
``verify_diagram_bindings`` fails when the rendered label does not contain
it — renaming a label, or retargeting an anchor while leaving the old label,
fails generation and ``--check``.
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

FIRST_PARTY_ROOTS = ("quant_fund", "fx1")
SCHEMA_VERSION = 1
GENERATOR = "scripts/gen_arch_diagrams.py"
ARCH_DIR = Path("docs") / "architecture"
ATLAS_DOC = Path("docs") / "ARCHITECTURE_ATLAS.md"

GENERATED_HEADER = "%% Generated by scripts/gen_arch_diagrams.py — do not edit by hand."


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


# ---------------------------------------------------------------------------
# Import scanning
# ---------------------------------------------------------------------------


def iter_source_modules(src: Path) -> list[tuple[str, Path, bool]]:
    """Return sorted ``(dotted_module, repo-relative path, is_package)``."""
    out: list[tuple[str, Path, bool]] = []
    for path in sorted(src.rglob("*.py")):
        rel = path.relative_to(src).with_suffix("")
        parts = list(rel.parts)
        is_package = parts[-1] == "__init__"
        if is_package:
            parts = parts[:-1]
        if parts:
            out.append((".".join(parts), path, is_package))
    return sorted(out)


def _resolve_from(module: str, level: int, name: str | None, is_package: bool) -> str:
    """Resolve ``from <name> import ...`` at ``level`` inside ``module``.

    ``level == 0`` is absolute. For relative imports, level 1 is the current
    package: the module's parent for a regular module, the package itself for
    an ``__init__``.
    """
    if level == 0:
        return name or ""
    parts = module.split(".")
    drop = level - (1 if is_package else 0)
    base = parts[: len(parts) - drop]
    return ".".join(base + ([name] if name else []))


def parse_first_party_imports(
    path: Path, module: str, is_package: bool, known_modules: set[str]
) -> set[str]:
    """First-party import targets referenced by ``path`` (stdlib ast only).

    Includes function-level imports: optional/lazy dependencies (e.g. the
    W1 ``quant_fund.pit`` vault) are still real edges in the source.

    One edge per import alias: ``from a.b import c`` resolves to ``a.b.c``
    when that submodule exists, else to ``a.b``.
    """
    tree = ast.parse(path.read_text(encoding="utf-8"))
    targets: set[str] = set()
    for node in ast.walk(tree):
        candidates: list[str] = []
        if isinstance(node, ast.Import):
            candidates = [alias.name for alias in node.names]
        elif isinstance(node, ast.ImportFrom):
            base = _resolve_from(module, node.level, node.module, is_package)
            if base:
                candidates = [
                    f"{base}.{alias.name}" if f"{base}.{alias.name}" in known_modules else base
                    for alias in node.names
                ]
        for cand in candidates:
            if cand.split(".")[0] in FIRST_PARTY_ROOTS:
                targets.add(cand)
    return targets


def package_of(module: str) -> str:
    """Aggregate a dotted module to its second-level package node."""
    parts = module.split(".")
    if len(parts) > 1 and parts[0] in FIRST_PARTY_ROOTS:
        return ".".join(parts[:2])
    return parts[0]


def collect_graph(
    root: Path,
) -> tuple[list[str], Counter[tuple[str, str]], set[tuple[str, str]]]:
    """Scan ``src``; return (sorted modules, package edge counts, module edges).

    Package edges count distinct first-party modules imported per package
    pair. Module edges are the exact ``(importer, imported)`` pairs — the
    manifest stores them so ``--check`` detects any first-party import
    change, including moves within a package.
    """
    src = root / "src"
    modules = iter_source_modules(src)
    known_modules = {name for name, _, _ in modules}
    edges: Counter[tuple[str, str]] = Counter()
    module_edges: set[tuple[str, str]] = set()
    for name, path, is_package in modules:
        src_pkg = package_of(name)
        for target in parse_first_party_imports(path, name, is_package, known_modules):
            edges[(src_pkg, package_of(target))] += 1
            module_edges.add((name, target))
    return [name for name, _, _ in modules], edges, module_edges


# ---------------------------------------------------------------------------
# Symbol anchors for curated diagrams
# ---------------------------------------------------------------------------


def _top_level_symbols(path: Path) -> set[str]:
    """Top-level defs/classes/assignments plus ``Class.method`` members."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    names: set[str] = set()
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            names.add(node.name)
        elif isinstance(node, ast.ClassDef):
            names.add(node.name)
            for sub in node.body:
                if isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    names.add(f"{node.name}.{sub.name}")
        elif isinstance(node, ast.Assign):
            for tgt in node.targets:
                if isinstance(tgt, ast.Name):
                    names.add(tgt.id)
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            names.add(node.target.id)
    return names


def verify_anchors(root: Path) -> list[str]:
    """Return a list of errors for missing modules/symbols (empty when clean)."""
    errors: list[str] = []
    cache: dict[str, set[str]] = {}
    for anchor, (rel, symbol) in sorted(ANCHORS.items()):
        path = root / rel
        if not path.is_file():
            errors.append(f"{anchor}: module file missing: {rel}")
            continue
        if symbol == "*":
            continue
        if rel not in cache:
            cache[rel] = _top_level_symbols(path)
        if symbol not in cache[rel]:
            errors.append(f"{anchor}: {symbol} not defined at top level of {rel}")
    return errors


@dataclass(frozen=True)
class AnchoredNode:
    """A displayed diagram node whose label is taken from ``ANCHORS``."""

    node_id: str
    anchors: tuple[str, ...]
    detail: str = ""


@dataclass(frozen=True)
class FlowGroup:
    """One subgraph of the curated data-flow diagram."""

    group_id: str
    title: str
    nodes: tuple[AnchoredNode, ...]


# Anchors bind curated-diagram nodes to real code. ``*`` = module exists.
ANCHORS: dict[str, tuple[str, str]] = {
    "cli_main": ("src/quant_fund/cli/_app.py", "app"),
    "cli_paper": ("src/quant_fund/cli/ops_cmds.py", "paper"),
    "make_provider": ("src/quant_fund/data/ingest.py", "make_provider"),
    "ingest": ("src/quant_fund/data/ingest.py", "ingest"),
    "lake": ("src/quant_fund/data/lake.py", "Lake"),
    "adjust_prices": ("src/quant_fund/data/corporate_actions.py", "adjust_prices"),
    "listing_actions": ("src/quant_fund/data/corporate_actions.py", "apply_listing_actions"),
    "membership": ("src/quant_fund/data/universe.py", "build_membership_panel"),
    "security_master": ("src/quant_fund/data/security_master.py", "attach_master_attributes"),
    "pit_validate": ("src/quant_fund/data/point_in_time.py", "validate_feature_frame"),
    "build_features": ("src/quant_fund/features/engine.py", "build_features"),
    "feature_version": ("src/quant_fund/features/metadata.py", "FEATURE_SET_VERSION"),
    "build_labels": ("src/quant_fund/labels/engine.py", "build_labels"),
    "build_gold": ("src/quant_fund/pipeline/dataset.py", "build_gold"),
    "panel": ("src/quant_fund/pipeline/dataset.py", "panel"),
    "train": ("src/quant_fund/pipeline/train/ranking.py", "train_ranking"),
    "forecast_asof": ("src/quant_fund/pipeline/forecast/decide.py", "forecast_asof"),
    "optimize_asof": ("src/quant_fund/pipeline/forecast/decide.py", "optimize_asof"),
    "causal_weights": ("src/quant_fund/pipeline/forecast/decide.py", "build_causal_weight_panel"),
    "market_overlay": (
        "src/quant_fund/pipeline/forecast/covariance.py",
        "market_risk_overlay_asof",
    ),
    "market_state": ("src/quant_fund/schemas/forecast.py", "MarketState"),
    "fuse_signals": ("src/quant_fund/fusion/engine.py", "fuse_signals"),
    "optimizer": ("src/quant_fund/portfolio/optimizer.py", "optimize_mean_variance"),
    "risk_gate": ("src/quant_fund/portfolio/risk_gate.py", "check_order"),
    "total_cost": ("src/quant_fund/execution/costs.py", "total_cost"),
    "sim_broker": ("src/quant_fund/execution/simulated_broker.py", "SimulatedBroker"),
    "broker_submit": ("src/quant_fund/execution/simulated_broker.py", "SimulatedBroker.submit"),
    "broker_t2o": (
        "src/quant_fund/execution/simulated_broker.py",
        "SimulatedBroker.target_to_orders",
    ),
    "run_backtest": ("src/quant_fund/backtest/engine.py", "run_backtest"),
    "kill_switch": ("src/quant_fund/monitoring/kill_switch.py", "KillSwitch"),
    "paper_loop": ("src/quant_fund/paper/loop.py", "run_paper_loop"),
    "weight_fn": ("src/quant_fund/paper/loop.py", "WeightFn"),
    "replay_clock": ("src/quant_fund/paper/clock.py", "ReplayClock"),
    "wall_clock": ("src/quant_fund/paper/clock.py", "WallClock"),
    "ledger": ("src/quant_fund/paper/ledger.py", "PaperLedger"),
    "ledger_flush": ("src/quant_fund/paper/ledger.py", "PaperLedger.flush"),
    "ledger_broker_state": ("src/quant_fund/paper/ledger.py", "PaperLedger.save_broker_state"),
    "promo_dry_run": ("src/quant_fund/paper/ledger.py", "promotion_dry_run"),
    "run_research": ("src/quant_fund/research/agent.py", "run_research"),
    "verify_research": ("src/quant_fund/research/verify.py", "verify_research_artifact"),
    "validate_candidate": ("src/quant_fund/validation/gates.py", "validate_candidate"),
    "sim_live": ("src/quant_fund/paper/sim_live.py", "run_sim_live"),
    "fx1_cli": ("src/fx1/cli.py", "app"),
    "fx1_corpus": ("src/fx1/data/corpus.py", "*"),
    "fx1_honesty": ("src/fx1/honesty.py", "FORBIDDEN_HEADLINE_TOKENS"),
    "catalog": (
        "src/quant_fund/research/catalog/registry.py",
        "FORBIDDEN_RESEARCH_METRIC_KEYS",
    ),
}


def _format_symbol(symbol: str) -> str:
    """Render an anchored symbol the way the diagram should display it."""
    leaf = symbol.rsplit(".", 1)[-1]
    if leaf[:1].isupper():
        return symbol
    return f"{symbol}()"


def _symbol_text(key: str) -> str:
    spec = ANCHORS.get(key)
    if spec is None:
        return f"<missing:{key}>"
    return _format_symbol(spec[1])


def _node_label(node: AnchoredNode) -> str:
    label = " / ".join(_symbol_text(key) for key in node.anchors)
    if node.detail:
        label = f"{label}\\n{node.detail}"
    return label


def _participant_alias(node: AnchoredNode) -> str:
    alias = " / ".join(_symbol_text(key) for key in node.anchors)
    if node.detail:
        alias = f"{alias} {node.detail}"
    return alias


def _rendered_label(mermaid: str, node_id: str) -> str | None:
    """Return the label actually emitted for ``node_id``, if the node is present."""
    quoted = re.search(rf'(?m)^[ \t]*{re.escape(node_id)}\["([^"]*)"\]', mermaid)
    if quoted:
        return quoted.group(1)
    participant = re.search(
        rf"(?m)^[ \t]*participant[ \t]+{re.escape(node_id)}[ \t]+as[ \t]+(.+)$",
        mermaid,
    )
    if participant:
        return participant.group(1).strip()
    return None


def verify_diagram_bindings(root: Path) -> list[str]:
    """Fail when a displayed node is not rendered from its anchor symbol.

    ``verify_anchors`` alone accepts a diagram that names a different symbol
    than the one the anchor points at. This check parses the rendered Mermaid
    and requires each displayed node's label to contain every symbol its
    anchors name.
    """
    errors = verify_anchors(root)
    rendered = {
        "data_flow": render_data_flow(),
        "paper_loop": render_paper_loop(),
    }
    bound: list[tuple[str, AnchoredNode]] = [
        ("data_flow", node) for group in DATA_FLOW_GROUPS for node in group.nodes
    ]
    bound.extend(("paper_loop", node) for node in PAPER_LOOP_PARTICIPANTS)
    for diagram, node in bound:
        missing = [key for key in node.anchors if key not in ANCHORS]
        for key in missing:
            errors.append(f"{diagram}:{node.node_id}: unknown anchor {key}")
        if missing:
            continue
        label = _rendered_label(rendered[diagram], node.node_id)
        if label is None:
            errors.append(f"{diagram}:{node.node_id}: rendered node missing")
            continue
        for key in node.anchors:
            symbol = ANCHORS[key][1]
            if symbol not in label:
                errors.append(
                    f"{diagram}:{node.node_id}: label {label!r} does not include "
                    f"anchored symbol {symbol}"
                )
    return errors


# Curated data-flow nodes. Labels are rendered from ``ANCHORS``; do not hardcode
# symbol names in the detail string.
DATA_FLOW_GROUPS: tuple[FlowGroup, ...] = (
    FlowGroup(
        "pit",
        "point-in-time data",
        (
            AnchoredNode(
                "prov",
                ("make_provider",),
                "synthetic | file | hf_ohlcv_1m | public sources",
            ),
            AnchoredNode("ingest", ("ingest",), "bronze/silver parquet + data_manifest.json"),
            AnchoredNode("adj", ("adjust_prices", "listing_actions"), "corporate actions"),
            AnchoredNode("univ", ("membership",), "PIT universe"),
        ),
    ),
    FlowGroup(
        "gold",
        "gold panel",
        (
            AnchoredNode("feats", ("build_features", "feature_version"), "stamped on the frame"),
            AnchoredNode("labs", ("build_labels",), "forward-looking, never features"),
            AnchoredNode(
                "gold",
                ("build_gold", "panel"),
                "membership re-validated on cached gold",
            ),
        ),
    ),
    FlowGroup(
        "model",
        "forecast stack",
        (
            AnchoredNode("train", ("train",), "pipeline/train/ranking.py → joblib artifacts"),
            AnchoredNode("fcst", ("forecast_asof", "market_state"), "CQR intervals"),
            AnchoredNode("fuse", ("fuse_signals",), "transparent fusion"),
        ),
    ),
    FlowGroup(
        "alloc",
        "allocation + risk",
        (
            AnchoredNode("opt", ("optimizer",), "infeasible → diagnostics, no relaxation"),
            AnchoredNode("gate", ("risk_gate",), "deterministic pre-trade risk gate"),
            AnchoredNode("cost", ("total_cost",), "commission + spread + impact"),
        ),
    ),
    FlowGroup(
        "sim",
        "simulation (no live orders)",
        (
            AnchoredNode("bt", ("run_backtest",), "event-driven, next-open fills"),
            AnchoredNode("pl", ("paper_loop",), "champion + shadow slots"),
        ),
    ),
    FlowGroup(
        "evid",
        "evidence",
        (
            AnchoredNode("nb", ("run_research",), "sealed notebook + runs/<id>.json"),
            AnchoredNode("ver", ("verify_research",), "fail-closed recompute"),
            AnchoredNode("prom", ("validate_candidate",), "receipt-bound promotion gates"),
        ),
    ),
)

DATA_FLOW_CHAINS: tuple[tuple[str, ...], ...] = (
    ("prov", "ingest", "adj", "univ"),
    ("univ", "feats", "gold"),
    ("univ", "labs", "gold"),
    ("gold", "train", "fcst"),
    ("fcst", "fuse", "opt", "gate"),
    ("gate", "bt"),
    ("gate", "pl"),
    ("cost", "bt"),
    ("cost", "pl"),
    ("bt", "nb"),
    ("pl", "nb"),
    ("nb", "ver", "prom"),
)

PAPER_LOOP_PARTICIPANTS: tuple[AnchoredNode, ...] = (
    AnchoredNode("CLI", ("cli_paper",), ""),
    AnchoredNode("Loop", ("paper_loop",), ""),
    AnchoredNode("Clock", ("replay_clock", "wall_clock"), ""),
    AnchoredNode("W", ("weight_fn",), "weights panel"),
    AnchoredNode("CB", ("sim_broker",), "champion"),
    AnchoredNode("SB", ("sim_broker",), "shadow"),
    AnchoredNode("KS", ("kill_switch",), ""),
    AnchoredNode("RG", ("risk_gate",), "risk gate"),
    AnchoredNode("L", ("ledger",), ""),
)

PAPER_LOOP_MESSAGES: tuple[str, ...] = (
    "  CLI->>Loop: run_paper_loop(bars, cfg, champion/shadow weights)",
    "  opt resume",
    "    Loop->>L: load_broker_state(run_id)",
    "    L-->>Loop: prior champion/shadow state + cursors",
    "    Loop->>Loop: verify resume_fingerprint over bar prefix",
    "  end",
    "  Loop->>L: set_meta(data_source, label=PAPER_SIMULATED)",
    "  Loop->>Clock: ReplayClock(decision_dates)",
    "  loop each decision date t",
    "    Loop->>Clock: tick() -> t",
    "    Loop->>Loop: exec_dt = next bar open (FillConvention.NEXT_OPEN)",
    "    Loop->>CB: mark(pretrade marks: fresh opens + bounded carry)",
    "    Loop->>SB: mark(pretrade marks)",
    "    Loop->>W: champion_fn(t, cfg)",
    "    W-->>Loop: target weights",
    "    Loop->>W: shadow_fn(t, cfg) (optional)",
    "    Loop->>Loop: L1 divergence champion vs shadow",
    "    Loop->>CB: nav(pretrade_marks); break if <= 0",
    "    Loop->>Loop: market_risk_overlay_asof(cfg, bars, t)",
    "    Loop->>CB: target_to_orders(targets, marks)",
    "    loop each order",
    "      CB->>KS: assert_new_orders_allowed()",
    "      KS--xCB: KillSwitchActive when state != ENABLED",
    "      CB->>RG: check_order(nav, gross, net, participation, vol)",
    "      RG--xCB: RiskGateRejected on breach (counted)",
    "      CB->>CB: total_cost() then cash/shares update",
    "      CB-->>Loop: OrderRecord (fill or reject_reason)",
    "    end",
    "    Loop->>L: record_orders(step_recs, exec_dt)",
    "    Loop->>CB: mark(close marks) + exposures",
    "    Loop->>L: record_snapshot / record_shadow_equity",
    "    Loop->>L: flush()",
    "    Loop->>L: save_broker_state(cursor published LAST)",
    "  end",
    "  Loop->>L: promotion_dry_run() -> write_promotion_dry_run",
    "  Loop->>L: write_analytics_export + validate",
    "  Loop-->>CLI: PaperLoopResult{research_only, live_pnl_claim: false, paths}",
)


# ---------------------------------------------------------------------------
# Renderers (all deterministic — every collection is sorted)
# ---------------------------------------------------------------------------


def _mmd_id(package: str) -> str:
    return package.replace(".", "_").replace("-", "_")


def render_module_deps(modules: list[str], edges: Counter[tuple[str, str]]) -> str:
    known_pkgs = {package_of(m) for m in modules}
    qf = sorted(p for p in known_pkgs if p == "quant_fund" or p.startswith("quant_fund."))
    fx = sorted(p for p in known_pkgs if p == "fx1" or p.startswith("fx1."))
    ghost = sorted(
        {dst for (_, dst) in edges if dst not in known_pkgs}
        | {src for (src, _) in edges if src not in known_pkgs}
    )
    lines = [GENERATED_HEADER, "flowchart LR"]
    for group, title in (("quant_fund", "quant_fund (harness)"), ("fx1", "fx1 (model project)")):
        members = qf if group == "quant_fund" else fx
        # Prefix the cluster id. Mermaid shares a namespace with node ids, and
        # the root package nodes are already named ``quant_fund`` and ``fx1``.
        lines.append(f'  subgraph cluster_{group}["{title}"]')
        for pkg in members:
            lines.append(f'    {_mmd_id(pkg)}["{pkg}"]')
        lines.append("  end")
    for pkg in ghost:
        lines.append(f'  {_mmd_id(pkg)}["{pkg}"]:::ghost')
    for (src, dst), count in sorted(edges.items()):
        if src == dst:
            continue
        lines.append(f"  {_mmd_id(src)} -->|{count}| {_mmd_id(dst)}")
    lines += [
        "  classDef ghost stroke-dasharray: 5 5,color:#888",
        "  %% ghost nodes are lazily referenced packages absent from this tree",
    ]
    return "\n".join(lines) + "\n"


def render_data_flow() -> str:
    """ingest → features → model → backtest/paper → receipt. Labels come from anchors."""
    lines = [GENERATED_HEADER, "flowchart LR"]
    for group in DATA_FLOW_GROUPS:
        lines.append(f'  subgraph cluster_{group.group_id}["{group.title}"]')
        for node in group.nodes:
            lines.append(f'    {node.node_id}["{_node_label(node)}"]')
        lines.append("  end")
    for chain in DATA_FLOW_CHAINS:
        lines.append("  " + " --> ".join(chain))
    return "\n".join(lines) + "\n"


def render_paper_loop() -> str:
    """Sequence diagram of ``run_paper_loop``. Participant aliases come from anchors."""
    lines = [GENERATED_HEADER, "sequenceDiagram", "  autonumber"]
    for node in PAPER_LOOP_PARTICIPANTS:
        lines.append(f"  participant {node.node_id} as {_participant_alias(node)}")
    lines.extend(PAPER_LOOP_MESSAGES)
    return "\n".join(lines) + "\n"


def render_coverage(modules: list[str], edges: Counter[tuple[str, str]]) -> str:
    counts: Counter[str] = Counter(package_of(m) for m in modules)
    lines = ["| Package | Modules |", "|---|---|"]
    for pkg in sorted(counts):
        lines.append(f"| `{pkg}` | {counts[pkg]} |")
    n_edges = sum(1 for (s, d) in edges if s != d)
    lines.append("")
    lines.append(f"- Modules scanned: **{len(modules)}**")
    lines.append(f"- Packages: **{len(counts)}**")
    lines.append(f"- Cross-package import edges: **{n_edges}**")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Artifact assembly
# ---------------------------------------------------------------------------


def _rel(path: Path) -> str:
    """Repo-relative keys are always POSIX-style, on every platform."""
    return path.as_posix()


def generated_artifacts(root: Path) -> dict[str, str]:
    """Return ``{repo-relative path: content}`` for every generated file."""
    modules, edges, module_edges = collect_graph(root)
    return {
        _rel(ARCH_DIR / "module_deps.mmd"): render_module_deps(modules, edges),
        _rel(ARCH_DIR / "data_flow.mmd"): render_data_flow(),
        _rel(ARCH_DIR / "paper_loop_sequence.mmd"): render_paper_loop(),
        _rel(ARCH_DIR / "manifest.json"): json.dumps(
            {
                "schema_version": SCHEMA_VERSION,
                "generator": GENERATOR,
                "source_root": "src",
                "module_count": len(modules),
                "modules": sorted(modules),
                "package_edges": [
                    {"src": s, "dst": d, "imports": c} for (s, d), c in sorted(edges.items())
                ],
                "module_edges": [{"src": s, "dst": d} for (s, d) in sorted(module_edges)],
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
    }


def generated_blocks(artifacts: dict[str, str]) -> dict[str, str]:
    """Atlas-doc embed blocks keyed by marker name."""
    return {
        "module_deps": "```mermaid\n" + artifacts[_rel(ARCH_DIR / "module_deps.mmd")] + "```",
        "data_flow": "```mermaid\n" + artifacts[_rel(ARCH_DIR / "data_flow.mmd")] + "```",
        "paper_loop": "```mermaid\n"
        + artifacts[_rel(ARCH_DIR / "paper_loop_sequence.mmd")]
        + "```",
        "coverage": render_coverage(
            json.loads(artifacts[_rel(ARCH_DIR / "manifest.json")])["modules"],
            Counter(
                {
                    (e["src"], e["dst"]): e["imports"]
                    for e in json.loads(artifacts[_rel(ARCH_DIR / "manifest.json")])[
                        "package_edges"
                    ]
                }
            ),
        ),
    }


def splice_blocks(text: str, blocks: dict[str, str]) -> str:
    """Replace ``BEGIN/END GENERATED: name`` marker regions with fresh content."""
    out = text
    for name, body in blocks.items():
        begin = f"<!-- BEGIN GENERATED: {name} -->"
        end = f"<!-- END GENERATED: {name} -->"
        if out.count(begin) != 1 or out.count(end) != 1:
            raise ValueError(f"atlas doc requires one marker pair for {name!r}")
        i = out.find(begin)
        j = out.find(end)
        if i < 0 or j < 0 or j < i:
            raise ValueError(f"atlas doc is missing marker pair for {name!r}")
        out = out[: i + len(begin)] + "\n" + body + "\n" + out[j:]
    return out


def write_all(root: Path) -> list[str]:
    errors = verify_diagram_bindings(root)
    if errors:
        raise SystemExit("diagram binding verification failed:\n" + "\n".join(errors))
    artifacts = generated_artifacts(root)
    written: list[str] = []
    for rel, content in artifacts.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(rel)
    atlas = root / ATLAS_DOC
    if atlas.is_file():
        text = splice_blocks(atlas.read_text(encoding="utf-8"), generated_blocks(artifacts))
        atlas.write_text(text, encoding="utf-8")
        written.append(_rel(ATLAS_DOC))
    return written


def stale_artifacts(root: Path) -> list[str]:
    """Return sorted repo-relative paths whose committed bytes differ from fresh."""
    errors = verify_diagram_bindings(root)
    if errors:
        raise SystemExit("diagram binding verification failed:\n" + "\n".join(errors))
    artifacts = generated_artifacts(root)
    stale: list[str] = []
    for rel, content in artifacts.items():
        path = root / rel
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            stale.append(rel)
    atlas = root / ATLAS_DOC
    if atlas.is_file():
        try:
            expected = splice_blocks(atlas.read_text(encoding="utf-8"), generated_blocks(artifacts))
        except ValueError:
            stale.append(_rel(ATLAS_DOC))
        else:
            if atlas.read_text(encoding="utf-8") != expected:
                stale.append(_rel(ATLAS_DOC))
    else:
        stale.append(_rel(ATLAS_DOC))
    return sorted(stale)


def is_quant_fund_module(name: str) -> bool:
    return name == "quant_fund" or name.startswith("quant_fund.")


def is_fx1_module(name: str) -> bool:
    return name == "fx1" or name.startswith("fx1.")


def quant_fund_to_fx1_edges(module_edges: set[tuple[str, str]]) -> set[tuple[str, str]]:
    """Harness → model edges, including imports of ``fx1`` internals.

    A destination of exactly ``fx1`` is not enough: ``fx1.data.corpus`` is
    still a cross-root edge.
    """
    return {
        (src, dst) for src, dst in module_edges if is_quant_fund_module(src) and is_fx1_module(dst)
    }


def fx1_to_quant_fund_edges(module_edges: set[tuple[str, str]]) -> set[tuple[str, str]]:
    return {
        (src, dst) for src, dst in module_edges if is_fx1_module(src) and is_quant_fund_module(dst)
    }


# Measured boundary. ``--check`` does not compare these; the atlas unit test
# does, so adding or dropping an edge fails CI. ``quant_fund`` may import the
# ``fx1`` package root (the version re-export) and nothing under ``fx1.*``.
# ``fx1.forecast`` / ``fx1.eval`` may import only the harness modules below.
QUANT_FUND_TO_FX1_EDGES: frozenset[tuple[str, str]] = frozenset({("quant_fund", "fx1")})
FX1_TO_QUANT_FUND_EDGES: frozenset[tuple[str, str]] = frozenset(
    {
        ("fx1.eval.calibration_eval", "quant_fund.metrics.calibration_tests"),
        ("fx1.eval.options_reasoning_eval", "quant_fund.models.iv_approx"),
        ("fx1.eval.options_reasoning_eval", "quant_fund.models.options"),
        ("fx1.eval.rubric_banks", "quant_fund.metrics.conformal"),
        ("fx1.eval.rubric_banks", "quant_fund.metrics.scoring"),
        ("fx1.eval.ts_reasoning", "quant_fund.metrics.scoring"),
        ("fx1.forecast.core_audit", "quant_fund.data.adapters.synthetic"),
        ("fx1.forecast.core_audit", "quant_fund.schemas.errors"),
        ("fx1.forecast.data_audit", "quant_fund.schemas.errors"),
        ("fx1.forecast.dummy", "quant_fund.schemas.errors"),
        ("fx1.forecast.evaluate", "quant_fund.config.models"),
        ("fx1.forecast.evaluate", "quant_fund.metrics.direction"),
        ("fx1.forecast.evaluate", "quant_fund.metrics.returns"),
        ("fx1.forecast.evaluate", "quant_fund.metrics.scoring"),
        ("fx1.forecast.evaluate", "quant_fund.validation.walk_forward"),
        ("fx1.forecast.features", "quant_fund.data.point_in_time"),
        ("fx1.forecast.features", "quant_fund.schemas.errors"),
        ("fx1.forecast.runner", "quant_fund.data.adapters.parquet"),
        ("fx1.forecast.runner", "quant_fund.data.adapters.synthetic"),
        ("fx1.forecast.runner", "quant_fund.schemas.errors"),
        ("fx1.forecast.schema", "quant_fund.schemas.errors"),
        # --- audit/receipt seam (generated 2026-10-06) ---
        # Every fx1 *_audit module (plus sdk/api/serve/train/bench receipt
        # writers) seals evidence with the harness leaf utilities below.
        # All targets are inside the fx1-harness-surface allow_only
        # (configs/arch_boundaries.toml): utils leaf helpers + the receipt.v2
        # data-structure envelope. Regenerate with scripts/gen_arch_diagrams.py.
        ("fx1.bench.dip_audit", "quant_fund.utils.hashing"),
        ("fx1.bench.dip_audit", "quant_fund.utils.reproducibility"),
        ("fx1.bench.run", "quant_fund.utils.atomicio"),
        ("fx1.bench.run_audit", "quant_fund.utils.hashing"),
        ("fx1.bench.run_audit", "quant_fund.utils.reproducibility"),
        ("fx1.cli_audit", "quant_fund.utils.hashing"),
        ("fx1.cli_audit", "quant_fund.utils.reproducibility"),
        ("fx1.data.corpus_audit", "quant_fund.utils.hashing"),
        ("fx1.data.corpus_audit", "quant_fund.utils.reproducibility"),
        ("fx1.data.ledger_audit", "quant_fund.utils.hashing"),
        ("fx1.data.ledger_audit", "quant_fund.utils.reproducibility"),
        ("fx1.data.quality", "quant_fund.utils.atomicio"),
        ("fx1.data.quality_audit", "quant_fund.utils.hashing"),
        ("fx1.data.quality_audit", "quant_fund.utils.reproducibility"),
        ("fx1.data.receipts_audit", "quant_fund.utils.hashing"),
        ("fx1.data.receipts_audit", "quant_fund.utils.reproducibility"),
        ("fx1.data.sources.ds_audit", "quant_fund.utils.hashing"),
        ("fx1.data.sources.ds_audit", "quant_fund.utils.reproducibility"),
        ("fx1.data.sources_audit", "quant_fund.utils.hashing"),
        ("fx1.data.sources_audit", "quant_fund.utils.reproducibility"),
        ("fx1.doctor_audit", "quant_fund.utils.hashing"),
        ("fx1.doctor_audit", "quant_fund.utils.reproducibility"),
        ("fx1.eval.bank_audit", "quant_fund.utils.hashing"),
        ("fx1.eval.bank_audit", "quant_fund.utils.reproducibility"),
        ("fx1.eval.calibration_audit", "quant_fund.utils.hashing"),
        ("fx1.eval.calibration_audit", "quant_fund.utils.reproducibility"),
        ("fx1.eval.capability_audit", "quant_fund.utils.hashing"),
        ("fx1.eval.capability_audit", "quant_fund.utils.reproducibility"),
        ("fx1.eval.contamination_audit", "quant_fund.utils.hashing"),
        ("fx1.eval.contamination_audit", "quant_fund.utils.reproducibility"),
        ("fx1.eval.core_audit", "quant_fund.utils.hashing"),
        ("fx1.eval.core_audit", "quant_fund.utils.reproducibility"),
        ("fx1.eval.masking_audit", "quant_fund.utils.hashing"),
        ("fx1.eval.masking_audit", "quant_fund.utils.reproducibility"),
        ("fx1.eval.options_audit", "quant_fund.utils.hashing"),
        ("fx1.eval.options_audit", "quant_fund.utils.reproducibility"),
        ("fx1.eval.timepart_audit", "quant_fund.utils.hashing"),
        ("fx1.eval.timepart_audit", "quant_fund.utils.reproducibility"),
        ("fx1.eval.ts_reasoning_audit", "quant_fund.utils.hashing"),
        ("fx1.eval.ts_reasoning_audit", "quant_fund.utils.reproducibility"),
        ("fx1.ext_bench_audit", "quant_fund.utils.hashing"),
        ("fx1.ext_bench_audit", "quant_fund.utils.reproducibility"),
        ("fx1.forecast.artifacts", "quant_fund.utils.hashing"),
        ("fx1.forecast.core_audit", "quant_fund.utils.hashing"),
        ("fx1.forecast.core_audit", "quant_fund.utils.reproducibility"),
        ("fx1.forecast.data_audit", "quant_fund.utils.atomicio"),
        ("fx1.forecast.data_audit", "quant_fund.utils.hashing"),
        ("fx1.forecast.data_audit", "quant_fund.utils.reproducibility"),
        ("fx1.forecast.infra_audit", "quant_fund.utils.hashing"),
        ("fx1.forecast.infra_audit", "quant_fund.utils.reproducibility"),
        ("fx1.forecast.runner", "quant_fund.utils.hashing"),
        ("fx1.harness_audit", "quant_fund.utils.hashing"),
        ("fx1.harness_audit", "quant_fund.utils.reproducibility"),
        ("fx1.honesty_audit", "quant_fund.utils.hashing"),
        ("fx1.honesty_audit", "quant_fund.utils.reproducibility"),
        ("fx1.hypotheses_audit", "quant_fund.utils.hashing"),
        ("fx1.hypotheses_audit", "quant_fund.utils.reproducibility"),
        ("fx1.modelcard_audit", "quant_fund.utils.hashing"),
        ("fx1.modelcard_audit", "quant_fund.utils.reproducibility"),
        ("fx1.mrm", "quant_fund.utils.atomicio"),
        ("fx1.mrm_audit", "quant_fund.utils.hashing"),
        ("fx1.mrm_audit", "quant_fund.utils.reproducibility"),
        ("fx1.reward_audit", "quant_fund.utils.hashing"),
        ("fx1.reward_audit", "quant_fund.utils.reproducibility"),
        ("fx1.rt_audit", "quant_fund.utils.hashing"),
        ("fx1.rt_audit", "quant_fund.utils.reproducibility"),
        ("fx1.rubric_audit", "quant_fund.utils.hashing"),
        ("fx1.rubric_audit", "quant_fund.utils.reproducibility"),
        ("fx1.sbom_audit", "quant_fund.utils.hashing"),
        ("fx1.sbom_audit", "quant_fund.utils.reproducibility"),
        ("fx1.sdk", "quant_fund.research.receipt_v2"),
        ("fx1.sdk_audit", "quant_fund.research.receipt_v2"),
        ("fx1.sdk_audit", "quant_fund.utils.hashing"),
        ("fx1.sdk_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.anthropic_sdk_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.anthropic_sdk_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.api", "quant_fund.research.receipt_v2"),
        ("fx1.serve.api_audit", "quant_fund.research.receipt_v2"),
        ("fx1.serve.api_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.api_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.attestation_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.attestation_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.auth_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.auth_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.batch_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.batch_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.byok_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.byok_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.client_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.client_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.contract_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.contract_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.conv_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.conv_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.drain_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.e2e_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.e2e_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.eval_lifecycle_audit", "quant_fund.research.receipt_v2"),
        ("fx1.serve.eval_lifecycle_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.eval_lifecycle_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.fault_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.fault_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.files_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.files_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.header_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.header_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.idem_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.idem_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.jobs_audit", "quant_fund.research.receipt_v2"),
        ("fx1.serve.journal_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.journal_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.models_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.models_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.oai_sdk_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.oai_sdk_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.observe_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.observe_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.ops_receipt", "quant_fund.utils.hashing"),
        ("fx1.serve.ops_receipt", "quant_fund.utils.reproducibility"),
        ("fx1.serve.parity_audit", "quant_fund.research.receipt_v2"),
        ("fx1.serve.parity_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.parity_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.perf_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.perf_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.quota2_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.quota2_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.quota_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.quota_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.retrieval_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.retrieval_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.serve_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.serve_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.spec_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.spec_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.stream_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.stream_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.tenancy_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.tenancy_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.uploads_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.uploads_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.usage_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.usage_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.vs_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.vs_audit", "quant_fund.utils.reproducibility"),
        ("fx1.serve.webhook_audit", "quant_fund.utils.hashing"),
        ("fx1.serve.webhook_audit", "quant_fund.utils.reproducibility"),
        ("fx1.tail_audit", "quant_fund.utils.hashing"),
        ("fx1.tail_audit", "quant_fund.utils.reproducibility"),
        ("fx1.train.infra_audit", "quant_fund.utils.hashing"),
        ("fx1.train.infra_audit", "quant_fund.utils.reproducibility"),
        ("fx1.train.pipeline", "quant_fund.utils.atomicio"),
        ("fx1.train.pipeline_audit", "quant_fund.utils.hashing"),
        ("fx1.train.pipeline_audit", "quant_fund.utils.reproducibility"),
        ("fx1.train.receipts", "quant_fund.utils.atomicio"),
        ("fx1.train.receipts_audit", "quant_fund.utils.hashing"),
        ("fx1.train.receipts_audit", "quant_fund.utils.reproducibility"),
        ("fx1.train.run", "quant_fund.utils.atomicio"),
        ("fx1.train.run_audit", "quant_fund.utils.hashing"),
        ("fx1.train.run_audit", "quant_fund.utils.reproducibility"),
    }
)


def cross_root_errors(module_edges: set[tuple[str, str]]) -> list[str]:
    """Empty when ``module_edges`` matches the pinned cross-root boundary."""
    errors: list[str] = []
    harness_to_model = quant_fund_to_fx1_edges(module_edges)
    if harness_to_model != QUANT_FUND_TO_FX1_EDGES:
        rendered = ", ".join(f"{src} -> {dst}" for src, dst in sorted(harness_to_model))
        errors.append(f"quant_fund→fx1 edges drifted from the version re-export pin: {rendered}")
    model_to_harness = fx1_to_quant_fund_edges(module_edges)
    if model_to_harness != FX1_TO_QUANT_FUND_EDGES:
        rendered = ", ".join(f"{src} -> {dst}" for src, dst in sorted(model_to_harness))
        errors.append(f"fx1→quant_fund edges drifted from the forecast/eval pin: {rendered}")
    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="verify committed artifacts are fresh")
    parser.add_argument("--stats", action="store_true", help="print scan stats as JSON")
    parser.add_argument(
        "--root", type=Path, default=None, help="repo root (default: script parent)"
    )
    args = parser.parse_args(argv)
    root = (args.root or repo_root()).resolve()

    if args.stats:
        modules, edges, module_edges = collect_graph(root)
        print(
            json.dumps(
                {
                    "modules": len(modules),
                    "packages": len({package_of(m) for m in modules}),
                    "cross_package_edges": sum(1 for (s, d) in edges if s != d),
                    "module_edges": len(module_edges),
                    "distinct_imports": sum(edges.values()),
                },
                sort_keys=True,
            )
        )
        return 0

    if args.check:
        stale = stale_artifacts(root)
        if stale:
            print("stale architecture artifacts — run `python scripts/gen_arch_diagrams.py`:")
            for rel in stale:
                print(f"  {rel}")
            return 1
        print("architecture diagrams are fresh")
        return 0

    written = write_all(root)
    for rel in written:
        print(f"wrote {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
