#!/usr/bin/env python3
"""Self-contained AST mutation-testing harness (stdlib only; no mutmut/cosmic-ray).

Implements the SOTA roadmap §2.4 item 6 lane: mutation testing on the research
verification layer (``src/quant_fund/research/verify.py`` / ``catalog``). The
harness parses a target module with :mod:`ast`, applies a documented operator
set, and for each mutant overlays the mutated source into the pytest
subprocess's import system **without ever touching the working tree**.

Operator set (each mutant applies exactly one edit to a fresh parse):

* ``comparison-swap`` — ``<``↔``<=``/``>``, ``<=``→``<``/``>=``, ``>``→``>=``/``<``,
  ``>=``→``>``/``<=``, ``==``↔``!=``, ``is``↔``is not``, ``in``↔``not in``.
* ``boolop-swap`` — ``and``↔``or`` on every ``BoolOp``.
* ``numeric-perturb`` — integer constant ``n`` → ``n + 1``; float ``x`` → ``x + 1.0``.
* ``const-bool-flip`` — ``True``↔``False`` constants.
* ``negation-insertion`` — ``if/while/elif/ternary/assert`` test ``t`` → ``not t``.
* ``negation-removal`` — same sites where the test is already ``not t`` → ``t``.

Overlay mechanism: the mutated module is written to a temp dir together with a
generated ``sitecustomize.py`` that installs a ``sys.meta_path`` finder
redirecting exactly one fully-qualified module name to the mutated file.
``sitecustomize`` runs at interpreter startup (before pytest and any
``conftest.py`` can reorder ``sys.path``), and a meta-path finder wins over
path-based resolution — so the overlay is immune to the repo's editable-install
``.pth`` and the root ``conftest.py`` ``sys.path.insert`` of ``src/``.

Fail-closed rules (refuse to run, exit code 2):

* target file missing, not ``.py``, not inside the repo, or not part of an
  importable package (no ``__init__.py`` in its directory);
* pytest selector list empty, blank, option-like (``-`` prefix), or pointing
  outside the repo;
* baseline run (unmutated overlay) does not pass;
* sentinel run (overlay module replaced by a top-level ``raise``) does not
  fail — proves the overlay actually redirects imports *and* that the chosen
  test subset imports the target module at all;
* zero mutants generated, or ``--max-mutants`` < 1, or ``--timeout`` <= 0.

Verdicts per mutant: pytest exit 0 = ``survived``; 1/2/4 (test failures,
collection errors, or a conftest ImportError crash — the baseline run proves
the command line itself is valid, so a 4 during the campaign means the mutant
broke startup imports) = ``killed``; timeout = ``timeout``; 3/5 (pytest
internal error / no tests collected) = ``error`` (harness problem, excluded
from scoring, fails the run closed). Mutation score =
``(killed + timeout) / (sampled - error)``.

Sampling: all mutants are enumerated deterministically (``ast.walk`` order),
then ``--max-mutants`` caps the campaign via a seeded ``random.Random`` sample
(reproducible for a given ``--seed``).

Usage:
    python scripts/mutation_test.py --target src/quant_fund/research/verify.py \
        --pytest tests/unit/research/test_verify_cov.py \
        --max-mutants 20 --seed 7 --json-out /tmp/mutation_report.json
    python scripts/mutation_test.py --target ... --pytest ... --list-mutants

A mutation score is a test-suite diagnostic, not market evidence; no live-PnL
claim.
"""

from __future__ import annotations

import argparse
import ast
import json
import os
import random
import subprocess
import sys
import tempfile
import time
from collections.abc import Callable, Sequence
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from functools import partial
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[1]
WATERMARK = "test-suite diagnostic; not market evidence; no live-PnL claim"

DEFAULT_TIMEOUT_S = 120.0
DEFAULT_MAX_MUTANTS = 50
DEFAULT_SEED = 0
_OUTPUT_TAIL_LINES = 20

# Documented comparison-operator replacement table (values are constructor
# callables so each mutant builds a fresh operator node).
COMPARISON_SWAPS: dict[type[ast.cmpop], tuple[type[ast.cmpop], ...]] = {
    ast.Lt: (ast.LtE, ast.Gt),
    ast.LtE: (ast.Lt, ast.GtE),
    ast.Gt: (ast.GtE, ast.Lt),
    ast.GtE: (ast.Gt, ast.LtE),
    ast.Eq: (ast.NotEq,),
    ast.NotEq: (ast.Eq,),
    ast.Is: (ast.IsNot,),
    ast.IsNot: (ast.Is,),
    ast.In: (ast.NotIn,),
    ast.NotIn: (ast.In,),
}

# Negation operator sites ("simple conditions" per the lane spec).
_NEGATION_SITES = (ast.If, ast.While, ast.IfExp, ast.Assert)

SENTINEL_MARKER = "mutation-overlay-sentinel"
SENTINEL_SOURCE = f'raise RuntimeError("{SENTINEL_MARKER}")\n'

SITECUSTOMIZE_SOURCE = '''\
"""Mutation-overlay import hook (generated by scripts/mutation_test.py).

Loaded at interpreter startup via PYTHONPATH. Redirects exactly one module --
os.environ["MUTATION_TARGET_MODULE"] -- to the mutated source file at
os.environ["MUTATION_TARGET_FILE"]. Everything else imports normally.
"""

import os
import sys
from importlib.util import spec_from_file_location

_MODULE = os.environ.get("MUTATION_TARGET_MODULE", "")
_FILE = os.environ.get("MUTATION_TARGET_FILE", "")


class _MutationOverlayFinder:
    def find_spec(self, fullname, path=None, target=None):
        if _MODULE and _FILE and fullname == _MODULE:
            return spec_from_file_location(fullname, _FILE)
        return None


if _MODULE and _FILE:
    sys.meta_path.insert(0, _MutationOverlayFinder())
'''


class MutationTestError(ValueError):
    """A fail-closed precondition of the mutation campaign is violated."""


@dataclass(frozen=True)
class Mutant:
    """One candidate mutation of the target source."""

    mutant_id: str
    operator: str
    lineno: int
    description: str
    source: str


@dataclass(frozen=True)
class RunOutcome:
    """Result of one pytest (or stub) invocation."""

    returncode: int | None  # None means the process timed out
    duration_s: float
    output_tail: str = ""


@dataclass(frozen=True)
class MutantResult:
    """Bookkeeping row for one executed mutant."""

    mutant_id: str
    operator: str
    lineno: int
    description: str
    status: str  # killed | survived | timeout | error
    returncode: int | None
    duration_s: float


@dataclass
class CampaignReport:
    """Aggregate campaign outcome serialized to JSON."""

    created_utc: str
    target: str
    module: str
    selectors: tuple[str, ...]
    seed: int
    timeout_s: float
    total_mutants: int
    sampled: int
    counts: dict[str, int] = field(default_factory=dict)
    score: float = 0.0
    min_score: float | None = None
    watermark: str = WATERMARK
    results: list[dict[str, object]] = field(default_factory=list)
    survivors: list[dict[str, object]] = field(default_factory=list)


Runner = Callable[[list[str], Path, dict[str, str], float], RunOutcome]


# ---------------------------------------------------------------------------
# AST operators
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class _Spec:
    """A pending single-node edit, with closures bound to one parsed tree."""

    operator: str
    lineno: int
    description: str
    apply: Callable[[], None]


def _swap_compare_op(node: ast.Compare, position: int, replacement: type[ast.cmpop]) -> None:
    node.ops[position] = replacement()


def _swap_boolop(node: ast.BoolOp, replacement: type[ast.boolop]) -> None:
    node.op = replacement()


def _set_constant(node: ast.Constant, value: Any) -> None:
    node.value = value


def _insert_negation(node: ast.If | ast.While | ast.IfExp | ast.Assert, test: ast.expr) -> None:
    node.test = ast.UnaryOp(op=ast.Not(), operand=test)


def _remove_negation(node: ast.If | ast.While | ast.IfExp | ast.Assert, inner: ast.expr) -> None:
    node.test = inner


def _collect_specs(tree: ast.AST) -> list[_Spec]:
    """Enumerate every single-edit mutation of *tree* in deterministic order.

    ``ast.walk`` is breadth-first over a stable child order, so re-parsing the
    same source reproduces the same spec list index-for-index; materializing
    mutant *i* re-parses and applies spec *i* on the fresh tree.
    """
    specs: list[_Spec] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Compare):
            for position, op in enumerate(node.ops):
                for replacement in COMPARISON_SWAPS.get(type(op), ()):
                    name = f"{type(op).__name__}->{replacement.__name__}"
                    specs.append(
                        _Spec(
                            operator="comparison-swap",
                            lineno=node.lineno,
                            description=f"{name} (line {node.lineno})",
                            apply=partial(_swap_compare_op, node, position, replacement),
                        )
                    )
        elif isinstance(node, ast.BoolOp):
            bool_replacement: type[ast.boolop] = ast.Or if isinstance(node.op, ast.And) else ast.And
            name = f"{type(node.op).__name__}->{bool_replacement.__name__}"
            specs.append(
                _Spec(
                    operator="boolop-swap",
                    lineno=node.lineno,
                    description=f"{name} (line {node.lineno})",
                    apply=partial(_swap_boolop, node, bool_replacement),
                )
            )
        elif isinstance(node, ast.Constant):
            value = node.value
            if isinstance(value, bool):
                specs.append(
                    _Spec(
                        operator="const-bool-flip",
                        lineno=node.lineno,
                        description=f"{value}->{not value} (line {node.lineno})",
                        apply=partial(_set_constant, node, not value),
                    )
                )
            elif isinstance(value, int):
                specs.append(
                    _Spec(
                        operator="numeric-perturb",
                        lineno=node.lineno,
                        description=f"int {value}->{value + 1} (line {node.lineno})",
                        apply=partial(_set_constant, node, value + 1),
                    )
                )
            elif isinstance(value, float):
                specs.append(
                    _Spec(
                        operator="numeric-perturb",
                        lineno=node.lineno,
                        description=f"float {value}->{value + 1.0} (line {node.lineno})",
                        apply=partial(_set_constant, node, value + 1.0),
                    )
                )
        elif isinstance(node, _NEGATION_SITES):
            test = node.test
            if isinstance(test, ast.UnaryOp) and isinstance(test.op, ast.Not):
                specs.append(
                    _Spec(
                        operator="negation-removal",
                        lineno=node.lineno,
                        description=f"drop `not` from test (line {node.lineno})",
                        apply=partial(_remove_negation, node, test.operand),
                    )
                )
            else:
                specs.append(
                    _Spec(
                        operator="negation-insertion",
                        lineno=node.lineno,
                        description=f"insert `not` into test (line {node.lineno})",
                        apply=partial(_insert_negation, node, test),
                    )
                )
    return specs


def generate_mutants(source: str, filename: str = "<target>") -> list[Mutant]:
    """Materialize every single-edit mutant of *source* (deterministic order)."""
    try:
        tree = ast.parse(source, filename=filename)
    except SyntaxError as exc:
        raise MutationTestError(f"{filename}: target does not parse: {exc}") from exc
    specs = _collect_specs(tree)
    mutants: list[Mutant] = []
    for index, spec in enumerate(specs):
        fresh = ast.parse(source, filename=filename)
        fresh_specs = _collect_specs(fresh)
        fresh_specs[index].apply()
        mutated = ast.unparse(fresh)
        try:
            compile(mutated, filename, "exec")
        except SyntaxError as exc:  # pragma: no cover - unparse of a valid AST
            raise MutationTestError(f"mutant M{index:04d} does not compile: {exc}") from exc
        mutants.append(
            Mutant(
                mutant_id=f"M{index:04d}",
                operator=spec.operator,
                lineno=spec.lineno,
                description=spec.description,
                source=mutated,
            )
        )
    return mutants


def sample_mutants(mutants: Sequence[Mutant], max_mutants: int, seed: int) -> list[Mutant]:
    """Cap the campaign at *max_mutants* via a seeded sample (order preserved)."""
    if max_mutants < 1:
        raise MutationTestError(f"--max-mutants must be >= 1, got {max_mutants}")
    if len(mutants) <= max_mutants:
        return list(mutants)
    picks = sorted(random.Random(seed).sample(range(len(mutants)), max_mutants))
    return [mutants[i] for i in picks]


# ---------------------------------------------------------------------------
# Fail-closed validation
# ---------------------------------------------------------------------------


def resolve_target(target: str | Path, repo: Path = REPO) -> Path:
    """Validate the target file and return its resolved path."""
    repo_root = repo.resolve()
    path = Path(target)
    if not path.is_absolute():
        path = repo_root / path
    resolved = path.resolve()
    if not resolved.is_file():
        raise MutationTestError(f"target does not exist or is not a file: {resolved}")
    if resolved.suffix != ".py":
        raise MutationTestError(f"target must be a .py file: {resolved}")
    if repo_root not in resolved.parents:
        raise MutationTestError(f"target is outside the repo ({repo_root}): {resolved}")
    if not (resolved.parent / "__init__.py").is_file():
        raise MutationTestError(
            f"target is not part of an importable package (no __init__.py in {resolved.parent})"
        )
    return resolved


def module_name_for(target: Path) -> str:
    """Dotted module name for *target* (walks up while ``__init__.py`` exists)."""
    parts = [target.stem]
    parent = target.parent
    while (parent / "__init__.py").is_file():
        parts.append(parent.name)
        parent = parent.parent
    if len(parts) == 1:
        raise MutationTestError(f"target is not inside a package: {target}")
    return ".".join(reversed(parts))


def validate_selectors(selectors: Sequence[str], repo: Path = REPO) -> tuple[str, ...]:
    """Validate pytest selectors; refuse empty or option-like/injection inputs."""
    if not selectors:
        raise MutationTestError("pytest selector list is empty; pass at least one --pytest target")
    repo_root = repo.resolve()
    cleaned: list[str] = []
    for selector in selectors:
        if not isinstance(selector, str) or not selector.strip():
            raise MutationTestError(f"pytest selector must be a non-empty string: {selector!r}")
        text = selector.strip()
        if text.startswith("-"):
            raise MutationTestError(f"pytest selector must not look like an option: {text!r}")
        path_part = text.split("::", 1)[0]
        candidate = Path(path_part)
        if not candidate.is_absolute():
            candidate = repo_root / candidate
        try:
            resolved = candidate.resolve()
        except OSError as exc:
            raise MutationTestError(f"unreadable pytest selector path {text!r}: {exc}") from exc
        if repo_root != resolved and repo_root not in resolved.parents:
            raise MutationTestError(f"pytest selector points outside the repo: {text!r}")
        cleaned.append(text)
    return tuple(cleaned)


# ---------------------------------------------------------------------------
# Overlay + subprocess runner
# ---------------------------------------------------------------------------


def write_overlay(overlay_dir: Path, module_source: str) -> Path:
    """Write ``sitecustomize.py`` + ``mutant_module.py``; return the mutant path."""
    overlay_dir.mkdir(parents=True, exist_ok=True)
    (overlay_dir / "sitecustomize.py").write_text(SITECUSTOMIZE_SOURCE, encoding="utf-8")
    mutant_file = overlay_dir / "mutant_module.py"
    mutant_file.write_text(module_source, encoding="utf-8")
    return mutant_file


def overlay_env(
    overlay_dir: Path,
    module_name: str,
    mutant_file: Path,
    base_env: os._Environ[str] | dict[str, str] | None = None,
) -> dict[str, str]:
    """Subprocess env: overlay first on PYTHONPATH + redirect env vars."""
    env = dict(os.environ if base_env is None else base_env)
    existing = env.get("PYTHONPATH", "")
    env["PYTHONPATH"] = f"{overlay_dir}{os.pathsep}{existing}" if existing else str(overlay_dir)
    env["MUTATION_TARGET_MODULE"] = module_name
    env["MUTATION_TARGET_FILE"] = str(mutant_file)
    # Never let an ambient coverage subprocess hook pollute campaign runs.
    env.pop("COVERAGE_PROCESS_START", None)
    env.pop("COVERAGE_PROCESS_CONFIG", None)
    return env


def build_command(selectors: Sequence[str]) -> list[str]:
    """Pytest command for one campaign run (fail-fast, no cache writes)."""
    return [
        sys.executable,
        "-m",
        "pytest",
        "-x",
        "-q",
        "--no-header",
        "-p",
        "no:cacheprovider",
        *selectors,
    ]


def _tail(text: str, lines: int = _OUTPUT_TAIL_LINES) -> str:
    stripped = text.strip()
    if not stripped:
        return ""
    return "\n".join(stripped.splitlines()[-lines:])


def default_runner(
    command: list[str], cwd: Path, env: dict[str, str], timeout_s: float
) -> RunOutcome:
    """Real subprocess runner with a hard timeout."""
    start = time.perf_counter()
    try:
        completed = subprocess.run(
            command,
            cwd=cwd,
            env=env,
            timeout=timeout_s,
            capture_output=True,
            text=True,
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        partial = exc.stdout
        tail = _tail(
            partial.decode("utf-8", "replace") if isinstance(partial, bytes) else partial or ""
        )
        return RunOutcome(returncode=None, duration_s=time.perf_counter() - start, output_tail=tail)
    output = _tail(f"{completed.stdout}\n{completed.stderr}")
    return RunOutcome(
        returncode=completed.returncode,
        duration_s=time.perf_counter() - start,
        output_tail=output,
    )


def classify(returncode: int | None) -> str:
    """Map a pytest exit code onto a mutant verdict (see module docstring).

    Exit 4 (usage error / conftest ImportError) counts as ``killed``: the
    preflight baseline proved the command line is valid, so a 4 during the
    campaign means the mutated module crashed pytest's startup imports (this
    repo's ``tests/conftest.py`` eagerly imports the research layer). 3/5 stay
    ``error``: genuinely ambiguous harness states.
    """
    if returncode is None:
        return "timeout"
    if returncode == 0:
        return "survived"
    if returncode in (1, 2, 4):
        return "killed"
    return "error"


def _preflight(
    selectors: Sequence[str],
    repo: Path,
    overlay_dir: Path,
    module_name: str,
    original_source: str,
    timeout_s: float,
    runner: Runner,
) -> None:
    """Fail closed unless the baseline passes and the sentinel is killed."""
    command = build_command(selectors)

    mutant_file = write_overlay(overlay_dir, original_source)
    env = overlay_env(overlay_dir, module_name, mutant_file)
    outcome = runner(command, repo, env, timeout_s)
    status = classify(outcome.returncode)
    if status != "survived":
        raise MutationTestError(
            f"baseline pytest run did not pass ({status}, rc={outcome.returncode}); "
            f"refusing to mutate against a red suite.\n--- output tail ---\n{outcome.output_tail}"
        )

    mutant_file = write_overlay(overlay_dir, SENTINEL_SOURCE)
    env = overlay_env(overlay_dir, module_name, mutant_file)
    outcome = runner(command, repo, env, timeout_s)
    status = classify(outcome.returncode)
    if status != "killed":
        raise MutationTestError(
            f"sentinel overlay was not killed ({status}, rc={outcome.returncode}); the overlay "
            "did not redirect imports, or the pytest selector never imports the target module. "
            f"Refusing to run.\n--- output tail ---\n{outcome.output_tail}"
        )


def run_campaign(
    mutants: Sequence[Mutant],
    selectors: Sequence[str],
    repo: Path,
    overlay_dir: Path,
    module_name: str,
    timeout_s: float,
    runner: Runner | None = None,
    original_source: str | None = None,
    preflight: bool = True,
) -> list[MutantResult]:
    """Run every mutant through the pytest subset, recording verdicts."""
    if runner is None:  # late-bound so tests can monkeypatch default_runner
        runner = default_runner
    command = build_command(selectors)
    if preflight:
        if original_source is None:
            raise MutationTestError("preflight requires original_source")
        _preflight(selectors, repo, overlay_dir, module_name, original_source, timeout_s, runner)
    results: list[MutantResult] = []
    for mutant in mutants:
        mutant_file = write_overlay(overlay_dir, mutant.source)
        env = overlay_env(overlay_dir, module_name, mutant_file)
        outcome = runner(command, repo, env, timeout_s)
        results.append(
            MutantResult(
                mutant_id=mutant.mutant_id,
                operator=mutant.operator,
                lineno=mutant.lineno,
                description=mutant.description,
                status=classify(outcome.returncode),
                returncode=outcome.returncode,
                duration_s=round(outcome.duration_s, 3),
            )
        )
    return results


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------


def build_report(
    target: Path,
    module_name: str,
    selectors: Sequence[str],
    seed: int,
    timeout_s: float,
    total_mutants: int,
    results: Sequence[MutantResult],
    min_score: float | None = None,
) -> CampaignReport:
    """Aggregate results into a report; score = (killed+timeout)/(sampled-error)."""
    counts = {"killed": 0, "survived": 0, "timeout": 0, "error": 0}
    for result in results:
        counts[result.status] += 1
    attempted = len(results) - counts["error"]
    score = (counts["killed"] + counts["timeout"]) / attempted if attempted else 0.0
    rows = [asdict(result) for result in results]
    return CampaignReport(
        created_utc=datetime.now(UTC).isoformat(),
        target=str(target),
        module=module_name,
        selectors=tuple(selectors),
        seed=seed,
        timeout_s=timeout_s,
        total_mutants=total_mutants,
        sampled=len(results),
        counts=counts,
        score=round(score, 4),
        min_score=min_score,
        results=rows,
        survivors=[row for row in rows if row["status"] == "survived"],
    )


def report_to_dict(report: CampaignReport) -> dict[str, object]:
    payload = asdict(report)
    payload["selectors"] = list(report.selectors)
    return payload


def format_summary(report: CampaignReport) -> str:
    counts = report.counts
    lines = [
        f"target: {report.target} ({report.module})",
        f"selectors: {' '.join(report.selectors)}",
        f"mutants: {report.total_mutants} available, {report.sampled} sampled "
        f"(seed={report.seed}, max-mutants cap)",
        f"killed={counts['killed']} survived={counts['survived']} "
        f"timeout={counts['timeout']} error={counts['error']}",
        f"mutation score: {report.score:.2%}  [(killed+timeout)/(sampled-error)]",
    ]
    if report.survivors:
        lines.append("survivors:")
        for row in report.survivors:
            lines.append(
                f"  {row['mutant_id']} line {row['lineno']}: "
                f"[{row['operator']}] {row['description']}"
            )
    if report.min_score is not None:
        lines.append(
            "min-score gate: "
            + ("PASS" if report.score >= report.min_score else "FAIL")
            + f" (>= {report.min_score:.2%})"
        )
    lines.append(WATERMARK)
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: Sequence[str] | None = None, *, repo: Path = REPO) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--target", required=True, help="Python file to mutate (must live inside the repo)"
    )
    parser.add_argument(
        "--pytest",
        action="append",
        default=[],
        dest="selectors",
        help="pytest selector (path or path::nodeid) for the killing subset; repeatable",
    )
    parser.add_argument("--max-mutants", type=int, default=DEFAULT_MAX_MUTANTS)
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    parser.add_argument("--timeout", type=float, default=DEFAULT_TIMEOUT_S, help="per-run seconds")
    parser.add_argument("--json-out", type=Path, default=None)
    parser.add_argument(
        "--min-score",
        type=float,
        default=None,
        help="optional gate in [0, 1]; exit 1 when the mutation score is below it",
    )
    parser.add_argument(
        "--list-mutants",
        action="store_true",
        help="enumerate mutants and exit without running pytest",
    )
    args = parser.parse_args(argv)

    try:
        if args.timeout <= 0:
            raise MutationTestError(f"--timeout must be > 0, got {args.timeout}")
        if args.max_mutants < 1:
            raise MutationTestError(f"--max-mutants must be >= 1, got {args.max_mutants}")
        if args.min_score is not None and not 0.0 <= args.min_score <= 1.0:
            raise MutationTestError(f"--min-score must be in [0, 1], got {args.min_score}")
        if not args.list_mutants:
            validate_selectors(args.selectors, repo)
        target = resolve_target(args.target, repo)
        module_name = module_name_for(target)
        source = target.read_text(encoding="utf-8")
        mutants = generate_mutants(source, filename=str(target))
        if not mutants:
            raise MutationTestError(f"{target}: no mutants generated; refusing to run")
        sampled = sample_mutants(mutants, args.max_mutants, args.seed)

        if args.list_mutants:
            print(f"{target} ({module_name}): {len(mutants)} mutants available")
            for mutant in sampled:
                print(
                    f"  {mutant.mutant_id} line {mutant.lineno}: "
                    f"[{mutant.operator}] {mutant.description}"
                )
            return 0

        with tempfile.TemporaryDirectory(prefix="mutation-overlay-") as tmp:
            overlay_dir = Path(tmp) / "overlay"
            results = run_campaign(
                sampled,
                args.selectors,
                repo=repo,
                overlay_dir=overlay_dir,
                module_name=module_name,
                timeout_s=args.timeout,
                original_source=source,
            )
        report = build_report(
            target,
            module_name,
            tuple(args.selectors),
            args.seed,
            args.timeout,
            len(mutants),
            results,
            min_score=args.min_score,
        )
        print(format_summary(report))
        if args.json_out is not None:
            args.json_out.parent.mkdir(parents=True, exist_ok=True)
            args.json_out.write_text(
                json.dumps(report_to_dict(report), indent=2) + "\n", encoding="utf-8"
            )
            print(f"wrote {args.json_out}")
        if report.counts["error"] > 0:
            print(
                f"error: {report.counts['error']} mutant run(s) hit pytest internal/usage "
                "errors; failing closed",
                file=sys.stderr,
            )
            return 2
        if args.min_score is not None and report.score < args.min_score:
            return 1
        return 0
    except (MutationTestError, OSError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
