/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artifacts */
        get: operations["list_artifacts_artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Receipts */
        get: operations["list_receipts_receipts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/by-hash/{digest}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Receipt By Hash */
        get: operations["get_receipt_by_hash_receipts_by_hash__digest__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/{receipt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Receipt */
        get: operations["get_receipt_receipts__receipt_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/{receipt_id}/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify Receipt */
        get: operations["verify_receipt_receipts__receipt_id__verification_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Results */
        get: operations["list_results_results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/{kind}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Result */
        get: operations["get_result_results__kind___name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/{kind}/{name}/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify Result */
        get: operations["verify_result_results__kind___name__verification_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Run */
        get: operations["latest_run_runs_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/markdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Markdown */
        get: operations["get_run_markdown_runs__run_id__markdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify Run */
        get: operations["verify_run_runs__run_id__verification_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verifier/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Verifier Runs */
        get: operations["list_verifier_runs_verifier_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verifier/runs/{run_log_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Verifier Run */
        get: operations["get_verifier_run_verifier_runs__run_log_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verifier/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Verifier Versions */
        get: operations["list_verifier_versions_verifier_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verifier/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Verifier Version */
        get: operations["get_verifier_version_verifier_versions__version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactDetail */
        ArtifactDetail: {
            /** Artifact */
            artifact: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Path */
            path: string;
            /** Sha256 */
            sha256: string;
        };
        /** ArtifactListResponse */
        ArtifactListResponse: {
            /**
             * Claim
             * @default research_only
             * @constant
             */
            claim: "research_only";
            /** Items */
            items: components["schemas"]["ArtifactSummary"][];
            /** Total */
            total: number;
        };
        /**
         * ArtifactSummary
         * @description One committed ``artifacts/**\/*.json`` research artifact.
         */
        ArtifactSummary: {
            /** Id */
            id: string;
            /** Parse Error */
            parse_error?: string | null;
            /** Path */
            path: string;
            /** Schema Tag */
            schema_tag: string | null;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Artifacts Dir Present */
            artifacts_dir_present: boolean;
            /**
             * Claim
             * @default research_only
             * @constant
             */
            claim: "research_only";
            /** Data Root Present */
            data_root_present: boolean;
            /**
             * Firm
             * @default Artificial Hedge
             */
            firm: string;
            /**
             * Mode
             * @default read_only
             * @constant
             */
            mode: "read_only";
            /** Receipts Dir Present */
            receipts_dir_present: boolean;
            /**
             * Service
             * @default dipcatcher-research-api
             */
            service: string;
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Verifier Dir Present */
            verifier_dir_present: boolean;
            /**
             * Version
             * @default 0.4.0
             */
            version: string;
        };
        /** ReceiptDetail */
        ReceiptDetail: {
            /** Filename */
            filename: string;
            /** Id */
            id: string;
            /** Receipt */
            receipt: {
                [key: string]: unknown;
            };
            /** Schema Tag */
            schema_tag: string | null;
            /** Sha256 */
            sha256: string;
        };
        /** ReceiptListResponse */
        ReceiptListResponse: {
            /**
             * Claim
             * @default research_only
             * @constant
             */
            claim: "research_only";
            /** Items */
            items: components["schemas"]["ReceiptSummary"][];
            /** Total */
            total: number;
        };
        /**
         * ReceiptSummary
         * @description Summary of one committed ``receipts/*.json`` evidence document.
         */
        ReceiptSummary: {
            /** Filename */
            filename: string;
            /** Generated At */
            generated_at: string | null;
            /** Id */
            id: string;
            /** Live Pnl Claim */
            live_pnl_claim: boolean | null;
            /** Parse Error */
            parse_error?: string | null;
            /** Research Only */
            research_only: boolean | null;
            /** Schema Tag */
            schema_tag: string | null;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** ResultDetail */
        ResultDetail: {
            /** Files */
            files: components["schemas"]["ResultFile"][];
            /** Kind */
            kind: string;
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            } | null;
            /** Manifest Sha256 */
            manifest_sha256: string | null;
            /** Name */
            name: string;
            /** Path */
            path: string;
        };
        /**
         * ResultFile
         * @description One file inside a sealed benchmark run directory.
         */
        ResultFile: {
            /** Compressed */
            compressed: boolean;
            /** Name */
            name: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** ResultListResponse */
        ResultListResponse: {
            /**
             * Claim
             * @default research_only
             * @constant
             */
            claim: "research_only";
            /** Items */
            items: components["schemas"]["ResultSummary"][];
            /** Total */
            total: number;
        };
        /**
         * ResultSummary
         * @description A ``<data_root>/metadata/<kind>/<name>/`` sealed run directory.
         */
        ResultSummary: {
            /** Created At */
            created_at: string | null;
            /** Has Manifest */
            has_manifest: boolean;
            /** Has Test */
            has_test: boolean;
            /** Has Validation */
            has_validation: boolean;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Path */
            path: string;
        };
        /** RunDetail */
        RunDetail: {
            /** Receipt */
            receipt: {
                [key: string]: unknown;
            };
            /** Run Id */
            run_id: string;
            /** Sha256 */
            sha256: string;
        };
        /** RunListResponse */
        RunListResponse: {
            /**
             * Claim
             * @default research_only
             * @constant
             */
            claim: "research_only";
            /** Items */
            items: components["schemas"]["RunSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** RunMarkdownDetail */
        RunMarkdownDetail: {
            /** Markdown */
            markdown: string;
            /** Run Id */
            run_id: string;
            /** Sha256 */
            sha256: string;
        };
        /**
         * RunSummary
         * @description Summary of one ``metadata/research/runs/<run_id>.json`` notebook.
         */
        RunSummary: {
            /** Claim */
            claim: string | null;
            /** Data Source */
            data_source: string | null;
            /** Generated At */
            generated_at: string | null;
            /** Git Revision */
            git_revision: string | null;
            /** Has Markdown */
            has_markdown: boolean;
            /** N Hypotheses */
            n_hypotheses: number;
            /** N Rankers */
            n_rankers: number;
            /** Parse Error */
            parse_error?: string | null;
            /** Ranking Target */
            ranking_target: string | null;
            /** Run Id */
            run_id: string;
            /** Schema Version */
            schema_version: number | null;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Synthetic */
            synthetic: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerificationResult
         * @description Outcome of running a fail-closed verifier over an evidence object.
         *
         *     ``verifier`` names the check that ran so callers can distinguish the full
         *     research-notebook gate (``verify_research_artifact``) from the sealed-run
         *     verifier (``verify_phase1_run``) and the lightweight committed-receipt
         *     honesty check (``receipt_honesty_flags``).
         */
        VerificationResult: {
            /**
             * Claim
             * @default research_only
             * @constant
             */
            claim: "research_only";
            /** Context */
            context?: string | null;
            /** Errors */
            errors: string[];
            /**
             * Kind
             * @enum {string}
             */
            kind: "research_run" | "receipt" | "benchmark_run";
            /**
             * Live Pnl Claim
             * @default false
             * @constant
             */
            live_pnl_claim: false;
            /** Run Id */
            run_id?: string | null;
            /** Scorecard Families */
            scorecard_families?: number | null;
            /** Sha256 */
            sha256?: string | null;
            /** State */
            state?: string | null;
            /** Subject */
            subject: string;
            /** Valid */
            valid: boolean;
            /** Verifier */
            verifier: string;
        };
        /** VerifierRunDetail */
        VerifierRunDetail: {
            /** Id */
            id: string;
            /** Markdown */
            markdown: string;
            /** Sha256 */
            sha256: string;
            /** Time */
            time: string | null;
            /** Verdict */
            verdict: string | null;
            /** Version */
            version: string | null;
        };
        /** VerifierRunListResponse */
        VerifierRunListResponse: {
            /**
             * Claim
             * @default research_only
             * @constant
             */
            claim: "research_only";
            /** Items */
            items: components["schemas"]["VerifierRunSummary"][];
            /** Total */
            total: number;
        };
        /** VerifierRunSummary */
        VerifierRunSummary: {
            /** Id */
            id: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Time */
            time: string | null;
            /** Verdict */
            verdict: string | null;
            /** Version */
            version: string | null;
        };
        /** VerifierVersionDetail */
        VerifierVersionDetail: {
            /** Acceptance Markdown */
            acceptance_markdown: string;
            /** Sha256 */
            sha256: string;
            /** Version */
            version: string;
        };
        /** VerifierVersionListResponse */
        VerifierVersionListResponse: {
            /**
             * Claim
             * @default research_only
             * @constant
             */
            claim: "research_only";
            /** Items */
            items: components["schemas"]["VerifierVersionSummary"][];
            /** Total */
            total: number;
        };
        /** VerifierVersionSummary */
        VerifierVersionSummary: {
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_artifacts_artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactListResponse"];
                };
            };
        };
    };
    get_artifact_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_receipts_receipts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptListResponse"];
                };
            };
        };
    };
    get_receipt_by_hash_receipts_by_hash__digest__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                digest: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_receipt_receipts__receipt_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                receipt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_receipt_receipts__receipt_id__verification_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                receipt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_results_results_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultListResponse"];
                };
            };
        };
    };
    get_result_results__kind___name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_result_results__kind___name__verification_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_run_runs_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_markdown_runs__run_id__markdown_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunMarkdownDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_run_runs__run_id__verification_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_verifier_runs_verifier_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifierRunListResponse"];
                };
            };
        };
    };
    get_verifier_run_verifier_runs__run_log_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_log_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifierRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_verifier_versions_verifier_versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifierVersionListResponse"];
                };
            };
        };
    };
    get_verifier_version_verifier_versions__version__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifierVersionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
