CASES = {
    "plugins.read_cbor": {
        "arguments": {
            "path": "item.cbor",
        },
        "files": {
            "item.cbor": {
                "base64": "AA==",
            },
        },
        "expect": {
            "nodes": [
                {
                    "id": 0,
                    "parent_id": None,
                    "child_index": 0,
                    "depth": 0,
                    "map_key": None,
                    "map_key_byte_start": None,
                    "map_key_byte_length": None,
                    "byte_start": 0,
                    "byte_length": 1,
                    "kind": "unsigned_integer",
                    "value": "0",
                    "scalar_encoding_hex": "00",
                    "indefinite": False,
                    "string_chunk_count": None,
                    "child_count": 0,
                },
            ],
            "total_nodes": 1,
            "parsed_headers": 1,
            "maximum_depth": 0,
            "map_pair_count": 0,
            "string_payload_bytes": 0,
            "nonshortest_argument_count": 0,
            "offset": 0,
            "has_more": False,
            "full_source_validated": True,
            "deterministic_encoding_verified": False,
            "tag_policy": "reject_all_tags",
            "map_key_policy": "unique_definite_utf8_text",
            "source_bytes": 1,
            "source_sha256": "6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d",
        },
        "approx": False,
        "note": "One-byte CBOR unsigned integer 0 (major 0, additional 0).",
    },
    "plugins.read_csv": {
        "arguments": {
            "path": "table.csv",
        },
        "files": {
            "table.csv": "h\n1\n",
        },
        "expect": {
            "columns": [
                "h",
            ],
            "rows": [
                {
                    "h": "1",
                },
            ],
            "total_rows": 1,
            "offset": 0,
            "returned_rows": 1,
            "has_more": False,
            "blank_records_skipped": 0,
            "source_sha256": "733e3611b3b9ec754cb628ae0ce9d5f30f09ced371d95b0c605d6c97a75d0545",
            "source_bytes": 4,
        },
        "approx": False,
        "note": "Header h and one string cell 1; cells stay strings.",
    },
    "plugins.read_dbase": {
        "arguments": {
            "path": "rows.dbf",
            "text_codec": "ascii",
        },
        "files": {
            "rows.dbf": {
                "base64": "A3wBDwEAAABBAAIAAAAAAAAAAAAAAAAAAAAAAAAAAABBAAAAAAAAAAAAAEMAAAAAAQAAAAAAAAAAAAAAAAAAAA0gWBo=",
            },
        },
        "expect": {
            "version": "dBASE_III_PLUS_0x03_strict_subset",
            "text_codec": "ascii",
            "header_update_date": "2024-01-15",
            "header_bytes": 65,
            "record_bytes": 2,
            "columns": [
                {
                    "name": "A",
                    "kind": "C",
                    "width": 1,
                    "decimal_count": 0,
                    "record_byte_start": 1,
                    "observed_memory_address_hex": "00000000",
                },
            ],
            "physical_record_count": 1,
            "active_record_count": 1,
            "deleted_record_count": 0,
            "selected_record_count": 1,
            "include_deleted": False,
            "has_selected_records": True,
            "rows": [
                {
                    "selected_row_index": 0,
                    "physical_record_index": 0,
                    "source_byte_start": 65,
                    "deleted": False,
                    "values": [
                        "X",
                    ],
                    "raw_fields_hex": [
                        "58",
                    ],
                },
            ],
            "offset": 0,
            "has_more": False,
            "numeric_encoding": "exact_ascii_decimal_string",
            "character_padding_preserved": True,
            "full_source_validated": True,
            "sidecars_read": False,
            "source_bytes": 68,
            "source_sha256": "32485717423f9e26fea7032089eba82405e2cfb18baaafb5ac46b57dd5060b5e",
        },
        "approx": False,
        "note": "dBASE III 0x03, one C field A width 1, active record X, update date 2024-01-15.",
    },
    "plugins.read_fits_table": {
        "arguments": {
            "path": "table.fits",
        },
        "files": {
            "table.fits": {
                "base64": "U0lNUExFICA9ICAgICAgICAgICAgICAgICAgICBUICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBCSVRQSVggID0gICAgICAgICAgICAgICAgICAgIDggICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIE5BWElTICAgPSAgICAgICAgICAgICAgICAgICAgMCAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgRVhURU5EICA9ICAgICAgICAgICAgICAgICAgICBUICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBFTkQgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgWFRFTlNJT049ICdCSU5UQUJMRScgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBCSVRQSVggID0gICAgICAgICAgICAgICAgICAgIDggICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIE5BWElTICAgPSAgICAgICAgICAgICAgICAgICAgMiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgTkFYSVMxICA9ICAgICAgICAgICAgICAgICAgICAxICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBOQVhJUzIgID0gICAgICAgICAgICAgICAgICAgIDEgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIFBDT1VOVCAgPSAgICAgICAgICAgICAgICAgICAgMCAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgR0NPVU5UICA9ICAgICAgICAgICAgICAgICAgICAxICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBURklFTERTID0gICAgICAgICAgICAgICAgICAgIDEgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIFRGT1JNMSAgPSAnQiAgICAgICAnICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgVFRZUEUxICA9ICdWQUxVRSAgICcgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBFTkQgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
            },
        },
        "expect": {
            "table_kind": "BINTABLE",
            "columns": [
                {
                    "column_index": 0,
                    "name": "VALUE",
                    "unit": None,
                    "format": "B",
                    "scalar_type": "B",
                    "row_byte_start": 0,
                    "byte_width": 1,
                    "null_declaration": None,
                    "scale_declaration": "1",
                    "zero_declaration": "0",
                    "nonidentity_scaling_declared": False,
                },
            ],
            "row_bytes": 1,
            "row_count": 1,
            "has_rows": True,
            "table_data_byte_start": 5760,
            "table_data_bytes": 1,
            "table_padding_bytes": 2879,
            "primary_header_cards": [
                "SIMPLE  =                    T                                                  ",
                "BITPIX  =                    8                                                  ",
                "NAXIS   =                    0                                                  ",
                "EXTEND  =                    T                                                  ",
                "END                                                                             ",
            ],
            "table_header_cards": [
                "XTENSION= 'BINTABLE'                                                            ",
                "BITPIX  =                    8                                                  ",
                "NAXIS   =                    2                                                  ",
                "NAXIS1  =                    1                                                  ",
                "NAXIS2  =                    1                                                  ",
                "PCOUNT  =                    0                                                  ",
                "GCOUNT  =                    1                                                  ",
                "TFIELDS =                    1                                                  ",
                "TFORM1  = 'B       '                                                            ",
                "TTYPE1  = 'VALUE   '                                                            ",
                "END                                                                             ",
            ],
            "primary_header_sha256": "0e614f2a23eed66ea351fda79076eb6c160477372cae46375fff91e3314e596c",
            "table_header_sha256": "198c31c6d0486e502c31b13fa4867c4cbbaa28cd87b2593a875fdef6ba0406df",
            "rows": [
                {
                    "row_index": 0,
                    "source_byte_start": 5760,
                    "cells": [
                        {
                            "source_byte_start": 5760,
                            "raw_hex": "07",
                            "value": "7",
                            "value_encoding": "integer_decimal",
                            "null_reason": None,
                            "string_nul_terminated": False,
                        },
                    ],
                },
            ],
            "offset": 0,
            "has_more": False,
            "scaling_policy": "require_identity",
            "physical_scaling_applied": False,
            "values_represent": "stored_unscaled_values_with_declared_nulls",
            "fits_checksum_verified": False,
            "informational_metadata_interpreted": False,
            "full_source_validated_for_supported_subset": True,
            "source_bytes": 8640,
            "source_sha256": "066059469bc1c01b913cdd61ab9e0e0b55302f4a4160f3d73c746923d3d5b36a",
        },
        "approx": False,
        "note": "Empty primary plus one-row BINTABLE uint8 cell 7 at byte 5760.",
    },
    "plugins.read_fixed_width": {
        "arguments": {
            "path": "cols.fwf",
            "columns": [
                {
                    "name": "c",
                    "start": 0,
                    "end": 1,
                },
            ],
            "record_width": 1,
        },
        "files": {
            "cols.fwf": "Z\n",
        },
        "expect": {
            "columns": [
                "c",
            ],
            "column_spans": [
                [
                    0,
                    1,
                ],
            ],
            "position_convention": "zero_based_half_open_unicode_code_points",
            "record_width": 1,
            "physical_line_count": 1,
            "skipped_lines": 0,
            "comment_lines": 0,
            "skipped_blank_lines": 0,
            "header_source_line": None,
            "header_cells": None,
            "data_row_count": 1,
            "has_data_rows": True,
            "parsed_data_cells": 1,
            "rows": [
                {
                    "row_index": 0,
                    "source_line": 1,
                    "source_byte_start": 0,
                    "source_record_bytes": 1,
                    "cells": [
                        "Z",
                    ],
                },
            ],
            "offset": 0,
            "has_more": False,
            "full_source_validated": True,
            "source_bytes": 2,
            "source_sha256": "ec39b67830c0c34d71b0b6bf1d1c424eb7caab9222eb401fdaef044cf2145e9b",
        },
        "approx": False,
        "note": "One code-point record Z spanning [0, 1).",
    },
    "plugins.read_jsonl": {
        "arguments": {
            "path": "rows.jsonl",
        },
        "files": {
            "rows.jsonl": '{"a":1}\n',
        },
        "expect": {
            "columns": [
                "a",
            ],
            "rows": [
                {
                    "a": 1,
                },
            ],
            "physical_line_numbers": [
                1,
            ],
            "total_rows": 1,
            "offset": 0,
            "returned_rows": 1,
            "has_more": False,
            "blank_lines_skipped": 0,
            "source_sha256": "e346432021b04179518d9614f3560ccd71354a4ee101ddcb893d6959a9d6301c",
            "source_bytes": 8,
        },
        "approx": False,
        "note": "One JSON object; integer 1 is preserved as an int.",
    },
    "plugins.read_libsvm": {
        "arguments": {
            "path": "rows.libsvm",
        },
        "files": {
            "rows.libsvm": "1 2:3\n",
        },
        "expect": {
            "row_count": 1,
            "has_rows": True,
            "coordinate_count": 1,
            "explicit_zero_coordinates": 0,
            "nonzero_coordinates": 1,
            "declared_feature_count": None,
            "maximum_observed_feature_index": 2,
            "physical_line_count": 1,
            "comment_lines": 0,
            "inline_comments": 0,
            "skipped_blank_lines": 0,
            "rows": [
                {
                    "row_index": 0,
                    "source_line": 1,
                    "source_byte_start": 0,
                    "label": "1",
                    "stored_features": 1,
                    "explicit_zero_features": 0,
                    "coordinate_start": 0,
                },
            ],
            "row_offset": 0,
            "has_more_rows": False,
            "coordinates": [
                {
                    "coordinate_index": 0,
                    "row_index": 0,
                    "source_line": 1,
                    "feature_index": 2,
                    "value": "3",
                },
            ],
            "coordinate_offset": 0,
            "has_more_coordinates": False,
            "feature_index_base": 1,
            "numeric_encoding": "original_exact_decimal_tokens",
            "label_semantics": "not_inferred",
            "dense_array_allocated": False,
            "full_source_validated": True,
            "source_bytes": 6,
            "source_sha256": "035a0df2e2248118b9f4b44893dbde3ed0bfd68710c52512b813fea455a9dbfe",
        },
        "approx": False,
        "note": "Label 1 and one increasing index:value pair 2:3.",
    },
    "plugins.read_matrix_market": {
        "arguments": {
            "path": "matrix.mtx",
            "duplicate_policy": "reject",
        },
        "files": {
            "matrix.mtx": "%%MatrixMarket matrix coordinate integer general\n1 1 1\n1 1 7\n",
        },
        "expect": {
            "rows": 1,
            "columns": 1,
            "field": "integer",
            "symmetry": "general",
            "duplicate_policy": "reject",
            "input_records": 1,
            "stored_unique_entries": 1,
            "duplicate_records_merged": 0,
            "expanded_entry_count": 1,
            "explicit_input_zero_records": 0,
            "reduced_zero_entries": 0,
            "expanded_nonzero_entries": 1,
            "entries": [
                {
                    "row": 0,
                    "column": 0,
                    "real": "7",
                    "imaginary": None,
                },
            ],
            "offset": 0,
            "has_more": False,
            "output_index_base": 0,
            "numerical_encoding": "exact_decimal_strings_pattern_values_null",
            "symmetry_expanded": True,
            "dense_array_allocated": False,
            "source_bytes": 61,
            "source_sha256": "0c6a405f52e1bfb368870fd1725394852d20a294d51bf66deb3d78906b9adf70",
        },
        "approx": False,
        "note": "1x1 integer coordinate; one-based (1,1)=7 becomes zero-based (0,0) decimal 7.",
    },
    "plugins.read_messagepack": {
        "arguments": {
            "path": "value.msgpack",
        },
        "files": {
            "value.msgpack": {
                "base64": "AA==",
            },
        },
        "expect": {
            "nodes": [
                {
                    "id": 0,
                    "parent_id": None,
                    "child_index": 0,
                    "depth": 0,
                    "map_key": None,
                    "map_key_byte_start": None,
                    "map_key_byte_length": None,
                    "byte_start": 0,
                    "byte_length": 1,
                    "format_byte_hex": "00",
                    "kind": "integer",
                    "value": "0",
                    "scalar_payload_hex": "",
                    "child_count": 0,
                    "extension_type": None,
                    "timestamp_seconds": None,
                    "timestamp_nanoseconds": None,
                },
            ],
            "total_nodes": 1,
            "parsed_headers": 1,
            "maximum_depth": 0,
            "map_pair_count": 0,
            "timestamp_count": 0,
            "opaque_extension_count": 0,
            "application_extensions": "reject",
            "offset": 0,
            "has_more": False,
            "full_source_validated": True,
            "canonical_encoding_verified": False,
            "object_extensions_loaded": False,
            "map_key_policy": "unique_utf8_strings",
            "source_bytes": 1,
            "source_sha256": "6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d",
        },
        "approx": False,
        "note": "Positive fixint 0x00 is integer 0 with an empty scalar payload.",
    },
    "plugins.read_ply": {
        "arguments": {
            "path": "mesh.ply",
        },
        "files": {
            "mesh.ply": "ply\nformat ascii 1.0\nelement vertex 1\nproperty int x\nend_header\n1",
        },
        "expect": {
            "format": "ascii",
            "elements": [
                {
                    "name": "vertex",
                    "record_count": 1,
                    "properties": [
                        {
                            "name": "x",
                            "item_type": "int32",
                            "count_type": None,
                        },
                    ],
                },
            ],
            "header_lines": [
                "ply",
                "format ascii 1.0",
                "element vertex 1",
                "property int x",
                "end_header",
            ],
            "header_bytes": 64,
            "record_count": 1,
            "has_records": True,
            "scalar_reads": 1,
            "conventional_face_list_count": 0,
            "faces_with_repeated_indices": 0,
            "conventional_face_property_declared": False,
            "topology_indices_checked": False,
            "geometric_validity_verified": False,
            "ascii_float_rounding_applied": False,
            "records": [
                {
                    "record_index": 0,
                    "element_name": "vertex",
                    "element_record_index": 0,
                    "source_byte_start": 64,
                    "source_byte_length": 1,
                    "values": [
                        {
                            "property_name": "x",
                            "values": [
                                "1",
                            ],
                            "is_list": False,
                            "source_byte_start": 64,
                            "source_byte_length": 1,
                            "raw_hex": "31",
                        },
                    ],
                },
            ],
            "offset": 0,
            "has_more": False,
            "full_supported_structure_validated": True,
            "source_bytes": 65,
            "source_sha256": "68747c6a3def2cc32294cddb9f3a498681efa4c91aef1d04a7ff515ba58bf139",
        },
        "approx": False,
        "note": "ASCII PLY alias int is int32; the single token 1 is the decimal string 1.",
    },
    "plugins.read_sparse_npz": {
        "arguments": {
            "path": "sparse.npz",
            "expected_format": "coo",
        },
        "files": {
            "sparse.npz": {
                "base64": "UEsDBBQAAAAAAAAAAABuyvInUwAAAFMAAAAKAAAAZm9ybWF0Lm5weZNOVU1QWQEARgB7J2Rlc2NyJzogJ3xTMycsICdmb3J0cmFuX29yZGVyJzogRmFsc2UsICdzaGFwZSc6ICgpLCB9ICAgICAgICAgICAgICAKY29vUEsDBBQAAAAAAAAAAAC8AtsWWAAAAFgAAAAJAAAAc2hhcGUubnB5k05VTVBZAQBGAHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgIAoBAAAAAQAAAFBLAwQUAAAAAAAAAAAAwDg6PlQAAABUAAAACAAAAGRhdGEubnB5k05VTVBZAQBGAHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgIAoFAAAAUEsDBBQAAAAAAAAAAADyyOQJVAAAAFQAAAAHAAAAcm93Lm5weZNOVU1QWQEARgB7J2Rlc2NyJzogJzxpNCcsICdmb3J0cmFuX29yZGVyJzogRmFsc2UsICdzaGFwZSc6ICgxLCksIH0gICAgICAgICAgICAKAAAAAFBLAwQUAAAAAAAAAAAA8sjkCVQAAABUAAAABwAAAGNvbC5ucHmTTlVNUFkBAEYAeydkZXNjcic6ICc8aTQnLCAnZm9ydHJhbl9vcmRlcic6IEZhbHNlLCAnc2hhcGUnOiAoMSwpLCB9ICAgICAgICAgICAgCgAAAABQSwECFAAUAAAAAAAAAAAAbsryJ1MAAABTAAAACgAAAAAAAAAAAAAAAAAAAAAAZm9ybWF0Lm5weVBLAQIUABQAAAAAAAAAAAC8AtsWWAAAAFgAAAAJAAAAAAAAAAAAAAAAAHsAAABzaGFwZS5ucHlQSwECFAAUAAAAAAAAAAAAwDg6PlQAAABUAAAACAAAAAAAAAAAAAAAAAD6AAAAZGF0YS5ucHlQSwECFAAUAAAAAAAAAAAA8sjkCVQAAABUAAAABwAAAAAAAAAAAAAAAAB0AQAAcm93Lm5weVBLAQIUABQAAAAAAAAAAADyyOQJVAAAAFQAAAAHAAAAAAAAAAAAAAAAAO0BAABjb2wubnB5UEsFBgAAAAAFAAUADwEAAGYCAAAAAA==",
            },
        },
        "expect": {
            "sparse_format": "coo",
            "shape": [
                1,
                1,
            ],
            "data_dtype": "<i4",
            "value_encoding": "decimal_integer",
            "is_array_marker": None,
            "stored_entry_count": 1,
            "explicit_zero_count": 0,
            "duplicate_entry_count": 0,
            "coordinates_unique": True,
            "storage_coordinates_sorted": True,
            "canonical_storage": True,
            "has_stored_entries": True,
            "entries": [
                {
                    "storage_index": 0,
                    "row": 0,
                    "column": 0,
                    "components": [
                        "5",
                    ],
                    "raw_hex": "05000000",
                },
            ],
            "offset": 0,
            "has_more": False,
            "members": [
                {
                    "name": "format.npy",
                    "compressed_bytes": 83,
                    "expanded_bytes": 83,
                    "compression": "stored",
                    "sha256": "7eaacee950689f67260fb9a48a06910116d0ae4b4d2450fba97e12de0a080afa",
                    "crc32_hex": "27f2ca6e",
                    "npy_version": "1.0",
                    "dtype": "|S3",
                    "shape": [],
                },
                {
                    "name": "shape.npy",
                    "compressed_bytes": 88,
                    "expanded_bytes": 88,
                    "compression": "stored",
                    "sha256": "76876d0ff29a1a30df0dfb9c83109ad68a20951056326b9fe118236b7db1604a",
                    "crc32_hex": "16db02bc",
                    "npy_version": "1.0",
                    "dtype": "<i4",
                    "shape": [
                        2,
                    ],
                },
                {
                    "name": "data.npy",
                    "compressed_bytes": 84,
                    "expanded_bytes": 84,
                    "compression": "stored",
                    "sha256": "6bdbbe4dc28fa5031c877739395b1a92f880d15c0fd3b7568d72fa8ee7839fc0",
                    "crc32_hex": "3e3a38c0",
                    "npy_version": "1.0",
                    "dtype": "<i4",
                    "shape": [
                        1,
                    ],
                },
                {
                    "name": "row.npy",
                    "compressed_bytes": 84,
                    "expanded_bytes": 84,
                    "compression": "stored",
                    "sha256": "c09a10d02fced46fb66c092278dfa61c924e35bfe1ed0051ba6e6dd2d14e7ffb",
                    "crc32_hex": "09e4c8f2",
                    "npy_version": "1.0",
                    "dtype": "<i4",
                    "shape": [
                        1,
                    ],
                },
                {
                    "name": "col.npy",
                    "compressed_bytes": 84,
                    "expanded_bytes": 84,
                    "compression": "stored",
                    "sha256": "c09a10d02fced46fb66c092278dfa61c924e35bfe1ed0051ba6e6dd2d14e7ffb",
                    "crc32_hex": "09e4c8f2",
                    "npy_version": "1.0",
                    "dtype": "<i4",
                    "shape": [
                        1,
                    ],
                },
            ],
            "expanded_bytes": 423,
            "full_source_validated": True,
            "dense_matrix_allocated": False,
            "duplicate_reduction_performed": False,
            "source_bytes": 907,
            "source_sha256": "93621cf086235c6a1788df5464eb255cf8aa3f482021b5cc0364fc9873688467",
        },
        "approx": False,
        "note": "Stored COO NPZ, shape 1x1, one little-endian int32 value 5 at (0, 0).",
    },
    "plugins.read_toml": {
        "arguments": {
            "path": "config.toml",
        },
        "files": {
            "config.toml": "n = 1\nd = 2024-01-02\n",
        },
        "expect": {
            "table_path": [],
            "data": {
                "n": 1,
                "d": "2024-01-02",
            },
            "temporal_values": [
                {
                    "path": [
                        "d",
                    ],
                    "kind": "local_date",
                    "iso_value": "2024-01-02",
                },
            ],
            "source_sha256": "ee6a4184008cfc09d06d62c6cffdd5fa5bc9507f7a10b4572d3a457df0153b1a",
            "source_bytes": 21,
        },
        "approx": False,
        "note": "Integer n stays an int; local date d is an ISO string with local_date metadata.",
    },
    "plugins.read_wav_pcm": {
        "arguments": {
            "path": "tone.wav",
        },
        "files": {
            "tone.wav": {
                "base64": "UklGRiYAAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQEAAACAAA==",
            },
        },
        "expect": {
            "format_code": 1,
            "encoding": "pcm_unsigned_8",
            "extensible": False,
            "channel_count": 1,
            "channel_mask": None,
            "speaker_bit_indices": None,
            "sample_rate": 8000,
            "bits_per_sample": 8,
            "block_align": 1,
            "byte_rate": 8000,
            "frame_count": 1,
            "scalar_sample_count": 1,
            "has_frames": True,
            "duration_numerator": 1,
            "time_denominator": 8000,
            "fact_declared_sample_count": None,
            "fact_count_equals_frame_count": None,
            "fact_count_semantics_verified": False,
            "chunks": [
                {
                    "chunk_id": "fmt ",
                    "header_byte_start": 12,
                    "payload_byte_start": 20,
                    "payload_bytes": 16,
                    "padding_bytes": 0,
                    "payload_sha256": "c4a4d3e449c0242ca1cbe7a9a4f77e77de991da5947eb0c14a57b1b23847a994",
                    "payload_interpreted": True,
                },
                {
                    "chunk_id": "data",
                    "header_byte_start": 36,
                    "payload_byte_start": 44,
                    "payload_bytes": 1,
                    "padding_bytes": 1,
                    "payload_sha256": "76be8b528d0075f7aae98d6fa57a6d3c83ae480a8469e668d7b0af968995ac71",
                    "payload_interpreted": True,
                },
            ],
            "frames": [
                {
                    "frame_index": 0,
                    "source_byte_start": 44,
                    "time_numerator": 0,
                    "samples": [
                        {
                            "channel_index": 0,
                            "source_byte_start": 44,
                            "raw_hex": "80",
                            "value": "128",
                        },
                    ],
                },
            ],
            "offset": 0,
            "has_more": False,
            "normalization_applied": False,
            "ancillary_semantics_validated": False,
            "full_framing_and_samples_validated": True,
            "source_bytes": 46,
            "source_sha256": "373324023416a5dc3809e647e041fc48a13db20648d5782ac989cba17014203b",
        },
        "approx": False,
        "note": "Mono 8-bit PCM, one unsigned sample 0x80 = 128, odd data chunk zero-padded.",
    },
    "plugins.read_xml": {
        "arguments": {
            "path": "doc.xml",
        },
        "files": {
            "doc.xml": '<r a="1">t</r>',
        },
        "expect": {
            "nodes": [
                {
                    "id": 0,
                    "parent_id": None,
                    "sibling_index": 0,
                    "depth": 1,
                    "namespace_uri": None,
                    "local_name": "r",
                    "attributes": [
                        {
                            "namespace_uri": None,
                            "local_name": "a",
                            "value": "1",
                        },
                    ],
                    "child_count": 0,
                    "text": "t",
                    "tail": "",
                },
            ],
            "total_nodes": 1,
            "maximum_depth": 1,
            "total_attributes": 1,
            "total_text_characters": 1,
            "total_attribute_characters": 1,
            "comment_count": 0,
            "processing_instruction_count": 0,
            "namespace_declaration_count": 0,
            "offset": 0,
            "has_more": False,
            "document_validated": True,
            "custom_entities_allowed": False,
            "namespace_representation": "expanded_uri_and_local_name",
            "source_bytes": 14,
            "source_sha256": "0a96a629f6c6d72f80743bae7b4e0675891aafa1f5af18279dd00056ca3c5c49",
        },
        "approx": False,
        "note": "One element r, attribute a=1, text t; no namespace declarations.",
    },
    "plugins.read_yaml": {
        "arguments": {
            "path": "doc.yaml",
        },
        "files": {
            "doc.yaml": "a: 1\n",
        },
        "expect": {
            "data": {
                "a": 1,
            },
            "value_node_count": 2,
            "maximum_depth": 1,
            "scalar_policy": "json_spellings_with_yaml_strings",
            "aliases_allowed": False,
            "explicit_tags_allowed": False,
            "source_sha256": "37b128c59f1f5097f73f82691cb519f1f568667faab5ced1b4ab979d36837eae",
            "source_bytes": 5,
        },
        "approx": False,
        "note": "One map and one JSON integer; keys are not value nodes, so the count is 2 and depth is 1.",
    },
    "plugins.verify_file_hash": {
        "arguments": {
            "path": "artifact.txt",
            "expected_sha256": "2d711642b726b04401627ca9fbac32f5c8530fb1903cc4db02258717921a4881",
            "expected_bytes": 1,
        },
        "files": {
            "artifact.txt": "x",
        },
        "expect": {
            "path": "artifact.txt",
            "expected_sha256": "2d711642b726b04401627ca9fbac32f5c8530fb1903cc4db02258717921a4881",
            "actual_sha256": "2d711642b726b04401627ca9fbac32f5c8530fb1903cc4db02258717921a4881",
            "digest_matches": True,
            "actual_bytes": 1,
            "expected_bytes": 1,
            "size_matches": True,
            "matches": True,
        },
        "approx": False,
        "note": "SHA-256 and size of the single byte x both match, so matches is true.",
    },
    "plugins.verify_signed_checkpoint": {
        "arguments": {
            "path": "checkpoint.json",
            "trusted_keys": [
                {
                    "identity": "signer",
                    "public_key": "cdb70e63b550c9c2994650d2aac1ba7a47124ff9fa8187cc894402d3ba619290",
                },
            ],
            "expected_identity": "signer",
            "expected_domain": "quant_fund.audit.checkpoint.v1",
            "expected_tree_size": 1,
            "expected_merkle_root": "7975edd9e7393c229e744913fe0d0bb86fb4cf46906e2e51152137e20ad15590",
        },
        "files": {
            "checkpoint.json": '{"key_id":"960dcfe3bcba6eb8","merkle_root":"7975edd9e7393c229e744913fe0d0bb86fb4cf46906e2e51152137e20ad15590","public_key":"cdb70e63b550c9c2994650d2aac1ba7a47124ff9fa8187cc894402d3ba619290","scheme":"ed25519","signature":"1465244694ec08efa47524e23610c0ecf83bd01be3aec07e10350bdf7778e42ea0111e40e4906a866585e1934f993ff9aec5e93f81d7451fd07b38b036e19407","timestamp_utc":"2024-01-02T00:00:00Z","tree_size":1,"v":1}',
        },
        "expect": {
            "record_index": 0,
            "record_count": 1,
            "declared_tree_size": 1,
            "declared_merkle_root": "7975edd9e7393c229e744913fe0d0bb86fb4cf46906e2e51152137e20ad15590",
            "declared_timestamp_utc": "2024-01-02T00:00:00Z",
            "declared_key_id": "960dcfe3bcba6eb8",
            "expected_identity": "signer",
            "expected_domain": "quant_fund.audit.checkpoint.v1",
            "supplied_key_sha256": "960dcfe3bcba6eb8df310336505695ffdfd7c0bc9051efbaf57fee25777e21bc",
            "signature_valid_under_supplied_key": True,
            "signature_valid_under_embedded_key": True,
            "embedded_key_matches_supplied_key": True,
            "key_id_matches_supplied_key": True,
            "expected_tree_size_matches": True,
            "expected_merkle_root_matches": True,
            "checkpoint_matches_supplied_expectations": True,
            "unsigned_metadata": {
                "public_key": "cdb70e63b550c9c2994650d2aac1ba7a47124ff9fa8187cc894402d3ba619290",
                "sigstore_bundle_json": None,
                "sigstore_identity": None,
                "sigstore_issuer": None,
            },
            "canonical_record_spelling": True,
            "signed_payload_sha256": "b3ee72c20e3c9abd5eddc53893a4f631f10a7c9dcc50f656977611c47239822e",
            "signed_payload_bytes": 188,
            "domain_cryptographically_bound": False,
            "trust_scope": "agreement_with_caller_supplied_key_and_anchors",
            "ledger_completeness_verified": False,
            "ledger_consistency_verified": False,
            "timestamp_freshness_checked": False,
            "research_certified": False,
            "source_bytes": 411,
            "source_sha256": "c98d7831ba0691bd51abc8c84e7d7d3f97e608c36b8b795d8eb283bc49845856",
        },
        "approx": False,
        "note": "Ed25519 signature over the sorted six-field payload; key_id is the first 16 hex chars of SHA-256(public key).",
    },
    "skills.align_event_sequences": {
        "arguments": {
            "left": [
                {
                    "match_key": "A",
                    "event_time": "2024-01-01T00:00:00Z",
                },
            ],
            "right": [
                {
                    "match_key": "A",
                    "event_time": "2024-01-01T00:00:00Z",
                },
            ],
            "max_time_difference_microseconds": 0,
            "clock_direction": "either",
            "left_gap_cost": 1,
            "right_gap_cost": 1,
            "match_cost": 0,
            "time_difference_cost_per_microsecond": 0,
        },
        "files": {},
        "expect": {
            "left_count": 1,
            "right_count": 1,
            "dp_cells": 4,
            "eligible_pair_count": 1,
            "total_cost": 0,
            "matched_pair_count": 1,
            "unmatched_left_count": 0,
            "unmatched_right_count": 0,
            "alignment_step_count": 1,
            "optimal_path_count_capped_at_two": 1,
            "optimal_alignment_ambiguous": False,
            "ambiguity_definition": "distinct_operation_paths_including_gap_order",
            "alignment_semantics": "cost_optimum_not_verified_event_identity",
            "tie_policy": "backward_match_then_left_only_then_right_only",
            "clock_direction": "either",
            "max_time_difference_microseconds": 0,
            "left_gap_cost": 1,
            "right_gap_cost": 1,
            "match_cost": 0,
            "time_difference_cost_per_microsecond": 0,
            "selected_path_ambiguity_count": 0,
            "omitted_ambiguity_diagnostics": 0,
            "ambiguity_diagnostics": [],
            "offset": 0,
            "next_offset": None,
            "steps": [
                {
                    "alignment_index": 0,
                    "operation": "match",
                    "left_row_index": 0,
                    "right_row_index": 0,
                    "right_minus_left_microseconds": 0,
                    "cost": 0,
                },
            ],
        },
        "approx": False,
        "note": "Equal keys and clocks make the match cost 0, which beats either gap cost of 1.",
    },
    "skills.assign_horizon_targets": {
        "arguments": {
            "calendars": [
                {
                    "calendar_id": "nyse",
                    "available_time": "2024-01-01T00:00:00Z",
                    "coverage_start": "2024-01-01T00:00:00Z",
                    "coverage_end": "2024-01-03T00:00:00Z",
                    "closes": [
                        {
                            "session_id": "s1",
                            "close_time": "2024-01-02T21:00:00Z",
                        },
                    ],
                },
            ],
            "decisions": [
                {
                    "calendar_id": "nyse",
                    "decision_time": "2024-01-02T00:00:00Z",
                },
            ],
            "session_offsets": [
                1,
            ],
            "inclusion": "strictly_after",
        },
        "files": {},
        "expect": {
            "calendar_count": 1,
            "supplied_close_count": 1,
            "decision_count": 1,
            "horizon_count": 1,
            "assignment_count": 1,
            "assigned_count": 1,
            "unresolved_count": 0,
            "status_counts": {
                "assigned": 1,
            },
            "inclusion": "strictly_after",
            "coverage_completeness": "asserted_by_caller_not_inferred",
            "assignment_order": "decision_input_order_then_session_offsets_input_order",
            "assignments": [
                {
                    "assignment_index": 0,
                    "decision_row_index": 0,
                    "horizon_index": 0,
                    "session_offset": 1,
                    "status": "assigned",
                    "calendar_row_index": 0,
                    "target_session_index": 0,
                    "target_session_id": "s1",
                    "target_time": "2024-01-02T21:00:00Z",
                    "target_strictly_after_decision": True,
                },
            ],
            "next_offset": None,
        },
        "approx": False,
        "note": "strictly_after the 00:00 decision selects the only later close, session offset 1.",
    },
    "skills.audit_artifact_assembly": {
        "arguments": {
            "objects": [
                {
                    "object_id": "obj",
                    "version_id": "v1",
                    "size": 4,
                    "sha256": "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
                    "available_time": "2024-01-01T00:00:00Z",
                },
            ],
            "assemblies": [
                {
                    "assembly_id": "asm",
                    "version_id": "v1",
                    "declared_size": 4,
                    "sha256": "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
                    "expected_part_count": 1,
                    "available_time": "2024-01-02T00:00:00Z",
                },
            ],
            "parts": [
                {
                    "part_id": "part1",
                    "assembly_id": "asm",
                    "ordinal": 0,
                    "source_object_id": "obj",
                    "source_version_id": "v1",
                    "expected_source_sha256": "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
                    "source_offset": 0,
                    "length": 4,
                    "target_offset": 0,
                    "part_sha256": "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
                    "available_time": "2024-01-01T12:00:00Z",
                },
            ],
            "decision_time": "2024-01-03T00:00:00Z",
        },
        "files": {},
        "expect": {
            "passed": True,
            "object_count": 1,
            "assembly_count": 1,
            "part_count": 1,
            "usable_declaration_count": 1,
            "issue_counts": {},
            "diagnostics": [],
            "omitted_diagnostics": 0,
            "assemblies": [
                {
                    "assembly_row_index": 0,
                    "assembly_id": "asm",
                    "version_id": "v1",
                    "declared_size": 4,
                    "observed_part_count": 1,
                    "source_references_complete": True,
                    "maximum_declared_input_available_time": "2024-01-01T12:00:00Z",
                    "missing_ordinal_count": 0,
                    "excess_ordinal_count": 0,
                    "ordinal_concatenation_matches": True,
                    "target_covered_bytes": 4,
                    "target_missing_bytes": 0,
                    "target_overlap_bytes": 0,
                    "target_multiplicity_excess_bytes": 0,
                    "target_excess_bytes": 0,
                    "hash_label_equation": "single_part",
                    "hash_labels_match": True,
                    "available_at_decision": True,
                    "usable_declaration_at_decision": True,
                    "passed": True,
                },
            ],
            "offset": 0,
            "has_more": False,
            "artifact_bytes_verified": False,
            "publication_truth_verified": False,
            "multipart_hash_derived": False,
        },
        "approx": False,
        "note": "One whole-source part covers [0, 4) in ordinal order; single-part hash labels agree.",
    },
    "skills.audit_bar_integrity": {
        "arguments": {
            "bars": [
                {
                    "open": 10.0,
                    "high": 9.0,
                    "low": 11.0,
                    "close": 10.0,
                    "volume": 1.0,
                },
            ],
        },
        "files": {},
        "expect": {
            "row_count": 1,
            "valid_rows": 0,
            "invalid_rows": 1,
            "passed": False,
            "violation_count": 1,
            "violation_counts": {
                "inverted_range": 1,
            },
            "diagnostics": [
                {
                    "row_index": 0,
                    "field": "high",
                    "code": "inverted_range",
                },
            ],
            "omitted_diagnostics": 0,
        },
        "approx": False,
        "note": "Low 11 is above high 9, so the only violation is inverted_range on high; envelope checks are skipped.",
    },
    "skills.audit_cross_field_contracts": {
        "arguments": {
            "rows": [
                {
                    "x": 1,
                    "y": 2,
                },
                {
                    "x": 3,
                    "y": 3,
                },
            ],
            "rules": [
                {
                    "id": "lt",
                    "left_field": "x",
                    "operator": "lt",
                    "right": {
                        "kind": "field",
                        "field": "y",
                    },
                },
            ],
            "numeric_policy": "compatible",
        },
        "files": {},
        "expect": {
            "row_count": 2,
            "rule_count": 1,
            "numeric_policy": "compatible",
            "assessment": "failed",
            "passed": False,
            "checked_comparisons": 2,
            "failed_comparisons": 1,
            "skipped_comparisons": 0,
            "conforming_rows": 1,
            "nonconforming_rows": 1,
            "unassessed_rows": 0,
            "rules": [
                {
                    "rule_id": "lt",
                    "passed_comparisons": 1,
                    "failed_comparisons": 1,
                    "skipped_missing": 0,
                    "skipped_null": 0,
                    "failure_counts": {
                        "comparison_failed": 1,
                    },
                    "passed": False,
                },
            ],
            "diagnostics": [
                {
                    "row_index": 1,
                    "rule_id": "lt",
                    "code": "comparison_failed",
                    "left_value": 3,
                    "right_value": 3,
                    "missing_fields": [],
                },
            ],
            "omitted_diagnostics": 0,
        },
        "approx": False,
        "note": "1 < 2 passes and 3 < 3 fails, so one of two checked comparisons fails.",
    },
    "skills.audit_dependency_releases": {
        "arguments": {
            "stage_order": [
                "build",
            ],
            "releases": [
                {
                    "component_id": "lib",
                    "version_id": "1",
                    "available_time": "2024-01-01T00:00:00Z",
                    "valid_from": "2024-01-01T00:00:00Z",
                    "milestones": [
                        {
                            "stage_id": "build",
                            "started_time": "2024-01-01T00:00:00Z",
                            "completed_time": "2024-01-01T01:00:00Z",
                            "available_time": "2024-01-01T02:00:00Z",
                        },
                    ],
                },
            ],
            "queries": [
                {
                    "component_id": "lib",
                    "version_id": "1",
                    "stage_id": "build",
                    "decision_time": "2024-01-02T00:00:00Z",
                },
            ],
        },
        "files": {},
        "expect": {
            "passed": True,
            "release_count": 1,
            "milestone_count": 1,
            "dependency_count": 0,
            "declared_supersession_count": 0,
            "applied_supersession_edge_count": 0,
            "invalid_manifest_count": 0,
            "invalid_stage_count": 0,
            "issue_counts": {},
            "diagnostics": [],
            "omitted_diagnostics": 0,
            "query_count": 1,
            "candidate_versions_examined": 1,
            "query_status_counts": {
                "resolved": 1,
            },
            "queries": [
                {
                    "query_row_index": 0,
                    "status": "resolved",
                    "candidate_count": 1,
                    "candidate_release_row_indexes": [
                        0,
                    ],
                    "omitted_candidate_indexes": 0,
                    "release_row_index": 0,
                    "milestone_row_index": 0,
                    "maximum_source_available_time": "2024-01-01T02:00:00Z",
                    "superseded_at": None,
                    "ineligibility_reason": None,
                },
            ],
            "offset": 0,
            "has_more": False,
            "artifact_contents_verified": False,
            "deployment_or_publication_truth_verified": False,
        },
        "approx": False,
        "note": "The only build milestone is available at 02:00, before the next-day decision, so the query resolves.",
    },
    "skills.audit_duplicate_keys": {
        "arguments": {
            "rows": [
                {
                    "k": "a",
                },
                {
                    "k": "a",
                },
                {
                    "k": "b",
                },
            ],
            "keys": [
                "k",
            ],
            "null_policy": "reject",
        },
        "files": {},
        "expect": {
            "row_count": 3,
            "keys": [
                "k",
            ],
            "null_policy": "reject",
            "passed": False,
            "invalid_key_rows": 0,
            "null_key_rows": 0,
            "comparable_rows": 3,
            "distinct_keys": 2,
            "duplicate_key_groups": 1,
            "duplicate_rows": 1,
            "rows_in_duplicate_groups": 2,
            "invalid_key_examples": [],
            "omitted_invalid_examples": 0,
            "duplicate_examples": [
                {
                    "key_values": {
                        "k": "a",
                    },
                    "row_count": 2,
                    "row_indices": [
                        0,
                        1,
                    ],
                    "omitted_row_indices": 0,
                },
            ],
            "omitted_duplicate_groups": 0,
        },
        "approx": False,
        "note": "Key a occurs twice and b once, so distinct keys are 2 and duplicate rows are 1.",
    },
    "skills.audit_effective_intervals": {
        "arguments": {
            "intervals": [
                {
                    "group_id": "g",
                    "valid_from": "2024-01-01T00:00:00Z",
                    "valid_to": "2024-01-01T00:00:10Z",
                },
                {
                    "group_id": "g",
                    "valid_from": "2024-01-01T00:00:12Z",
                    "valid_to": "2024-01-01T00:00:20Z",
                },
            ],
        },
        "files": {},
        "expect": {
            "input_intervals": 2,
            "group_count": 1,
            "valid_intervals": 2,
            "invalid_intervals": 0,
            "open_start_intervals": 0,
            "open_end_intervals": 0,
            "overlap_pair_count": 0,
            "intervals_with_prior_overlap": 0,
            "internal_gap_count": 1,
            "total_internal_gap_seconds": 2.0,
            "passed": False,
            "interval_policy": "half_open_with_none_as_unbounded_endpoint",
            "overlap_diagnostics": "one_witness_per_interval_with_prior_overlap",
            "finding_count": 1,
            "diagnostics": [
                {
                    "group_id": "g",
                    "code": "gap",
                    "row_index": 1,
                    "other_row_index": 0,
                    "span_start": "2024-01-01T00:00:10Z",
                    "span_end": "2024-01-01T00:00:12Z",
                    "prior_overlap_partners": 0,
                    "gap_seconds": 2.0,
                },
            ],
            "omitted_diagnostics": 0,
        },
        "approx": False,
        "note": "Half-open [00:00, 00:10) then [00:12, 00:20) leaves one internal gap of 2 seconds and no overlap.",
    },
    "skills.audit_feature_provenance": {
        "arguments": {
            "sources": [
                {
                    "source_id": "s1",
                    "source": "tape",
                    "revision_id": "r1",
                    "available_time": "2024-01-01T00:00:00Z",
                    "field_versions": {
                        "px": "v3",
                    },
                },
            ],
            "features": [
                {
                    "security_id": "AAA",
                    "decision_time": "2024-01-02T00:00:00Z",
                    "max_source_available_time": "2024-01-01T00:00:00Z",
                    "feature_set_version": "fs1",
                    "feature_versions": {
                        "px": "f1",
                    },
                    "dependencies": [
                        {
                            "feature_field": "px",
                            "source_id": "s1",
                            "source_field": "px",
                            "source_field_version": "v3",
                        },
                    ],
                },
            ],
            "required_feature_versions": {
                "px": "f1",
            },
            "required_feature_set_version": "fs1",
        },
        "files": {},
        "expect": {
            "feature_row_count": 1,
            "valid_feature_rows": 1,
            "invalid_feature_rows": 0,
            "source_row_count": 1,
            "duplicate_source_ids": 0,
            "passed": True,
            "issue_count": 0,
            "issue_counts": {},
            "diagnostics": [],
            "omitted_diagnostics": 0,
            "offset": 0,
            "next_offset": None,
            "rows": [
                {
                    "feature_row_index": 0,
                    "security_id": "AAA",
                    "valid": True,
                    "issue_count": 0,
                    "dependency_count": 1,
                    "resolved_source_count": 1,
                    "complete_reference_resolution": True,
                    "actual_max_source_available_time": "2024-01-01T00:00:00Z",
                    "claimed_max_source_available_time": "2024-01-01T00:00:00Z",
                },
            ],
        },
        "approx": False,
        "note": "The only dependency resolves to source s1 and the claimed availability maximum equals that clock.",
    },
    "skills.audit_forecast_panel": {
        "arguments": {
            "forecasts": [
                {
                    "security_id": "AAA",
                    "target": "ret",
                    "horizon": "1d",
                    "model_version": "m1",
                    "decision_time": "2024-01-01T00:00:00Z",
                    "target_time": "2024-01-02T00:00:00Z",
                    "max_source_available_time": "2024-01-01T00:00:00Z",
                    "forecast_available_time": "2024-01-01T00:00:00Z",
                    "values": {
                        "yhat": 1,
                    },
                },
            ],
            "realizations": [
                {
                    "security_id": "AAA",
                    "target": "ret",
                    "horizon": "1d",
                    "decision_time": "2024-01-01T00:00:00Z",
                    "target_time": "2024-01-02T00:00:00Z",
                    "available_time": "2024-01-02T00:00:00Z",
                    "revision_id": "r1",
                    "source": "tape",
                    "value": 1,
                },
            ],
            "evaluation_asof": "2024-01-03T00:00:00Z",
            "require_due_coverage": True,
            "require_no_orphan_realizations": False,
        },
        "files": {},
        "expect": {
            "forecast_rows": 1,
            "realization_rows": 1,
            "distinct_forecast_keys": 1,
            "distinct_outcome_forecast_keys": 1,
            "distinct_realization_keys": 1,
            "duplicate_forecast_groups": 0,
            "conflicting_forecast_groups": 0,
            "duplicate_realization_groups": 0,
            "conflicting_realization_groups": 0,
            "invalid_forecast_rows": 0,
            "invalid_realization_rows": 0,
            "orphan_realization_keys": 0,
            "orphan_realization_rows": 0,
            "eligible_forecast_rows": 1,
            "due_forecast_rows_without_eligible_realization": 0,
            "status_counts": {
                "eligible": 1,
            },
            "evaluation_asof": "2024-01-03T00:00:00Z",
            "require_due_coverage": True,
            "require_no_orphan_realizations": False,
            "passed": True,
            "eligibility": [
                {
                    "forecast_row_index": 0,
                    "status": "eligible",
                    "realization_row_index": 0,
                },
            ],
            "next_offset": None,
            "diagnostic_count": 0,
            "diagnostics": [],
            "omitted_diagnostics": 0,
        },
        "approx": False,
        "note": "Unique forecast and realization share target time, and both clocks are known at the evaluation instant.",
    },
    "skills.audit_join_fanout": {
        "arguments": {
            "left_rows": [
                {
                    "id": "a",
                },
                {
                    "id": "a",
                },
            ],
            "right_rows": [
                {
                    "id": "a",
                },
            ],
            "left_keys": [
                "id",
            ],
            "numeric_policy": "distinct",
            "null_policy": "never_match",
            "expected_relationship": "many_to_one",
        },
        "files": {},
        "expect": {
            "left_row_count": 2,
            "right_row_count": 1,
            "invalid_left_rows": 0,
            "invalid_right_rows": 0,
            "left_null_key_rows": 0,
            "right_null_key_rows": 0,
            "matched_left_rows": 2,
            "matched_right_rows": 1,
            "unmatched_valid_left_rows": 0,
            "unmatched_valid_right_rows": 0,
            "matched_key_groups": 1,
            "many_to_many_groups": 0,
            "left_rows_with_multiple_matches": 0,
            "right_rows_with_multiple_matches": 1,
            "predicted_inner_rows": 2,
            "predicted_left_join_rows": 2,
            "valid_subset_inner_rows": 2,
            "valid_subset_left_join_rows": 2,
            "relationship_violating_groups": 0,
            "expected_relationship": "many_to_one",
            "numeric_policy": "distinct",
            "null_policy": "never_match",
            "passed": True,
            "diagnostic_count": 1,
            "diagnostics": [
                {
                    "code": "fanout",
                    "table": "both",
                    "left_row_count": 2,
                    "right_row_count": 1,
                    "predicted_inner_rows": 2,
                    "left_row_indices": [
                        0,
                        1,
                    ],
                    "right_row_indices": [
                        0,
                    ],
                    "omitted_left_indices": 0,
                    "omitted_right_indices": 0,
                    "missing_fields": [],
                    "null_fields": [],
                    "violates_relationship": False,
                },
            ],
            "omitted_diagnostics": 0,
        },
        "approx": False,
        "note": "Two left rows and one right row on key a predict 2 inner rows; many-to-one allows that fanout.",
    },
    "skills.audit_lineage_graph": {
        "arguments": {
            "nodes": [
                "a",
                "b",
                "c",
            ],
            "edges": [
                {
                    "dependency_id": "a",
                    "dependent_id": "b",
                },
                {
                    "dependency_id": "b",
                    "dependent_id": "c",
                },
            ],
        },
        "files": {},
        "expect": {
            "verification_scope": "supplied_graph_structure_only",
            "receipt_verification": False,
            "edge_orientation": "dependency_to_dependent",
            "assessment": "valid",
            "passed": True,
            "node_declarations": 3,
            "distinct_nodes": 3,
            "edge_declarations": 2,
            "distinct_resolved_edges": 2,
            "duplicate_node_groups": 0,
            "extra_node_declarations": 0,
            "duplicate_edge_groups": 0,
            "extra_edge_declarations": 0,
            "unknown_reference_edges": 0,
            "distinct_unknown_node_ids": 0,
            "cyclic_components": 0,
            "cyclic_nodes": 0,
            "known_graph_is_acyclic": True,
            "dependent_nodes_blocked_by_cycles": 0,
            "topological_order": [
                "a",
                "b",
                "c",
            ],
            "duplicate_nodes": [],
            "duplicate_edges": [],
            "unknown_edges": [],
            "cycles": [],
            "omitted_duplicate_node_groups": 0,
            "omitted_duplicate_edge_groups": 0,
            "omitted_unknown_edges": 0,
            "omitted_cyclic_components": 0,
        },
        "approx": False,
        "note": "Chain a to b to c is acyclic; Kahn order with a heap emits a, b, c.",
    },
    "skills.audit_missingness": {
        "arguments": {
            "rows": [
                {
                    "a": 1,
                    "b": None,
                },
                {
                    "a": 2,
                    "b": 2,
                },
            ],
            "columns": [
                "a",
                "b",
            ],
            "empty_string_is_missing": False,
        },
        "files": {},
        "expect": {
            "row_count": 2,
            "column_count": 2,
            "empty_string_is_missing": False,
            "assessment": "observed",
            "no_missing_values": False,
            "complete_row_count": 1,
            "incomplete_row_count": 1,
            "complete_row_rate": 0.5,
            "effective_missing_cells": 1,
            "effective_missing_cell_rate": 0.25,
            "columns": [
                {
                    "column": "a",
                    "absent_count": 0,
                    "null_count": 0,
                    "empty_string_count": 0,
                    "effective_missing_count": 0,
                    "observed_value_count": 2,
                    "absent_rate": 0.0,
                    "null_rate": 0.0,
                    "empty_string_rate": 0.0,
                    "effective_missing_rate": 0.0,
                    "longest_missing_run": 0,
                    "leading_missing_run": 0,
                    "trailing_missing_run": 0,
                },
                {
                    "column": "b",
                    "absent_count": 0,
                    "null_count": 1,
                    "empty_string_count": 0,
                    "effective_missing_count": 1,
                    "observed_value_count": 1,
                    "absent_rate": 0.0,
                    "null_rate": 0.5,
                    "empty_string_rate": 0.0,
                    "effective_missing_rate": 0.5,
                    "longest_missing_run": 1,
                    "leading_missing_run": 1,
                    "trailing_missing_run": 0,
                },
            ],
            "incomplete_row_indices": [
                0,
            ],
            "omitted_incomplete_examples": 0,
        },
        "approx": False,
        "note": "One null in b over two rows is one missing cell of four, rate 0.25, and a leading run of 1.",
    },
    "skills.audit_missingness_association": {
        "arguments": {
            "rows": [
                {
                    "a": None,
                },
                {
                    "a": 1,
                    "b": 1,
                },
            ],
            "columns": [
                "a",
                "b",
            ],
            "empty_string_is_missing": False,
        },
        "files": {},
        "expect": {
            "row_count": 2,
            "column_count": 2,
            "pair_count": 1,
            "assessment": "observed",
            "interpretation": "descriptive_association_only",
            "empty_string_is_missing": False,
            "columns": [
                {
                    "column": "a",
                    "absent_count": 0,
                    "null_count": 1,
                    "empty_string_count": 0,
                    "missing_count": 1,
                    "missing_rate": 0.5,
                },
                {
                    "column": "b",
                    "absent_count": 1,
                    "null_count": 0,
                    "empty_string_count": 0,
                    "missing_count": 1,
                    "missing_rate": 0.5,
                },
            ],
            "associations": [
                {
                    "left_column": "a",
                    "right_column": "b",
                    "both_missing": 1,
                    "left_missing_only": 0,
                    "right_missing_only": 0,
                    "neither_missing": 1,
                    "joint_missing_rate": 0.5,
                    "jaccard": 1.0,
                    "phi": 1.0,
                    "left_missing_given_right_missing": 1.0,
                    "right_missing_given_left_missing": 1.0,
                },
            ],
        },
        "approx": False,
        "note": "Both indicators are missing on row 0 and present on row 1, so Jaccard and phi are exactly 1.",
    },
    "skills.audit_monotonic_sequences": {
        "arguments": {
            "observations": [
                {
                    "group": "g",
                    "event_time": "2024-01-01T00:00:00Z",
                    "value": 1,
                },
                {
                    "group": "g",
                    "event_time": "2024-01-01T00:00:01Z",
                    "value": 3,
                },
            ],
            "direction": "increasing",
            "strict": False,
            "allow_duplicate_event_times": False,
        },
        "files": {},
        "expect": {
            "row_count": 2,
            "group_count": 1,
            "direction": "increasing",
            "strict": False,
            "allow_duplicate_event_times": False,
            "assessment": "passed",
            "passed": True,
            "comparable_pairs": 1,
            "assessed_groups": 1,
            "unassessed_groups": 0,
            "event_time_reversals": 0,
            "duplicate_event_rows": 0,
            "numeric_direction_violations": 0,
            "violation_count": 0,
            "diagnostic_count": 0,
            "groups": [
                {
                    "group": "g",
                    "row_count": 2,
                    "comparable_pairs": 1,
                    "event_time_reversals": 0,
                    "duplicate_event_rows": 0,
                    "numeric_direction_violations": 0,
                    "passed": True,
                },
            ],
            "diagnostics": [],
            "omitted_diagnostics": 0,
        },
        "approx": False,
        "note": "One adjacent pair has a later clock and a larger value, so the increasing check passes.",
    },
}
